FORMAT: 1A

# Lenovo XClarity Management Console API

# GET /aicc

+ Response 200 (application/json)

  {
   "appliance": {
      "build": "110",
      "date": "2015-09-15_10-25-16",
      "name": "LXCA - 10.240.61.98",
      "runlevel": 3,
      "status": "Normal",
      "uuid": "bef3e2c3-a689-4734-aa79-2a21f21e8b97",
      "version": "1.1.0"
   },
   "appliance_states": [{
      "description": "Halt the appliance",
      "runlevel": 0
   },
   {
      "description": "Reboot the appliance",
      "runlevel": 6
   }],
   "date": {
      "date_time": "September 18, 2015 8:45:54 AM EST",
      "parts": {
         "yyyy": 2015,
         "mm": 9,
         "dd": 18,
         "hours": 8,
         "mins": 45
         "secs": 54,
      },
      "timezone": "Eastern Standard Time",
      "timezones": [{
         "daylight_saves": 0,
         "display_name": "GMT-12:00",
         "id": "Etc/GMT+12",
         "offset": -43200000,
         "uses_daylight": false,
         "utc_offset_raw": -43200000,
         "utc_offset_w_dst": -43200000
      },
      {
         "daylight_saves": 0,
         "display_name": "Eastern Standard Time",
         "id": "America/Grand_Turk",
         "offset": -14400000,
         "uses_daylight": false,
         "utc_offset_raw": -18000000,
         "utc_offset_w_dst": -14400000
      }],
      "timezone_id": "America/Cayman",
      "uses_daylight": true,
      "utc_offset": -18000000,
      "utc_offset_raw": -18000000,
      "utc_offset_w_dst": -18000000
   }
   "network_interfaces": [{
      "id": "eth0",
      "ip_addresses": [{
         "assign_method": "static",
         "ip": "fe80:0:0:0:200:ff:fe00:10%2",
         "ip_linklocal": "true",
         "prefix_length": 64,
         "version": 6
      },
      {
         "assign_method": "static",
         "ip": "10.240.61.98",
         "ip_linklocal": "false",
         "prefix_length": 22,
         "version": 4
      }],
      "mac_address": "00:00:00:00:00:10",
      "role": ["management", "osdeployment"]
   }],
   "ntp": {
      "servers": [{
         "authenticated": false,
         "server": "us.pool.ntp.org",
         "version": 1,
         "v3_key": "",
         "v3_key_index": 0,
         "v3_key_type": ""
      }]
   },
   "services": [{
      "id": "core",
      "initd": "xhmc-core",
      "pid": 52706,
      "state": 0
   },
   {
      "id": "watchdog",
      "initd": "sympl-watchdog",
      "pid": 52517,
      "state": 0
   }],
   "service_states": [{
      "description": "Service is running",
      "state": 0
   },
   {
      "description": "Special purpose state used to trigger restart through REST",
      "state": 191
   }],
   "subscriptions": [{
      "id": 1,
      "monitor_uri": "/aicc",
      "uri": "/ntpNotification"
   },
   {
      "id": 3,
      "monitor_uri": "",
      "uri": "/osdeployment/rest/internal/event/aicc"
   }],
  }

# PUT /aicc

+ Response 200 (application/json)

+ Response 400

# GET /aicc/network/ipdisable

+ Response 200 (application/json)

  {
   "ip_status": [{
      "ip_disable": 0,
      "ip_version": 4
   },
   {
      "ip_disable": 0,
      "ip_version": 6
   }]
  }

+ Response 404

# PUT /aicc/network/ipdisable

+ Response 200 (application/json)

+ Response 400

# GET /aicc/network/host

+ Response 200 (application/json)

  {
      "dns_servers": [{
          "ip": "192.168.3.1",
          "priority": 1
      },
      {
          "ip": "9.0.128.50",
          "priority": 2
      },
      {
          "ip": "9.0.130.50",
          "priority": 3
      },
      {
          "ip": "192.168.129.1",
          "priority": 4
      }],
      "domain_name": "(none),"
      "hostname": "localhost",
      "proxy": {
          "enabled": true,
          "ip": "1.1.1.1",
          "password": "password",
          "port": 11,
          "userid": "userid"
      }
  }

# PUT /aicc/network/host

+ Response 200 (application/json)

  {
      "dns_servers": [{
          "ip": "192.168.3.1",
          "priority": 1
      },
      {
          "ip": "9.0.128.50",
          "priority": 2
      },
      {
          "ip": "9.0.130.50",
          "priority": 3
      },
      {
          "ip": "192.168.129.1",
          "priority": 4
      }],
      "domain_name": "(none),"
      "hostname": "localhost",
      "proxy": {
          "enabled": true,
          "ip": "1.1.1.1",
          "password": "password",
          "port": 11,
          "userid": "userid"
      }
  }

+ Response 400

# GET /aicc/network/interfaces/{interface}

+ Parameters
    + interface - ID of the network interface.

+ Response 200 (application/json)

  [{
     "id": "eth0",
     "ip_addresses": [{
        "assign_method": "static",
        "ip": "fe80:0:0:0:20c:29ff:fec3:af6b%2",
        "ip_linklocal": "true",
        "prefix_length": 64,
        "version": 6
     },
     {
        "assign_method": "static",
        "ip": "10.240.70.20",
        "ip_linklocal": "false",
        "prefix_length": 23,
        "version": 4
     }],
     "mac_address": "00:0C:29:C3:AF:6B",
     "role": ["management", "osdeployment"]
  }]

+ Response 400

# PUT /aicc/network/interfaces/{interface}

+ Response 200 (application/json)
+ Response 400
+ Response 401
+ Response 403
+ Response 404
+ Response 409
+ Response 500

# GET /aicc/network/routes

+ Response 200 (application/json)

# PUT /aicc/network/routes

+ Response 200 (application/json)

  {
    "routes": [{
        "dev": "eth0",
        "destination": "100.10.10.10",
        "ip_version": 4,
        "nexthop": "192.168.56.1",
        "prefix_len": 32
    },
    {
        "dev": "eth0",
        "destination": "10.10.10.0",
        "ip_version": 4,
        "nexthop": "192.168.56.1",
        "prefix_len": 24
    },
    {
        "ip_version": 4,
        "nexthop": "10.0.3.2",
        "prefix_len": 0
    },
    {
        "dev": "eth1",
        "destination": "2001:db7:1::",
        "ip_version": 6,
        "nexthop": "2002:97b:c2bb:83d:5054:ff:fe2c:eefe",
        "prefix_len": 64
    },
    {
        "dev": "eth1",
        "destination": "2002:97b:face:83d:5054:ff:fe2c:eefe",
        "ip_version": 6,
        "nexthop": "2002:97b:c2bb:83d:5054:ff:fe2c:eefe",
        "prefix_len": 128
    }]
  }

+ Response 400

# GET /aicc/subscriptions

+ Response 200 (application/json)

  [{
     "id": 1,
     "monitor_uri": "/aicc/network/interfaces",
     "submonitor_uri": "",
     "uri": "/osdeployment/rest/internal/event/aicc"
  },
  {
     "id": 2,
     "monitor_uri": "/aicc",
     "submonitor_uri": "/ntp",
     "uri": "/ntpNotification"
  },
  {
     "id": 3,
     "monitor_uri": "/aicc/network/interfaces",
     "submonitor_uri": "",
     "uri": "/netchangenotsec"
  }]

+ Response 400

# PUT /aicc/subscriptions

+ Response 200 (application/json)
+ Response 400
+ Response 409

# DELETE /aicc/subscriptions/{id}

+ Response 200 (application/json)

+ Response 404

# GET /aicc/subscriptions/{id}

+ Response 200 (application/json)

+ Response 400
