FORMAT: 1A

# Canisters

# GET /canisters

+ Response 200 (application/json)
{
  "canisterList": [
    {
      "manufacturerId": "20301",
      "location": {
        "lowestRackUnit": 0,
        "location": "No Location Configured",
        "rack": "",
        "room": ""
      },
      "serialNumber": "G22L006",
      "driveBays": 0,
      "macAddress": "",
      "lanOverUsb": "enabled",
      "type": "ITE",
      "leds": [
        {
          "color": "Amber",
          "location": "FrontPanel",
          "name": "Fault",
          "state": "Off"
        },
        {
          "color": "Blue",
          "location": "FrontPanel",
          "name": "Identification",
          "state": "Off"
        },
        {
          "color": "Amber",
          "location": "FrontPanel",
          "name": "Check Log",
          "state": "On"
        },
        {
          "color": "Green",
          "location": "FrontPanel",
          "name": "Power",
          "state": "On"
        },
        {
          "color": "Green",
          "location": "Planar",
          "name": "BMC Heartbeat",
          "state": "Blinking"
        },
        {
          "color": "Amber",
          "location": "FrontPanel",
          "name": "Controller Fault",
          "state": "Off"
        },
        {
          "color": "Amber",
          "location": "FrontPanel",
          "name": "Internal Fault",
          "state": "Off"
        },
        {
          "color": "Yellow",
          "location": "Planar",
          "name": "IMM Fault",
          "state": "Off"
        }
      ],
      "description": "Device data missing",
      "errorFields": [
        {
          "Memory": "FETCH_FAILED"
        },
        {
          "RackCPU": "FETCH_FAILED"
        },
        {
          "BootMode": "FETCH_FAILED"
        },
        {
          "FlashDimm": "FETCH_FAILED"
        },
        {
          "VnicMode": "FETCH_FAILED"
        },
        {
          "IOCompatibilityData": "FETCH_FAILED"
        }
      ],
      "ipInterfaces": [
        {
          "IPv4enabled": true,
          "IPv4DHCPmode": "STATIC_ONLY",
          "IPv6enabled": true,
          "IPv6DHCPenabled": true,
          "IPv4assignments": [
            {
              "id": 0,
              "subnet": "255.255.252.0",
              "gateway": "0.0.0.0",
              "address": "10.240.72.69",
              "type": "INUSE"
            }
          ],
          "IPv6assignments": [
            {
              "id": 0,
              "scope": "Global",
              "gateway": "0:0:0:0:0:0:0:0",
              "source": "Static",
              "address": "fd6d:8bc2:3ad4:0:5ef3:fcff:fe6f:bcc",
              "prefix": 64,
              "type": "INUSE"
            },
            {
              "id": 0,
              "scope": "Global",
              "gateway": "0:0:0:0:0:0:0:0",
              "source": "Stateless",
              "address": "fd55:faaf:e1ab:20fc:5ef3:fcff:fe6f:bcc",
              "prefix": 64,
              "type": "INUSE"
            },
            {
              "id": 0,
              "scope": "Unknown",
              "gateway": "0:0:0:0:0:0:0:0",
              "source": "Unknown",
              "address": "fe80:0:0:0:5ef3:fcff:fe6f:bcc",
              "prefix": 64,
              "type": "UNKNOWN"
            }
          ],
          "name": "eth0",
          "IPv6statelessEnabled": true,
          "label": "unknown",
          "IPv6staticEnabled": true
        }
      ],
      "firmware": [
        {
          "status": "Inactive",
          "name": "UEFI Firmware/BIOS",
          "role": "Backup",
          "date": "",
          "type": "UEFI",
          "build": "0000000",
          "version": "0.00"
        },
        {
          "status": "Inactive",
          "name": "UEFI Backup Firmware/BIOS",
          "role": "Backup",
          "date": "",
          "type": "UEFI-Backup",
          "build": "0000000",
          "version": "0.00"
        },
        {
          "status": "Active",
          "name": "DSA Diagnostic Software",
          "role": "Primary",
          "date": "",
          "type": "DSA",
          "build": "*",
          "version": "65535.65535"
        },
        {
          "status": "Active",
          "name": "IMM2 Firmware",
          "role": "Primary",
          "date": "2013-10-08T00:00:00Z",
          "type": "IMM2",
          "build": "1AOO43S",
          "version": "2.65"
        },
        {
          "status": "Inactive",
          "name": "IMM2 Backup Firmware",
          "role": "Backup",
          "date": "2013-07-29T00:00:00Z",
          "type": "IMM2-Backup",
          "build": "1AOO41X",
          "version": "2.60"
        }
      ],
      "bladeState": 1,
      "activationKeys": [],
      "hostname": "IMM2-5cf3fc6f0bcc",
      "parent": {
        "uuid": "B8106786386411E19AE3EF8BCD385476",
        "uri": "node/B8106786386411E19AE3EF8BCD385476"
      },
      "FRU": "90Y7691",
      "uri": "canister/457784225BA511E18290B4F27BD253A5",
      "vnicMode": "disabled",
      "ipv6ServiceAddress": "",
      "powerStatus": 8,
      "ipv6Addresses": [
        "fd6d:8bc2:3ad4:0:5ef3:fcff:fe6f:bcc",
        "fd55:faaf:e1ab:20fc:5ef3:fcff:fe6f:bcc",
        "fe80:0:0:0:5ef3:fcff:fe6f:bcc"
      ],
      "serviceHostName": "",
      "manufacturer": "IBM",
      "slots": [
        5
      ],
      "vpdID": "3",
      "uuid": "457784225BA511E18290B4F27BD253A5",
      "memoryModules": [],
      "fruSerialNumber": "YM11BG22D03F",
      "model": "A49",
      "contact": "No Contact Configured",
      "dataHandle": 1475537856727,
      "ipv4Addresses": [
        "10.240.72.69",
        "169.254.95.118"
      ],
      "cmmDisplayName": "Node 05 - 01",
      "backedBy": "real",
      "name": "Storage ITE Mgm",
      "memorySlots": 2,
      "drives": [],
      "cmmHealthState": "Normal",
      "userDescription": "",
      "subSlots": [
        1
      ],
      "ipv4ServiceAddress": "10.240.72.71",
      "partNumber": "90Y7627",
      "machineType": "4939",
      "domainName": "",
      "processors": [],
      "processorSlots": 1,
      "productId": "374",
      "posID": "384",
      "subType": "SRC",
      "productName": "PRODUCT DESCRIPTION STORAGE ITE PRODUCT DESCRIPTION STORAGE ITE PRODUCT DESCRIPTION STORAGE ITE"
    },
    {
      "manufacturerId": "20301",
      "location": {
        "lowestRackUnit": 0,
        "location": "No Location Configured",
        "rack": "",
        "room": ""
      },
      "serialNumber": "G22L006",
      "driveBays": 0,
      "macAddress": "",
      "lanOverUsb": "enabled",
      "type": "ITE",
      "leds": [
        {
          "color": "Amber",
          "location": "FrontPanel",
          "name": "Fault",
          "state": "Off"
        },
        {
          "color": "Blue",
          "location": "FrontPanel",
          "name": "Identification",
          "state": "Off"
        },
        {
          "color": "Amber",
          "location": "FrontPanel",
          "name": "Check Log",
          "state": "On"
        },
        {
          "color": "Green",
          "location": "FrontPanel",
          "name": "Power",
          "state": "On"
        },
        {
          "color": "Green",
          "location": "Planar",
          "name": "BMC Heartbeat",
          "state": "Blinking"
        },
        {
          "color": "Amber",
          "location": "FrontPanel",
          "name": "Controller Fault",
          "state": "Off"
        },
        {
          "color": "Amber",
          "location": "FrontPanel",
          "name": "Internal Fault",
          "state": "Off"
        },
        {
          "color": "Yellow",
          "location": "Planar",
          "name": "IMM Fault",
          "state": "Off"
        }
      ],
      "description": "Device data missing",
      "errorFields": [
        {
          "Memory": "FETCH_FAILED"
        },
        {
          "RackCPU": "FETCH_FAILED"
        },
        {
          "BootMode": "FETCH_FAILED"
        },
        {
          "FlashDimm": "FETCH_FAILED"
        },
        {
          "VnicMode": "FETCH_FAILED"
        },
        {
          "IOCompatibilityData": "NETWORK_FAIL"
        }
      ],
      "ipInterfaces": [
        {
          "IPv4enabled": true,
          "IPv4DHCPmode": "STATIC_ONLY",
          "IPv6enabled": true,
          "IPv6DHCPenabled": true,
          "IPv4assignments": [
            {
              "id": 0,
              "subnet": "255.255.252.0",
              "gateway": "0.0.0.0",
              "address": "10.240.72.70",
              "type": "INUSE"
            }
          ],
          "IPv6assignments": [
            {
              "id": 0,
              "scope": "Global",
              "gateway": "0:0:0:0:0:0:0:0",
              "source": "Stateless",
              "address": "fd55:faaf:e1ab:20fc:5ef3:fcff:fe6f:c64",
              "prefix": 64,
              "type": "INUSE"
            },
            {
              "id": 0,
              "scope": "Global",
              "gateway": "0:0:0:0:0:0:0:0",
              "source": "Static",
              "address": "fd6d:8bc2:3ad4:0:5ef3:fcff:fe6f:c64",
              "prefix": 64,
              "type": "INUSE"
            },
            {
              "id": 0,
              "scope": "Unknown",
              "gateway": "0:0:0:0:0:0:0:0",
              "source": "Unknown",
              "address": "fe80:0:0:0:5ef3:fcff:fe6f:c64",
              "prefix": 64,
              "type": "UNKNOWN"
            }
          ],
          "name": "eth0",
          "IPv6statelessEnabled": true,
          "label": "unknown",
          "IPv6staticEnabled": true
        }
      ],
      "firmware": [
        {
          "status": "Inactive",
          "name": "UEFI Firmware/BIOS",
          "role": "Backup",
          "date": "",
          "type": "UEFI",
          "build": "0000000",
          "version": "0.00"
        },
        {
          "status": "Inactive",
          "name": "UEFI Backup Firmware/BIOS",
          "role": "Backup",
          "date": "",
          "type": "UEFI-Backup",
          "build": "0000000",
          "version": "0.00"
        },
        {
          "status": "Active",
          "name": "DSA Diagnostic Software",
          "role": "Primary",
          "date": "",
          "type": "DSA",
          "build": "*",
          "version": "65535.65535"
        },
        {
          "status": "Active",
          "name": "IMM2 Firmware",
          "role": "Primary",
          "date": "2013-10-08T00:00:00Z",
          "type": "IMM2",
          "build": "1AOO43S",
          "version": "2.65"
        },
        {
          "status": "Inactive",
          "name": "IMM2 Backup Firmware",
          "role": "Backup",
          "date": "2013-07-29T00:00:00Z",
          "type": "IMM2-Backup",
          "build": "1AOO41X",
          "version": "2.60"
        }
      ],
      "bladeState": 1,
      "activationKeys": [],
      "hostname": "IMM2-5cf3fc6f0c64",
      "parent": {
        "uuid": "B8106786386411E19AE3EF8BCD385476",
        "uri": "node/B8106786386411E19AE3EF8BCD385476"
      },
      "FRU": "90Y7691",
      "uri": "canister/E0D47B8A5BC511E1B5D1D13BF6351882",
      "vnicMode": "disabled",
      "ipv6ServiceAddress": "",
      "powerStatus": 8,
      "ipv6Addresses": [
        "fd55:faaf:e1ab:20fc:5ef3:fcff:fe6f:c64",
        "fd6d:8bc2:3ad4:0:5ef3:fcff:fe6f:c64",
        "fe80:0:0:0:5ef3:fcff:fe6f:c64"
      ],
      "serviceHostName": "",
      "manufacturer": "IBM",
      "slots": [
        5
      ],
      "vpdID": "3",
      "uuid": "E0D47B8A5BC511E1B5D1D13BF6351882",
      "memoryModules": [],
      "fruSerialNumber": "YM11BG22D042",
      "model": "A49",
      "contact": "No Contact Configured",
      "dataHandle": 1475537856456,
      "ipv4Addresses": [
        "10.240.72.70",
        "169.254.95.118"
      ],
      "cmmDisplayName": "Node 05 - 02",
      "backedBy": "real",
      "name": "Storage ITE Mgm",
      "memorySlots": 2,
      "drives": [],
      "cmmHealthState": "Normal",
      "userDescription": "",
      "subSlots": [
        2
      ],
      "ipv4ServiceAddress": "10.240.72.72",
      "partNumber": "90Y7627",
      "machineType": "4939",
      "domainName": "",
      "processors": [],
      "processorSlots": 1,
      "productId": "374",
      "posID": "384",
      "subType": "SRC",
      "productName": "PRODUCT DESCRIPTION STORAGE ITE PRODUCT DESCRIPTION STORAGE ITE PRODUCT DESCRIPTION STORAGE ITE"
    }
  ]
}
+ Response 400
+ Response 401
+ Response 404
+ Response 409
+ Response 500

# GET /canisters?includeAttributes=memorySlots

+ Response 200 (application/json)
{
  "canisterList": [
    {
      "parent": {
        "uuid": "B8106786386411E19AE3EF8BCD385476",
        "uri": "node/B8106786386411E19AE3EF8BCD385476"
      },
      "memorySlots": 2,
      "uuid": "457784225BA511E18290B4F27BD253A5",
      "uri": "canister/457784225BA511E18290B4F27BD253A5",
      "dataHandle": 1475537856727
    },
    {
      "parent": {
        "uuid": "B8106786386411E19AE3EF8BCD385476",
        "uri": "node/B8106786386411E19AE3EF8BCD385476"
      },
      "memorySlots": 2,
      "uuid": "E0D47B8A5BC511E1B5D1D13BF6351882",
      "uri": "canister/E0D47B8A5BC511E1B5D1D13BF6351882",
      "dataHandle": 1475537856456
    }
  ]
}
+ Response 400
+ Response 401
+ Response 404
+ Response 409
+ Response 500

# GET /canisters?excludeAttributes=memorySlots

+ Response 200 (application/json)
{
  "canisterList": [
    {
      "model": "A49",
      "manufacturerId": "20301",
      "location": {
        "lowestRackUnit": 0,
        "location": "No Location Configured",
        "rack": "",
        "room": ""
      },
      "serialNumber": "G22L006",
      "driveBays": 0,
      "macAddress": "",
      "type": "ITE",
      "lanOverUsb": "enabled",
      "contact": "No Contact Configured",
      "dataHandle": 1475537856727,
      "ipv4Addresses": [
        "10.240.72.69",
        "169.254.95.118"
      ],
      "backedBy": "real",
      "cmmDisplayName": "Node 05 - 01",
      "leds": [
        {
          "color": "Amber",
          "location": "FrontPanel",
          "name": "Fault",
          "state": "Off"
        },
        {
          "color": "Blue",
          "location": "FrontPanel",
          "name": "Identification",
          "state": "Off"
        },
        {
          "color": "Amber",
          "location": "FrontPanel",
          "name": "Check Log",
          "state": "On"
        },
        {
          "color": "Green",
          "location": "FrontPanel",
          "name": "Power",
          "state": "On"
        },
        {
          "color": "Green",
          "location": "Planar",
          "name": "BMC Heartbeat",
          "state": "Blinking"
        },
        {
          "color": "Amber",
          "location": "FrontPanel",
          "name": "Controller Fault",
          "state": "Off"
        },
        {
          "color": "Amber",
          "location": "FrontPanel",
          "name": "Internal Fault",
          "state": "Off"
        },
        {
          "color": "Yellow",
          "location": "Planar",
          "name": "IMM Fault",
          "state": "Off"
        }
      ],
      "description": "Device data missing",
      "name": "Storage ITE Mgm",
      "errorFields": [
        {
          "Memory": "FETCH_FAILED"
        },
        {
          "RackCPU": "FETCH_FAILED"
        },
        {
          "BootMode": "FETCH_FAILED"
        },
        {
          "FlashDimm": "FETCH_FAILED"
        },
        {
          "VnicMode": "FETCH_FAILED"
        },
        {
          "IOCompatibilityData": "FETCH_FAILED"
        }
      ],
      "cmmHealthState": "Normal",
      "drives": [],
      "userDescription": "",
      "subSlots": [
        1
      ],
      "ipv4ServiceAddress": "10.240.72.71",
      "partNumber": "90Y7627",
      "ipInterfaces": [
        {
          "IPv4enabled": true,
          "IPv4DHCPmode": "STATIC_ONLY",
          "IPv6enabled": true,
          "IPv6DHCPenabled": true,
          "IPv4assignments": [
            {
              "id": 0,
              "subnet": "255.255.252.0",
              "gateway": "0.0.0.0",
              "address": "10.240.72.69",
              "type": "INUSE"
            }
          ],
          "IPv6assignments": [
            {
              "id": 0,
              "scope": "Global",
              "gateway": "0:0:0:0:0:0:0:0",
              "source": "Static",
              "address": "fd6d:8bc2:3ad4:0:5ef3:fcff:fe6f:bcc",
              "prefix": 64,
              "type": "INUSE"
            },
            {
              "id": 0,
              "scope": "Global",
              "gateway": "0:0:0:0:0:0:0:0",
              "source": "Stateless",
              "address": "fd55:faaf:e1ab:20fc:5ef3:fcff:fe6f:bcc",
              "prefix": 64,
              "type": "INUSE"
            },
            {
              "id": 0,
              "scope": "Unknown",
              "gateway": "0:0:0:0:0:0:0:0",
              "source": "Unknown",
              "address": "fe80:0:0:0:5ef3:fcff:fe6f:bcc",
              "prefix": 64,
              "type": "UNKNOWN"
            }
          ],
          "name": "eth0",
          "IPv6statelessEnabled": true,
          "label": "unknown",
          "IPv6staticEnabled": true
        }
      ],
      "firmware": [
        {
          "status": "Inactive",
          "name": "UEFI Firmware/BIOS",
          "role": "Backup",
          "date": "",
          "type": "UEFI",
          "build": "0000000",
          "version": "0.00"
        },
        {
          "status": "Inactive",
          "name": "UEFI Backup Firmware/BIOS",
          "role": "Backup",
          "date": "",
          "type": "UEFI-Backup",
          "build": "0000000",
          "version": "0.00"
        },
        {
          "status": "Active",
          "name": "DSA Diagnostic Software",
          "role": "Primary",
          "date": "",
          "type": "DSA",
          "build": "*",
          "version": "65535.65535"
        },
        {
          "status": "Active",
          "name": "IMM2 Firmware",
          "role": "Primary",
          "date": "2013-10-08T00:00:00Z",
          "type": "IMM2",
          "build": "1AOO43S",
          "version": "2.65"
        },
        {
          "status": "Inactive",
          "name": "IMM2 Backup Firmware",
          "role": "Backup",
          "date": "2013-07-29T00:00:00Z",
          "type": "IMM2-Backup",
          "build": "1AOO41X",
          "version": "2.60"
        }
      ],
      "bladeState": 1,
      "machineType": "4939",
      "activationKeys": [],
      "parent": {
        "uuid": "B8106786386411E19AE3EF8BCD385476",
        "uri": "node/B8106786386411E19AE3EF8BCD385476"
      },
      "hostname": "IMM2-5cf3fc6f0bcc",
      "domainName": "",
      "FRU": "90Y7691",
      "processors": [],
      "uri": "canister/457784225BA511E18290B4F27BD253A5",
      "processorSlots": 1,
      "vnicMode": "disabled",
      "productId": "374",
      "ipv6ServiceAddress": "",
      "powerStatus": 8,
      "ipv6Addresses": [
        "fd6d:8bc2:3ad4:0:5ef3:fcff:fe6f:bcc",
        "fd55:faaf:e1ab:20fc:5ef3:fcff:fe6f:bcc",
        "fe80:0:0:0:5ef3:fcff:fe6f:bcc"
      ],
      "posID": "384",
      "slots": [
        5
      ],
      "subType": "SRC",
      "manufacturer": "IBM",
      "serviceHostName": "",
      "vpdID": "3",
      "uuid": "457784225BA511E18290B4F27BD253A5",
      "productName": "PRODUCT DESCRIPTION STORAGE ITE PRODUCT DESCRIPTION STORAGE ITE PRODUCT DESCRIPTION STORAGE ITE",
      "memoryModules": [],
      "fruSerialNumber": "YM11BG22D03F"
    },
    {
      "model": "A49",
      "manufacturerId": "20301",
      "location": {
        "lowestRackUnit": 0,
        "location": "No Location Configured",
        "rack": "",
        "room": ""
      },
      "serialNumber": "G22L006",
      "driveBays": 0,
      "macAddress": "",
      "type": "ITE",
      "lanOverUsb": "enabled",
      "contact": "No Contact Configured",
      "dataHandle": 1475537856456,
      "ipv4Addresses": [
        "10.240.72.70",
        "169.254.95.118"
      ],
      "backedBy": "real",
      "cmmDisplayName": "Node 05 - 02",
      "leds": [
        {
          "color": "Amber",
          "location": "FrontPanel",
          "name": "Fault",
          "state": "Off"
        },
        {
          "color": "Blue",
          "location": "FrontPanel",
          "name": "Identification",
          "state": "Off"
        },
        {
          "color": "Amber",
          "location": "FrontPanel",
          "name": "Check Log",
          "state": "On"
        },
        {
          "color": "Green",
          "location": "FrontPanel",
          "name": "Power",
          "state": "On"
        },
        {
          "color": "Green",
          "location": "Planar",
          "name": "BMC Heartbeat",
          "state": "Blinking"
        },
        {
          "color": "Amber",
          "location": "FrontPanel",
          "name": "Controller Fault",
          "state": "Off"
        },
        {
          "color": "Amber",
          "location": "FrontPanel",
          "name": "Internal Fault",
          "state": "Off"
        },
        {
          "color": "Yellow",
          "location": "Planar",
          "name": "IMM Fault",
          "state": "Off"
        }
      ],
      "description": "Device data missing",
      "name": "Storage ITE Mgm",
      "errorFields": [
        {
          "Memory": "FETCH_FAILED"
        },
        {
          "RackCPU": "FETCH_FAILED"
        },
        {
          "BootMode": "FETCH_FAILED"
        },
        {
          "FlashDimm": "FETCH_FAILED"
        },
        {
          "VnicMode": "FETCH_FAILED"
        },
        {
          "IOCompatibilityData": "NETWORK_FAIL"
        }
      ],
      "cmmHealthState": "Normal",
      "drives": [],
      "userDescription": "",
      "subSlots": [
        2
      ],
      "ipv4ServiceAddress": "10.240.72.72",
      "partNumber": "90Y7627",
      "ipInterfaces": [
        {
          "IPv4enabled": true,
          "IPv4DHCPmode": "STATIC_ONLY",
          "IPv6enabled": true,
          "IPv6DHCPenabled": true,
          "IPv4assignments": [
            {
              "id": 0,
              "subnet": "255.255.252.0",
              "gateway": "0.0.0.0",
              "address": "10.240.72.70",
              "type": "INUSE"
            }
          ],
          "IPv6assignments": [
            {
              "id": 0,
              "scope": "Global",
              "gateway": "0:0:0:0:0:0:0:0",
              "source": "Stateless",
              "address": "fd55:faaf:e1ab:20fc:5ef3:fcff:fe6f:c64",
              "prefix": 64,
              "type": "INUSE"
            },
            {
              "id": 0,
              "scope": "Global",
              "gateway": "0:0:0:0:0:0:0:0",
              "source": "Static",
              "address": "fd6d:8bc2:3ad4:0:5ef3:fcff:fe6f:c64",
              "prefix": 64,
              "type": "INUSE"
            },
            {
              "id": 0,
              "scope": "Unknown",
              "gateway": "0:0:0:0:0:0:0:0",
              "source": "Unknown",
              "address": "fe80:0:0:0:5ef3:fcff:fe6f:c64",
              "prefix": 64,
              "type": "UNKNOWN"
            }
          ],
          "name": "eth0",
          "IPv6statelessEnabled": true,
          "label": "unknown",
          "IPv6staticEnabled": true
        }
      ],
      "firmware": [
        {
          "status": "Inactive",
          "name": "UEFI Firmware/BIOS",
          "role": "Backup",
          "date": "",
          "type": "UEFI",
          "build": "0000000",
          "version": "0.00"
        },
        {
          "status": "Inactive",
          "name": "UEFI Backup Firmware/BIOS",
          "role": "Backup",
          "date": "",
          "type": "UEFI-Backup",
          "build": "0000000",
          "version": "0.00"
        },
        {
          "status": "Active",
          "name": "DSA Diagnostic Software",
          "role": "Primary",
          "date": "",
          "type": "DSA",
          "build": "*",
          "version": "65535.65535"
        },
        {
          "status": "Active",
          "name": "IMM2 Firmware",
          "role": "Primary",
          "date": "2013-10-08T00:00:00Z",
          "type": "IMM2",
          "build": "1AOO43S",
          "version": "2.65"
        },
        {
          "status": "Inactive",
          "name": "IMM2 Backup Firmware",
          "role": "Backup",
          "date": "2013-07-29T00:00:00Z",
          "type": "IMM2-Backup",
          "build": "1AOO41X",
          "version": "2.60"
        }
      ],
      "bladeState": 1,
      "machineType": "4939",
      "activationKeys": [],
      "parent": {
        "uuid": "B8106786386411E19AE3EF8BCD385476",
        "uri": "node/B8106786386411E19AE3EF8BCD385476"
      },
      "hostname": "IMM2-5cf3fc6f0c64",
      "domainName": "",
      "FRU": "90Y7691",
      "processors": [],
      "uri": "canister/E0D47B8A5BC511E1B5D1D13BF6351882",
      "processorSlots": 1,
      "vnicMode": "disabled",
      "productId": "374",
      "ipv6ServiceAddress": "",
      "powerStatus": 8,
      "ipv6Addresses": [
        "fd55:faaf:e1ab:20fc:5ef3:fcff:fe6f:c64",
        "fd6d:8bc2:3ad4:0:5ef3:fcff:fe6f:c64",
        "fe80:0:0:0:5ef3:fcff:fe6f:c64"
      ],
      "posID": "384",
      "slots": [
        5
      ],
      "subType": "SRC",
      "manufacturer": "IBM",
      "serviceHostName": "",
      "vpdID": "3",
      "uuid": "E0D47B8A5BC511E1B5D1D13BF6351882",
      "productName": "PRODUCT DESCRIPTION STORAGE ITE PRODUCT DESCRIPTION STORAGE ITE PRODUCT DESCRIPTION STORAGE ITE",
      "memoryModules": [],
      "fruSerialNumber": "YM11BG22D042"
    }
  ]
}
+ Response 400
+ Response 401
+ Response 404
+ Response 409
+ Response 500

# GET /canisters/457784225BA511E18290B4F27BD253A5

+ Response 200 (application/json)
{
  "manufacturerId": "20301",
  "location": {
    "lowestRackUnit": 0,
    "location": "No Location Configured",
    "rack": "",
    "room": ""
  },
  "serialNumber": "G22L006",
  "driveBays": 0,
  "macAddress": "",
  "lanOverUsb": "enabled",
  "type": "ITE",
  "leds": [
    {
      "color": "Amber",
      "location": "FrontPanel",
      "name": "Fault",
      "state": "Off"
    },
    {
      "color": "Blue",
      "location": "FrontPanel",
      "name": "Identification",
      "state": "Off"
    },
    {
      "color": "Amber",
      "location": "FrontPanel",
      "name": "Check Log",
      "state": "On"
    },
    {
      "color": "Green",
      "location": "FrontPanel",
      "name": "Power",
      "state": "On"
    },
    {
      "color": "Green",
      "location": "Planar",
      "name": "BMC Heartbeat",
      "state": "Blinking"
    },
    {
      "color": "Amber",
      "location": "FrontPanel",
      "name": "Controller Fault",
      "state": "Off"
    },
    {
      "color": "Amber",
      "location": "FrontPanel",
      "name": "Internal Fault",
      "state": "Off"
    },
    {
      "color": "Yellow",
      "location": "Planar",
      "name": "IMM Fault",
      "state": "Off"
    }
  ],
  "description": "Device data missing",
  "errorFields": [
    {
      "Memory": "FETCH_FAILED"
    },
    {
      "RackCPU": "FETCH_FAILED"
    },
    {
      "BootMode": "FETCH_FAILED"
    },
    {
      "FlashDimm": "FETCH_FAILED"
    },
    {
      "VnicMode": "FETCH_FAILED"
    },
    {
      "IOCompatibilityData": "FETCH_FAILED"
    }
  ],
  "ipInterfaces": [
    {
      "IPv4enabled": true,
      "IPv4DHCPmode": "STATIC_ONLY",
      "IPv6enabled": true,
      "IPv6DHCPenabled": true,
      "IPv4assignments": [
        {
          "id": 0,
          "subnet": "255.255.252.0",
          "gateway": "0.0.0.0",
          "address": "10.240.72.69",
          "type": "INUSE"
        }
      ],
      "IPv6assignments": [
        {
          "id": 0,
          "scope": "Global",
          "gateway": "0:0:0:0:0:0:0:0",
          "source": "Static",
          "address": "fd6d:8bc2:3ad4:0:5ef3:fcff:fe6f:bcc",
          "prefix": 64,
          "type": "INUSE"
        },
        {
          "id": 0,
          "scope": "Global",
          "gateway": "0:0:0:0:0:0:0:0",
          "source": "Stateless",
          "address": "fd55:faaf:e1ab:20fc:5ef3:fcff:fe6f:bcc",
          "prefix": 64,
          "type": "INUSE"
        },
        {
          "id": 0,
          "scope": "Unknown",
          "gateway": "0:0:0:0:0:0:0:0",
          "source": "Unknown",
          "address": "fe80:0:0:0:5ef3:fcff:fe6f:bcc",
          "prefix": 64,
          "type": "UNKNOWN"
        }
      ],
      "name": "eth0",
      "IPv6statelessEnabled": true,
      "label": "unknown",
      "IPv6staticEnabled": true
    }
  ],
  "firmware": [
    {
      "status": "Inactive",
      "name": "UEFI Firmware/BIOS",
      "role": "Backup",
      "date": "",
      "type": "UEFI",
      "build": "0000000",
      "version": "0.00"
    },
    {
      "status": "Inactive",
      "name": "UEFI Backup Firmware/BIOS",
      "role": "Backup",
      "date": "",
      "type": "UEFI-Backup",
      "build": "0000000",
      "version": "0.00"
    },
    {
      "status": "Active",
      "name": "DSA Diagnostic Software",
      "role": "Primary",
      "date": "",
      "type": "DSA",
      "build": "*",
      "version": "65535.65535"
    },
    {
      "status": "Active",
      "name": "IMM2 Firmware",
      "role": "Primary",
      "date": "2013-10-08T00:00:00Z",
      "type": "IMM2",
      "build": "1AOO43S",
      "version": "2.65"
    },
    {
      "status": "Inactive",
      "name": "IMM2 Backup Firmware",
      "role": "Backup",
      "date": "2013-07-29T00:00:00Z",
      "type": "IMM2-Backup",
      "build": "1AOO41X",
      "version": "2.60"
    }
  ],
  "bladeState": 1,
  "activationKeys": [],
  "hostname": "IMM2-5cf3fc6f0bcc",
  "parent": {
    "uuid": "B8106786386411E19AE3EF8BCD385476",
    "uri": "node/B8106786386411E19AE3EF8BCD385476"
  },
  "FRU": "90Y7691",
  "uri": "canister/457784225BA511E18290B4F27BD253A5",
  "vnicMode": "disabled",
  "ipv6ServiceAddress": "",
  "powerStatus": 8,
  "ipv6Addresses": [
    "fd6d:8bc2:3ad4:0:5ef3:fcff:fe6f:bcc",
    "fd55:faaf:e1ab:20fc:5ef3:fcff:fe6f:bcc",
    "fe80:0:0:0:5ef3:fcff:fe6f:bcc"
  ],
  "serviceHostName": "",
  "manufacturer": "IBM",
  "slots": [
    5
  ],
  "vpdID": "3",
  "uuid": "457784225BA511E18290B4F27BD253A5",
  "memoryModules": [],
  "fruSerialNumber": "YM11BG22D03F",
  "model": "A49",
  "contact": "No Contact Configured",
  "dataHandle": 1475537856727,
  "ipv4Addresses": [
    "10.240.72.69",
    "169.254.95.118"
  ],
  "cmmDisplayName": "Node 05 - 01",
  "backedBy": "real",
  "name": "Storage ITE Mgm",
  "memorySlots": 2,
  "drives": [],
  "cmmHealthState": "Normal",
  "userDescription": "",
  "subSlots": [
    1
  ],
  "ipv4ServiceAddress": "10.240.72.71",
  "partNumber": "90Y7627",
  "machineType": "4939",
  "domainName": "",
  "processors": [],
  "processorSlots": 1,
  "productId": "374",
  "posID": "384",
  "subType": "SRC",
  "productName": "PRODUCT DESCRIPTION STORAGE ITE PRODUCT DESCRIPTION STORAGE ITE PRODUCT DESCRIPTION STORAGE ITE"
}
+ Response 400
+ Response 401
+ Response 404
+ Response 409
+ Response 500

# GET /canisters/457784225BA511E18290B4F27BD253A5?includeAttributes=memorySlots

+ Response 200 (application/json)
{
  "parent": {
    "uuid": "B8106786386411E19AE3EF8BCD385476",
    "uri": "node/B8106786386411E19AE3EF8BCD385476"
  },
  "memorySlots": 2,
  "uuid": "457784225BA511E18290B4F27BD253A5",
  "uri": "canister/457784225BA511E18290B4F27BD253A5",
  "dataHandle": 1475537856727
}
+ Response 400
+ Response 401
+ Response 404
+ Response 409
+ Response 500

# GET /canisters/457784225BA511E18290B4F27BD253A5?excludeAttributes=memorySlots

+ Response 200 (application/json)
{
  "model": "A49",
  "manufacturerId": "20301",
  "location": {
    "lowestRackUnit": 0,
    "location": "No Location Configured",
    "rack": "",
    "room": ""
  },
  "serialNumber": "G22L006",
  "driveBays": 0,
  "macAddress": "",
  "type": "ITE",
  "lanOverUsb": "enabled",
  "contact": "No Contact Configured",
  "dataHandle": 1475537856727,
  "ipv4Addresses": [
    "10.240.72.69",
    "169.254.95.118"
  ],
  "backedBy": "real",
  "cmmDisplayName": "Node 05 - 01",
  "leds": [
    {
      "color": "Amber",
      "location": "FrontPanel",
      "name": "Fault",
      "state": "Off"
    },
    {
      "color": "Blue",
      "location": "FrontPanel",
      "name": "Identification",
      "state": "Off"
    },
    {
      "color": "Amber",
      "location": "FrontPanel",
      "name": "Check Log",
      "state": "On"
    },
    {
      "color": "Green",
      "location": "FrontPanel",
      "name": "Power",
      "state": "On"
    },
    {
      "color": "Green",
      "location": "Planar",
      "name": "BMC Heartbeat",
      "state": "Blinking"
    },
    {
      "color": "Amber",
      "location": "FrontPanel",
      "name": "Controller Fault",
      "state": "Off"
    },
    {
      "color": "Amber",
      "location": "FrontPanel",
      "name": "Internal Fault",
      "state": "Off"
    },
    {
      "color": "Yellow",
      "location": "Planar",
      "name": "IMM Fault",
      "state": "Off"
    }
  ],
  "description": "Device data missing",
  "name": "Storage ITE Mgm",
  "errorFields": [
    {
      "Memory": "FETCH_FAILED"
    },
    {
      "RackCPU": "FETCH_FAILED"
    },
    {
      "BootMode": "FETCH_FAILED"
    },
    {
      "FlashDimm": "FETCH_FAILED"
    },
    {
      "VnicMode": "FETCH_FAILED"
    },
    {
      "IOCompatibilityData": "FETCH_FAILED"
    }
  ],
  "cmmHealthState": "Normal",
  "drives": [],
  "userDescription": "",
  "subSlots": [
    1
  ],
  "ipv4ServiceAddress": "10.240.72.71",
  "partNumber": "90Y7627",
  "ipInterfaces": [
    {
      "IPv4enabled": true,
      "IPv4DHCPmode": "STATIC_ONLY",
      "IPv6enabled": true,
      "IPv6DHCPenabled": true,
      "IPv4assignments": [
        {
          "id": 0,
          "subnet": "255.255.252.0",
          "gateway": "0.0.0.0",
          "address": "10.240.72.69",
          "type": "INUSE"
        }
      ],
      "IPv6assignments": [
        {
          "id": 0,
          "scope": "Global",
          "gateway": "0:0:0:0:0:0:0:0",
          "source": "Static",
          "address": "fd6d:8bc2:3ad4:0:5ef3:fcff:fe6f:bcc",
          "prefix": 64,
          "type": "INUSE"
        },
        {
          "id": 0,
          "scope": "Global",
          "gateway": "0:0:0:0:0:0:0:0",
          "source": "Stateless",
          "address": "fd55:faaf:e1ab:20fc:5ef3:fcff:fe6f:bcc",
          "prefix": 64,
          "type": "INUSE"
        },
        {
          "id": 0,
          "scope": "Unknown",
          "gateway": "0:0:0:0:0:0:0:0",
          "source": "Unknown",
          "address": "fe80:0:0:0:5ef3:fcff:fe6f:bcc",
          "prefix": 64,
          "type": "UNKNOWN"
        }
      ],
      "name": "eth0",
      "IPv6statelessEnabled": true,
      "label": "unknown",
      "IPv6staticEnabled": true
    }
  ],
  "firmware": [
    {
      "status": "Inactive",
      "name": "UEFI Firmware/BIOS",
      "role": "Backup",
      "date": "",
      "type": "UEFI",
      "build": "0000000",
      "version": "0.00"
    },
    {
      "status": "Inactive",
      "name": "UEFI Backup Firmware/BIOS",
      "role": "Backup",
      "date": "",
      "type": "UEFI-Backup",
      "build": "0000000",
      "version": "0.00"
    },
    {
      "status": "Active",
      "name": "DSA Diagnostic Software",
      "role": "Primary",
      "date": "",
      "type": "DSA",
      "build": "*",
      "version": "65535.65535"
    },
    {
      "status": "Active",
      "name": "IMM2 Firmware",
      "role": "Primary",
      "date": "2013-10-08T00:00:00Z",
      "type": "IMM2",
      "build": "1AOO43S",
      "version": "2.65"
    },
    {
      "status": "Inactive",
      "name": "IMM2 Backup Firmware",
      "role": "Backup",
      "date": "2013-07-29T00:00:00Z",
      "type": "IMM2-Backup",
      "build": "1AOO41X",
      "version": "2.60"
    }
  ],
  "bladeState": 1,
  "machineType": "4939",
  "activationKeys": [],
  "parent": {
    "uuid": "B8106786386411E19AE3EF8BCD385476",
    "uri": "node/B8106786386411E19AE3EF8BCD385476"
  },
  "hostname": "IMM2-5cf3fc6f0bcc",
  "domainName": "",
  "FRU": "90Y7691",
  "processors": [],
  "uri": "canister/457784225BA511E18290B4F27BD253A5",
  "processorSlots": 1,
  "vnicMode": "disabled",
  "productId": "374",
  "ipv6ServiceAddress": "",
  "powerStatus": 8,
  "ipv6Addresses": [
    "fd6d:8bc2:3ad4:0:5ef3:fcff:fe6f:bcc",
    "fd55:faaf:e1ab:20fc:5ef3:fcff:fe6f:bcc",
    "fe80:0:0:0:5ef3:fcff:fe6f:bcc"
  ],
  "posID": "384",
  "slots": [
    5
  ],
  "subType": "SRC",
  "manufacturer": "IBM",
  "serviceHostName": "",
  "vpdID": "3",
  "uuid": "457784225BA511E18290B4F27BD253A5",
  "productName": "PRODUCT DESCRIPTION STORAGE ITE PRODUCT DESCRIPTION STORAGE ITE PRODUCT DESCRIPTION STORAGE ITE",
  "memoryModules": [],
  "fruSerialNumber": "YM11BG22D03F"
}
+ Response 400
+ Response 401
+ Response 404
+ Response 409
+ Response 500
