FORMAT: 1A

# Cmms

# GET /cmms

+ Response 200 (application/json)
  {
  "cmmsList": [{
    "accessState": "Online",
    "activationKeys": [],
    "activeAlerts": [{
      "corrIDs": "",
      "id": "LENOVO:CMM01:Y034BG17606E:01:15649",
      "location": "01010201",
      "msg": "The CMM J40 jumper is installed in bay 1.",
      "msgID": "CMM0488",
      "severity": "WARNING"
    }, {
      "corrIDs": "",
      "id": "LENOVO:CMM01:Y034BG17606E:01:15657",
      "location": "01010402",
      "msg": "Power supply Power Supply 02 is off. Input fault.",
      "msgID": "CMM0043",
      "severity": "WARNING"
    }, {
      "corrIDs": "",
      "id": "LENOVO:CMM01:Y034BG17606E:01:15679",
      "location": "010103085901",
      "msg": "Node Node 08 device Storage back plane[01] VPD is not valid.",
      "msgID": "CMM0835",
      "severity": "WARNING"
    }],
    "backedBy": "real",
    "bladeSlots": 14,
    "cmmDisplayName": "SN#Y034BG17606E",
    "cmmHealthState": "Non-Critical",
    "contact": "No Contact Configured",
    "dataHandle": 1427332847174,
    "description": "Lenovo Flex System Cmms",
    "encapsulation": {
      "encapsulationMode": "normal"
    },
    "energyPolicies": {
      "acousticAttenuationMode": "Off",
      "hotAirRecirculation": {
        "cmmsBay": [{
          "isExceeded": "N",
          "sensorName": "Cmms Ambient",
          "sensorValue": 26.5,
          "slot": 0,
          "subSlot": -1
        }, {
          "isExceeded": "Y",
          "sensorName": "Inlet 2 Temp",
          "sensorValue": -1.0,
          "slot": 1,
          "subSlot": -1
        }],
        "isEnabled": true,
        "maxVariation": 5.0
      },
      "powerCappingPolicy": {
        "cappingPolicy": "OFF",
        "maxPowerCap": 7515,
        "currentPowerCap": 0,
        "minPowerCap": 2048
      },
      "powerRedundancyMode": 4
    },
    "errorFields": [],
    "fanMuxSlots": 2,
    "fanSlots": 10,
    "height": 10,
    "hostname": "MM5CF3FC25DF43",
    "isConnectionTrusted": "true",
    "leds": [{
      "color": "Blue",
      "location": "FrontPanel",
      "name": "Location",
      "state": "Off"
    }, {
      "color": "Amber",
      "location": "FrontPanel",
      "name": "FAULT",
      "state": "Off"
    }, {
      "color": "Amber",
      "location": "FrontPanel",
      "name": "Information",
      "state": "On"
    }],
    "location": {
      "lowestRackUnit": 0,
      "location": "No Location Configured",
      "rack": "",
      "room": ""
    },
    "manufacturer": "20301",
    "manufacturerId": "20301",
    "mgmtProcIPaddress": "fd55:faaf:e1ab:2021:5ef3:fcff:fe25:df43",
    "model": "HC1",
    "powerAllocation": {
      "midPlaneCardMaximumAllocatedPower": 38,
      "midPlaneCardMinimumAllocatedPower": 38,
      "remainingOutputPower": 5467,
      "totalInputPower": 10891,
      "totalOutputPower": 7515,
      "allocatedOutputPower": 2048
    },
    "powerSupplySlots": 6,
    "serialNumber": "23FBX24",
    "status": {
      "message": "MANAGED",
      "name": "MANAGED"
    },
    "switchSlots": 4,
    "tlsVersion": {
      "possibleValues": ["SSL_30",
        "TLS_12_Server_Client",
        "TLS_12_Server"
      ],
      "currentValue": "SSL_30"
    },
    "type": "Cmms",
    "uri": "cmms/ED895B48D50D4E34B5DAF1F697B1FAC5",
    "uuid": "ED895B48D50D4E34B5DAF1F697B1FAC5",
    "vpdID": "14",
    "name": "SN#Y034BG17606E",
    "ledCardSlots": 1,
    "SecurityPolicy": {
      "cmmPolicyLevel": "SECURE",
      "cmmPolicyState": "ACTIVE"
    },
    "userDescription": "",
    "partNumber": "88Y6660",
    "excludedHealthState": "Critical",
    "machineType": "8721",
    "mmSlots": 2,
    "managerName": "UNKNOWN",
    "domainName": "",
    "managerUuid": "UNKNOWN",
    "productId": "336",
    "nist": {
      "possibleValues": ["Compatibility",
        "Nist_800_131A_Strict",
        "Nist_800_131A_Custom"
      ],
      "currentValue": "Compatibility"
    },
    "posID": "336",
    "overallHealthState": "Critical",
    "complex": [{
      "partition": [{
        "nodes": [{
          "accessState": "Partial",
          "manufacturerId": "20301",
          "arch": "x86",
          "addinCardSlots": 0,
          "location": {
            "lowestRackUnit": 0,
            "location": "",
            "rack": "",
            "room": ""
          },
          "serialNumber": "23YWAP6",
          "driveBays": 8,
          "macAddress": "6C:AE:8B:6F:0D:39,6C:AE:8B:6F:0D:38",
          "lanOverUsb": "disabled",
          "type": "ITE",
          "onboardPciDevices": [],
          "leds": [{
            "location": "Unknown",
            "color": "Unknown",
            "name": "",
            "state": "Off"
          }, {
            "location": "Planar",
            "color": "Yellow",
            "name": "DC Fault",
            "state": "Off"
          }, {
            "location": "Planar",
            "color": "Yellow",
            "name": "SAS BP 1 Error",
            "state": "Off"
          }, {
            "location": "Planar",
            "color": "Yellow",
            "name": "SAS BP 2 Error",
            "state": "Off"
          }, {
            "location": "Planar",
            "color": "Yellow",
            "name": "CMOS Batt Errror",
            "state": "Off"
          }],
          "description": "Flex System x880 X6 + 10G",
          "errorFields": [{
            "HostAndDomain": "NO_CONNECTOR"
          }, {
            "PhysicalAndLocation": "NO_CONNECTOR"
          }, {
            "Memory": "NO_CONNECTOR"
          }, {
            "ServerOnboardPciDevices": "NO_CONNECTOR"
          }, {
            "BootMode": "NO_CONNECTOR"
          }, {
            "Memory": "NO_CONNECTOR"
          }, {
            "BootOrder": "NO_CONNECTOR"
          }, {
            "FlashDimm": "NO_CONNECTOR"
          }, {
            "HostMacAddress": "NO_CONNECTOR"
          }, {
            "VnicMode": "NO_CONNECTOR"
          }, {
            "RemotePresenceEnabled": "NO_CONNECTOR"
          }, {
            "ActivationKey": "NO_CONNECTOR"
          }, {
            "LanOverUsbMode": "FETCH_FAILED"
          }, {
            "ServerMetrics": "NO_CONNECTOR"
          }, {
            "ScalableComplexPartitionUUIDData": "NO_CONNECTOR"
          }],
          "expansionCards": [],
          "mgmtProcIPaddress": "fd55:faaf:e1ab:2021:6eae:8bff:fe6f:d39",
          "ipInterfaces": [{
            "IPv4enabled": true,
            "IPv4DHCPmode": "DHCP_THEN_STATIC",
            "IPv6enabled": true,
            "IPv6assignments": [{
              "id": 16,
              "scope": "Global",
              "source": "Stateless",
              "gateway": "0:0:0:0:0:0:0:0",
              "address": "fd55:faaf:e1ab:2021:6eae:8bff:fe6f:d39",
              "prefix": 64,
              "type": "INUSE"
            }, {
              "id": 1,
              "scope": "LinkLocal",
              "source": "Other",
              "gateway": "fe80:0:0:0:202:ff:fe02:2",
              "address": "fe80:0:0:0:6eae:8bff:fe6f:d39",
              "prefix": 64,
              "type": "INUSE"
            }, {
              "id": 3,
              "scope": "Global",
              "source": "Static",
              "gateway": "0:0:0:0:0:0:0:0",
              "address": "0:0:0:0:0:0:0:0",
              "prefix": 64,
              "type": "CONFIGURED"
            }],
            "IPv4assignments": [{
              "id": 2,
              "subnet": "255.255.248.0",
              "gateway": "10.240.80.1",
              "address": "10.240.81.176",
              "type": "CONFIGURED"
            }, {
              "id": 64,
              "subnet": "255.255.240.0",
              "gateway": "10.243.0.1",
              "address": "10.243.12.118",
              "type": "INUSE"
            }],
            "IPv6DHCPenabled": true,
            "name": "eth1",
            "IPv6statelessEnabled": false,
            "label": "eth1",
            "IPv6staticEnabled": false
          }],
          "firmware": [{
            "status": "Active",
            "name": "MP",
            "role": "Primary",
            "build": "1AOO89M",
            "type": "MP",
            "date": "2014-09-08T04:00:00Z",
            "version": "9.00"
          }, {
            "status": "Not Active",
            "name": "MP",
            "role": "Backup",
            "build": "1AOO89M",
            "type": "MP",
            "date": "2014-09-08T04:00:00Z",
            "version": "9.00"
          }, {
            "status": "Active",
            "name": "UEFI",
            "role": "Primary",
            "build": "N2E111AUS",
            "type": "UEFI",
            "date": "2014-07-31T04:00:00Z",
            "version": "1.00"
          }, {
            "status": "Not Active",
            "name": "UEFI",
            "role": "Backup",
            "build": "N2E111AUS",
            "type": "UEFI",
            "date": "2014-07-31T04:00:00Z",
            "version": "1.00"
          }, {
            "status": "Active",
            "name": "DSA",
            "role": "Primary",
            "build": "DSYTD1H",
            "type": "DSA",
            "date": "2013-10-14T04:00:00Z",
            "version": "9.50"
          }],
          "bladeState": 1,
          "activationKeys": [],
          "status": {
            "message": "managed",
            "name": "MANAGED"
          },
          "bladeState_health": "GOOD",
          "hostname": "",
          "parent": {
            "uuid": "ED895B48D50D4E34B5DAF1F697B1FAC5",
            "uri": "cmms/ED895B48D50D4E34B5DAF1F697B1FAC5"
          },
          "powerSupplies": [],
          "parentComplexID": "88DA",
          "FRU": "47C2239",
          "uri": "node/DA5036596FE011E3A5736CAE8B7034F0",
          "vnicMode": "disabled",
          "powerAllocation": {
            "maximumAllocatedPower": 140,
            "minimumAllocatedPower": 254
          },
          "bootOrder": {
            "bootOrderList": [],
            "uri": "node/DA5036596FE011E3A5736CAE8B7034F0/bootOrder"
          },
          "powerStatus": 5,
          "expansionProductType": "",
          "expansionProducts": [],
          "ipv6Addresses": ["fd55:faaf:e1ab:2021:6eae:8bff:fe6f:d39",
            "fe80:0:0:0:6eae:8bff:fe6f:d39"
          ],
          "manufacturer": "Lenovo",
          "slots": [3,
            4
          ],
          "addinCards": [],
          "vpdID": "30",
          "raidSettings": [],
          "parentPartitionUUID": "",
          "isConnectionTrusted": "false",
          "uuid": "DA5036596FE011E3A5736CAE8B7034F0",
          "memoryModules": [],
          "tlsVersion": {
            "possibleValues": ["TLS_10",
              "TLS_11",
              "TLS_12"
            ],
            "currentValue": "Unknown"
          },
          "secureBootMode": {
            "possibleValues": [],
            "currentValue": ""
          },
          "partitionEnabled": false,
          "fruSerialNumber": "YG31BG3B600L",
          "model": "AC1",
          "expansionCardSlots": 4,
          "isScalable": true,
          "hostMacAddresses": "",
          "isITME": false,
          "contact": "",
          "dataHandle": 1427332579349,
          "ipv4Addresses": ["10.243.12.118",
            "10.240.81.176"
          ],
          "backedBy": "real",
          "cmmDisplayName": "Node 03",
          "complexID": 35034,
          "name": "Newport-dev1",
          "memorySlots": 48,
          "drives": [],
          "cmmHealthState": "Normal",
          "userDescription": "",
          "subSlots": [],
          "partNumber": "00AN678",
          "excludedHealthState": "Critical",
          "bladeState_string": "Newport-dev1",
          "machineType": "7903",
          "isRemotePresenceEnabled": false,
          "pciDevices": [],
          "domainName": "",
          "processors": [],
          "processorSlots": 2,
          "pciCapabilities": [],
          "hasOS": false,
          "productId": "448",
          "bootMode": {
            "possibleValues": [],
            "currentValue": ""
          },
          "embeddedHypervisorPresence": false,
          "ports": [],
          "nist": {
            "possibleValues": ["Compatibility",
              "Nist_800_131A_Strict"
            ],
            "currentValue": "Unknown"
          },
          "posID": "256",
          "overallHealthState": "Critical",
          "subType": "Nantahala",
          "partitionID": 1,
          "flashStorage": [],
          "dnsHostnames": ["10.243.12.118",
            "10.240.81.176",
            "fd55:faaf:e1ab:2021:6eae:8bff:fe6f:d39"
          ],
          "productName": "Flex System x880 X6 Compute Node with embedded 10Gb Virtual Fabric"
        }],
        "slots": [3,
          4
        ],
        "partitionID": 1,
        "uuid": ""
      }],
      "orphanNodes": [],
      "slots": [3,
        4
      ],
      "complexID": "88DA",
      "partitionCount": 1,
      "uuid": "DA5036596FE011E3A5736CAE8B7034F0",
      "nodeCount": 1
    }, {
      "partition": [{
        "nodes": [{
          "accessState": "Partial",
          "manufacturerId": "20301",
          "arch": "x86",
          "addinCardSlots": 0,
          "location": {
            "lowestRackUnit": 0,
            "location": "",
            "rack": "",
            "room": ""
          },
          "serialNumber": "23YWAN5",
          "driveBays": 8,
          "macAddress": "6C:AE:8B:6F:0E:05,6C:AE:8B:6F:0E:04",
          "lanOverUsb": "disabled",
          "type": "ITE",
          "onboardPciDevices": [],
          "leds": [{
            "location": "Unknown",
            "color": "Unknown",
            "name": "",
            "state": "Off"
          }, {
            "location": "Planar",
            "color": "Yellow",
            "name": "DC Fault",
            "state": "Off"
          }, {
            "location": "Planar",
            "color": "Yellow",
            "name": "SAS BP 1 Error",
            "state": "Off"
          }, {
            "location": "Planar",
            "color": "Yellow",
            "name": "SAS BP 2 Error",
            "state": "Off"
          }, {
            "location": "Planar",
            "color": "Yellow",
            "name": "CMOS Batt Errror",
            "state": "Off"
          }],
          "description": "Flex System x880 X6 + 10G",
          "errorFields": [{
            "HostAndDomain": "NO_CONNECTOR"
          }, {
            "PhysicalAndLocation": "NO_CONNECTOR"
          }, {
            "Memory": "NO_CONNECTOR"
          }, {
            "ServerOnboardPciDevices": "NO_CONNECTOR"
          }, {
            "BootMode": "NO_CONNECTOR"
          }, {
            "Memory": "NO_CONNECTOR"
          }, {
            "BootOrder": "NO_CONNECTOR"
          }, {
            "FlashDimm": "NO_CONNECTOR"
          }, {
            "HostMacAddress": "NO_CONNECTOR"
          }, {
            "VnicMode": "NO_CONNECTOR"
          }, {
            "RemotePresenceEnabled": "NO_CONNECTOR"
          }, {
            "ActivationKey": "NO_CONNECTOR"
          }, {
            "LanOverUsbMode": "FETCH_FAILED"
          }, {
            "ServerMetrics": "NO_CONNECTOR"
          }, {
            "ScalableComplexPartitionUUIDData": "NO_CONNECTOR"
          }],
          "expansionCards": [],
          "mgmtProcIPaddress": "fd55:faaf:e1ab:2021:6eae:8bff:fe6f:e05",
          "ipInterfaces": [{
            "IPv4enabled": true,
            "IPv4DHCPmode": "DHCP_ONLY",
            "IPv6enabled": true,
            "IPv6assignments": [{
              "id": 16,
              "scope": "Global",
              "source": "Stateless",
              "gateway": "0:0:0:0:0:0:0:0",
              "address": "fd55:faaf:e1ab:2021:6eae:8bff:fe6f:e05",
              "prefix": 64,
              "type": "INUSE"
            }, {
              "id": 1,
              "scope": "LinkLocal",
              "source": "Other",
              "gateway": "fe80:0:0:0:202:ff:fe02:2",
              "address": "fe80:0:0:0:6eae:8bff:fe6f:e05",
              "prefix": 64,
              "type": "INUSE"
            }, {
              "id": 3,
              "scope": "Global",
              "source": "Static",
              "gateway": "0:0:0:0:0:0:0:0",
              "address": "0:0:0:0:0:0:0:0",
              "prefix": 64,
              "type": "CONFIGURED"
            }],
            "IPv4assignments": [{
              "id": 2,
              "subnet": "255.255.248.0",
              "gateway": "10.240.80.1",
              "address": "10.240.86.235",
              "type": "CONFIGURED"
            }, {
              "id": 64,
              "subnet": "255.255.240.0",
              "gateway": "10.243.0.1",
              "address": "10.243.15.207",
              "type": "INUSE"
            }],
            "IPv6DHCPenabled": true,
            "name": "eth1",
            "IPv6statelessEnabled": false,
            "label": "eth1",
            "IPv6staticEnabled": false
          }],
          "firmware": [{
            "status": "Active",
            "name": "MP",
            "role": "Primary",
            "build": "1AOO89M",
            "type": "MP",
            "date": "2014-09-08T04:00:00Z",
            "version": "9.00"
          }, {
            "status": "Not Active",
            "name": "MP",
            "role": "Backup",
            "build": "1AOO89M",
            "type": "MP",
            "date": "2014-09-08T04:00:00Z",
            "version": "9.00"
          }, {
            "status": "Active",
            "name": "UEFI",
            "role": "Primary",
            "build": "N2E111AUS",
            "type": "UEFI",
            "date": "2014-07-31T04:00:00Z",
            "version": "1.00"
          }, {
            "status": "Not Active",
            "name": "UEFI",
            "role": "Backup",
            "build": "N2E111AUS",
            "type": "UEFI",
            "date": "2014-07-31T04:00:00Z",
            "version": "1.00"
          }, {
            "status": "Active",
            "name": "DSA",
            "role": "Primary",
            "build": "DSYTD1H",
            "type": "DSA",
            "date": "2013-10-14T04:00:00Z",
            "version": "9.50"
          }],
          "bladeState": 1,
          "activationKeys": [],
          "status": {
            "message": "managed",
            "name": "MANAGED"
          },
          "bladeState_health": "GOOD",
          "hostname": "",
          "parent": {
            "uuid": "ED895B48D50D4E34B5DAF1F697B1FAC5",
            "uri": "cmms/ED895B48D50D4E34B5DAF1F697B1FAC5"
          },
          "powerSupplies": [],
          "parentComplexID": "0640",
          "FRU": "47C2239",
          "uri": "node/BDB64B266F3911E391406CAE8B703820",
          "vnicMode": "disabled",
          "powerAllocation": {
            "maximumAllocatedPower": 330,
            "minimumAllocatedPower": 233
          },
          "bootOrder": {
            "bootOrderList": [],
            "uri": "node/BDB64B266F3911E391406CAE8B703820/bootOrder"
          },
          "powerStatus": 5,
          "expansionProductType": "",
          "expansionProducts": [],
          "ipv6Addresses": ["fd55:faaf:e1ab:2021:6eae:8bff:fe6f:e05",
            "fe80:0:0:0:6eae:8bff:fe6f:e05"
          ],
          "manufacturer": "Lenovo",
          "slots": [1,
            2
          ],
          "addinCards": [],
          "vpdID": "30",
          "raidSettings": [],
          "parentPartitionUUID": "",
          "isConnectionTrusted": "false",
          "uuid": "BDB64B266F3911E391406CAE8B703820",
          "memoryModules": [],
          "tlsVersion": {
            "possibleValues": ["TLS_10",
              "TLS_11",
              "TLS_12"
            ],
            "currentValue": "Unknown"
          },
          "secureBootMode": {
            "possibleValues": [],
            "currentValue": ""
          },
          "partitionEnabled": false,
          "fruSerialNumber": "YG31BG3B6027",
          "model": "AC1",
          "expansionCardSlots": 4,
          "isScalable": true,
          "hostMacAddresses": "",
          "isITME": false,
          "contact": "",
          "dataHandle": 1427332579243,
          "ipv4Addresses": ["10.243.15.207",
            "10.240.86.235"
          ],
          "backedBy": "real",
          "cmmDisplayName": "Node 01",
          "complexID": 1600,
          "name": "Newport-dev2",
          "memorySlots": 48,
          "drives": [],
          "cmmHealthState": "Normal",
          "userDescription": "",
          "subSlots": [],
          "partNumber": "00AN678",
          "excludedHealthState": "Critical",
          "bladeState_string": "Newport-dev2",
          "machineType": "7903",
          "isRemotePresenceEnabled": false,
          "pciDevices": [],
          "domainName": "",
          "processors": [],
          "processorSlots": 2,
          "pciCapabilities": [],
          "hasOS": false,
          "productId": "448",
          "bootMode": {
            "possibleValues": [],
            "currentValue": ""
          },
          "embeddedHypervisorPresence": false,
          "ports": [],
          "nist": {
            "possibleValues": ["Compatibility",
              "Nist_800_131A_Strict"
            ],
            "currentValue": "Unknown"
          },
          "posID": "256",
          "overallHealthState": "Critical",
          "subType": "Nantahala",
          "partitionID": 1,
          "flashStorage": [],
          "dnsHostnames": ["10.243.15.207",
            "10.240.86.235",
            "fd55:faaf:e1ab:2021:6eae:8bff:fe6f:e05"
          ],
          "productName": "Flex System x880 X6 Compute Node with embedded 10Gb Virtual Fabric"
        }],
        "slots": [1,
          2
        ],
        "partitionID": 1,
        "uuid": "BDB64B266F3911E391406CAE8B703820"
      }],
      "orphanNodes": [],
      "slots": [1,
        2
      ],
      "complexID": "0640",
      "partitionCount": 1,
      "uuid": "BDB64B266F3911E391406CAE8B703820",
      "nodeCount": 1
    }],
    "powerSupplies": [],
    "parentComplexID": "0640",
    "FRU": "47C2239",
    "uri": "node/BDB64B266F3911E391406CAE8B703820",
    "vnicMode": "disabled",
    "powerAllocation": {
      "maximumAllocatedPower": 330,
      "minimumAllocatedPower": 233
    },
    "bootOrder": {
      "bootOrderList": [],
      "uri": "node/BDB64B266F3911E391406CAE8B703820/bootOrder"
    },
    "powerStatus": 5,
    "expansionProductType": "",
    "expansionProducts": [],
    "ipv6Addresses": ["fd55:faaf:e1ab:2021:6eae:8bff:fe6f:e05",
      "fe80:0:0:0:6eae:8bff:fe6f:e05"
    ],
    "manufacturer": "Lenovo",
    "slots": [1,
      2
    ],
    "addinCards": [],
    "vpdID": "30",
    "raidSettings": [],
    "parentPartitionUUID": "",
    "isConnectionTrusted": "false",
    "uuid": "BDB64B266F3911E391406CAE8B703820",
    "memoryModules": [],
    "tlsVersion": {
      "possibleValues": ["TLS_10",
        "TLS_11",
        "TLS_12"
      ],
      "currentValue": "Unknown"
    },
    "secureBootMode": {
      "possibleValues": [],
      "currentValue": ""
    },
    "partitionEnabled": false,
    "fruSerialNumber": "YG31BG3B6027",
    "model": "AC1",
    "expansionCardSlots": 4,
    "isScalable": true,
    "hostMacAddresses": "",
    "isITME": false,
    "contact": "",
    "dataHandle": 1427332579243,
    "ipv4Addresses": ["10.243.15.207",
      "10.240.86.235"
    ],
    "backedBy": "real",
    "cmmDisplayName": "Node 01",
    "complexID": 1600,
    "name": "Newport-dev2",
    "memorySlots": 48,
    "drives": [],
    "cmmHealthState": "Normal",
    "userDescription": "",
    "subSlots": [],
    "partNumber": "00AN678",
    "excludedHealthState": "Critical",
    "bladeState_string": "Newport-dev2",
    "machineType": "7903",
    "isRemotePresenceEnabled": false,
    "pciDevices": [],
    "domainName": "",
    "processors": [],
    "processorSlots": 2,
    "pciCapabilities": [],
    "hasOS": false,
    "productId": "448",
    "bootMode": {
      "possibleValues": [],
      "currentValue": ""
    },
    "embeddedHypervisorPresence": false,
    "ports": [],
    "nist": {
      "possibleValues": ["Compatibility",
        "Nist_800_131A_Strict"
      ],
      "currentValue": "Unknown"
    },
    "posID": "256",
    "overallHealthState": "Critical",
    "subType": "Nantahala",
    "partitionID": 1,
    "flashStorage": [],
    "dnsHostnames": ["10.243.15.207",
      "10.240.86.235",
      "fd55:faaf:e1ab:2021:6eae:8bff:fe6f:e05"
    ],
    "productName": "Flex System x880 X6 Compute Node with embedded 10Gb Virtual Fabric",
    "powerSupplies": [{
      "model": "",
      "manufacturerId": "20301",
      "inputVoltageIsAC": true,
      "serialNumber": "",
      "type": "PowerSupply",
      "inputVoltageMin": 200,
      "dataHandle": 0,
      "cmmDisplayName": "Power Supply 01",
      "leds": [{
        "location": "FRU",
        "color": "Green",
        "name": "IN",
        "state": "On"
      }, {
        "location": "FRU",
        "color": "Green",
        "name": "OUT",
        "state": "On"
      }, {
        "location": "FRU",
        "color": "Amber",
        "name": "FAULT",
        "state": "Off"
      }],
      "description": "Power Supply",
      "name": "Power Supply 01",
      "cmmHealthState": "Normal",
      "manufactureDate": "2511",
      "userDescription": "",
      "partNumber": "69Y5802",
      "firmware": [{
        "status": "",
        "name": "Power Supply Firmware",
        "role": "",
        "build": "",
        "type": "Power Supply Firmware",
        "date": "",
        "version": "5"
      }],
      "machineType": "",
      "hardwareRevision": "75.54",
      "parent": {
        "uuid": "ED895B48D50D4E34B5DAF1F697B1FAC5",
        "uri": "cmms/ED895B48D50D4E34B5DAF1F697B1FAC5"
      },
      "FRU": "69Y5806",
      "uri": "powerSupply/E9D20C4DA58F4942896E976134AD0962",
      "productId": "304",
      "powerAllocation": {
        "totalInputPower": 2505,
        "totalOutputPower": 338
      },
      "posID": "128",
      "powerState": "Unknown",
      "manufacturer": "Lenovo",
      "slots": [1],
      "vpdID": "61",
      "uuid": "E9D20C4DA58F4942896E976134AD0962",
      "productName": "2500 W Power Supply",
      "fruSerialNumber": "ZK128116T06A",
      "inputVoltageMax": 208
    }, {
      "model": "",
      "manufacturerId": "20301",
      "inputVoltageIsAC": true,
      "serialNumber": "",
      "type": "PowerSupply",
      "inputVoltageMin": -1,
      "dataHandle": 0,
      "cmmDisplayName": "Power Supply 06",
      "leds": [{
        "location": "FRU",
        "color": "Green",
        "name": "IN",
        "state": "Off"
      }, {
        "location": "FRU",
        "color": "Green",
        "name": "OUT",
        "state": "Off"
      }, {
        "location": "FRU",
        "color": "Amber",
        "name": "FAULT",
        "state": "Off"
      }],
      "description": "Power Supply",
      "name": "Power Supply 06",
      "cmmHealthState": "Non-Critical",
      "manufactureDate": "2911",
      "userDescription": "",
      "partNumber": "69Y5801",
      "firmware": [{
        "status": "",
        "name": "Power Supply Firmware",
        "role": "",
        "build": "",
        "type": "Power Supply Firmware",
        "date": "",
        "version": "0"
      }],
      "machineType": "",
      "hardwareRevision": "6.0",
      "parent": {
        "uuid": "ED895B48D50D4E34B5DAF1F697B1FAC5",
        "uri": "cmms/ED895B48D50D4E34B5DAF1F697B1FAC5"
      },
      "FRU": "69Y5817",
      "uri": "powerSupply/A2D7550BB07D11E0009E009E009E009E",
      "productId": "303",
      "powerAllocation": {
        "totalInputPower": 0,
        "totalOutputPower": 338
      },
      "posID": "128",
      "powerState": "Unknown",
      "manufacturer": "Lenovo",
      "slots": [6],
      "vpdID": "60",
      "uuid": "A2D7550BB07D11E0009E009E009E009E",
      "productName": "2500 W Power Supply",
      "fruSerialNumber": "ZK135117N00Y",
      "inputVoltageMax": -1
    }],
    "fans": [{
      "model": "",
      "manufacturerId": "20301",
      "serialNumber": "",
      "type": "Fan",
      "dataHandle": 0,
      "cmmDisplayName": "Fan 01",
      "leds": [{
        "location": "FrontPanel",
        "color": "Amber",
        "name": "FAULT",
        "state": "Off"
      }],
      "description": "Fan Module",
      "errorFields": [],
      "name": "Fan 01",
      "cmmHealthState": "Normal",
      "manufactureDate": "2911",
      "userDescription": "",
      "partNumber": "88Y6671",
      "firmware": [{
        "status": "",
        "name": "Fan Controller",
        "role": "",
        "build": "",
        "type": "Fan Controller",
        "date": "",
        "version": "226"
      }],
      "machineType": "",
      "hardwareRevision": "4.0",
      "parent": {
        "uuid": "ED895B48D50D4E34B5DAF1F697B1FAC5",
        "uri": "cmms/ED895B48D50D4E34B5DAF1F697B1FAC5"
      },
      "FRU": "81Y2910",
      "uri": "fan/5B47AE2A24EB42BFB698204C8DDEE798",
      "productId": "341",
      "powerAllocation": {
        "maximumAllocatedPower": 75,
        "minimumAllocatedPower": 75
      },
      "posID": "373",
      "powerState": "Unknown",
      "manufacturer": "Lenovo",
      "slots": [1],
      "vpdID": "10",
      "uuid": "5B47AE2A24EB42BFB698204C8DDEE798",
      "productName": "",
      "fruSerialNumber": "YK10GM17D057"
    }, {
      "model": "",
      "manufacturerId": "20301",
      "serialNumber": "",
      "type": "Fan",
      "dataHandle": 0,
      "cmmDisplayName": "Fan 10",
      "leds": [{
        "location": "FrontPanel",
        "color": "Amber",
        "name": "FAULT",
        "state": "Off"
      }],
      "description": "Fan Module",
      "errorFields": [],
      "name": "Fan 10",
      "cmmHealthState": "Normal",
      "manufactureDate": "3011",
      "userDescription": "",
      "partNumber": "88Y6670",
      "firmware": [{
        "status": "",
        "name": "Fan Controller",
        "role": "",
        "build": "",
        "type": "Fan Controller",
        "date": "",
        "version": "226"
      }],
      "machineType": "",
      "hardwareRevision": "4.0",
      "parent": {
        "uuid": "ED895B48D50D4E34B5DAF1F697B1FAC5",
        "uri": "cmms/ED895B48D50D4E34B5DAF1F697B1FAC5"
      },
      "FRU": "81Y2911",
      "uri": "fan/06449592A0F2459686DFFFBCA04FDF9F",
      "productId": "339",
      "powerAllocation": {
        "maximumAllocatedPower": 60,
        "minimumAllocatedPower": 60
      },
      "posID": "373",
      "powerState": "Unknown",
      "manufacturer": "Lenovo",
      "slots": [10],
      "vpdID": "8",
      "uuid": "06449592A0F2459686DFFFBCA04FDF9F",
      "productName": "",
      "fruSerialNumber": "YK10GM17L019"
    }],
    "fanMuxes": [{
      "model": "",
      "machineType": "",
      "manufacturerId": "20301",
      "status": "Non-Critical",
      "hardwareRevision": "4.0",
      "parent": {
        "uuid": "ED895B48D50D4E34B5DAF1F697B1FAC5",
        "uri": "cmms/ED895B48D50D4E34B5DAF1F697B1FAC5"
      },
      "serialNumber": "",
      "FRU": "81Y2912",
      "type": "FanMux",
      "uri": "fanMux/5BB0129A985711E09F9BE2A4EAFEE097",
      "dataHandle": 0,
      "productId": "338",
      "cmmDisplayName": "Fan Logic 01",
      "leds": [{
        "location": "FrontPanel",
        "color": "Amber",
        "name": "FAULT",
        "state": "On"
      }],
      "description": "Fan Logic Module",
      "slots": [1],
      "manufacturer": "Lenovo",
      "name": "Fan Logic 01",
      "cmmHealthState": "Non-Critical",
      "uuid": "5BB0129A985711E09F9BE2A4EAFEE097",
      "manufactureDate": "2511",
      "productName": "Fan Pack Multiplexor Card",
      "partNumber": "81Y2990",
      "fruSerialNumber": "Y031BG16D09S"
    }, {
      "model": "",
      "machineType": "",
      "manufacturerId": "20301",
      "status": "Non-Critical",
      "hardwareRevision": "4.0",
      "parent": {
        "uuid": "ED895B48D50D4E34B5DAF1F697B1FAC5",
        "uri": "cmms/ED895B48D50D4E34B5DAF1F697B1FAC5"
      },
      "serialNumber": "",
      "FRU": "81Y2912",
      "type": "FanMux",
      "uri": "fanMux/BFBA72BA988211E0A90B93081C30C3B8",
      "dataHandle": 0,
      "productId": "338",
      "cmmDisplayName": "Fan Logic 02",
      "leds": [{
        "location": "FrontPanel",
        "color": "Amber",
        "name": "FAULT",
        "state": "On"
      }],
      "description": "Fan Logic Module",
      "slots": [2],
      "manufacturer": "Lenovo",
      "name": "Fan Logic 02",
      "cmmHealthState": "Non-Critical",
      "uuid": "BFBA72BA988211E0A90B93081C30C3B8",
      "manufactureDate": "2511",
      "productName": "Fan Pack Multiplexor Card",
      "partNumber": "81Y2990",
      "fruSerialNumber": "Y031BG16D085"
    }],
    "switches": [],
    "passThroughModules": [],
    "cmms": [{
      "model": "",
      "accessState": "Online",
      "serialNumber": "",
      "type": "CMM",
      "dataHandle": 1427332097660,
      "ipv4Addresses": ["10.243.4.147"],
      "cmmDisplayName": "SN#Y034BG17606E",
      "backedBy": "real",
      "hostConfig": [{
        "DDNSenabled": false,
        "IPversionPriority": "IPv6ThenIPv4",
        "DNSenabled": false,
        "terIPv6userDNSserver": "0:0:0:0:0:0:0:0",
        "secIPv4userDNSserver": "0.0.0.0",
        "terIPv4userDNSserver": "0.0.0.0",
        "secIPv6userDNSserver": "0:0:0:0:0:0:0:0",
        "priIPv6userDNSserver": "0:0:0:0:0:0:0:0",
        "priIPv4userDNSserver": "0.0.0.0"
      }],
      "leds": [{
        "location": "FrontPanel",
        "color": "Blue",
        "name": "Location",
        "state": "Off"
      }, {
        "location": "FrontPanel",
        "color": "Amber",
        "name": "FAULT",
        "state": "Off"
      }, {
        "location": "FrontPanel",
        "color": "Amber",
        "name": "Information",
        "state": "On"
      }],
      "description": "CMM",
      "errorFields": [],
      "mgmtProcIPaddress": "fd55:faaf:e1ab:2021:5ef3:fcff:fe25:df43",
      "name": "10.243.4.147",
      "role": "primary",
      "cmmHealthState": "Non-Critical",
      "userDescription": "",
      "partNumber": "68Y7029",
      "ipInterfaces": [{
        "IPv4enabled": true,
        "IPv4DHCPmode": "STATIC_ONLY",
        "IPv6enabled": true,
        "IPv6assignments": [{
          "id": 1,
          "scope": "LinkLocal",
          "source": "Other",
          "gateway": "0:0:0:0:0:0:0:0",
          "address": "fe80:0:0:0:5ef3:fcff:fe25:df43",
          "prefix": 64,
          "type": "INUSE"
        }, {
          "id": 2,
          "scope": "Global",
          "source": "Static",
          "gateway": "0:0:0:0:0:0:0:0",
          "address": "0:0:0:0:0:0:0:0",
          "prefix": 0,
          "type": "CONFIGURED"
        }, {
          "id": 16,
          "scope": "Global",
          "source": "Stateless",
          "gateway": "0:0:0:0:0:0:0:0",
          "address": "fd55:faaf:e1ab:2021:5ef3:fcff:fe25:df43",
          "prefix": 64,
          "type": "INUSE"
        }],
        "IPv4assignments": [{
          "id": 2,
          "subnet": "255.255.240.0",
          "gateway": "10.243.0.1",
          "address": "10.243.4.147",
          "type": "CONFIGURED"
        }, {
          "id": 2,
          "subnet": "255.255.240.0",
          "gateway": "10.243.0.1",
          "address": "10.243.4.147",
          "type": "INUSE"
        }],
        "IPv6DHCPenabled": true,
        "name": "eth0",
        "IPv6statelessEnabled": true,
        "label": "External",
        "IPv6staticEnabled": false
      }],
      "excludedHealthState": "Critical",
      "firmware": [{
        "status": "",
        "name": "CMM firmware",
        "role": "",
        "build": "1AON01N",
        "type": "CMM firmware",
        "date": "2015-03-09T04:00:00Z",
        "version": "1.0.0"
      }],
      "machineType": "",
      "hostname": "MM5CF3FC25DF43",
      "parent": {
        "uuid": "ED895B48D50D4E34B5DAF1F697B1FAC5",
        "uri": "cmms/ED895B48D50D4E34B5DAF1F697B1FAC5"
      },
      "domainName": "",
      "FRU": "68Y7032",
      "macAddresses": ["5C:F3:FC:25:DF:43"],
      "uri": "cmm/F37A6570B83611E09D0DD02C07D25365",
      "productId": "65",
      "powerAllocation": {
        "maximumAllocatedPower": 20,
        "minimumAllocatedPower": 20
      },
      "ipv6Addresses": ["fe80:0:0:0:5ef3:fcff:fe25:df43",
        "fd55:faaf:e1ab:2021:5ef3:fcff:fe25:df43"
      ],
      "overallHealthState": "Critical",
      "slots": [1],
      "uuid": "F37A6570B83611E09D0DD02C07D25365",
      "dnsHostnames": ["10.243.4.147",
        "fd55:faaf:e1ab:2021:5ef3:fcff:fe25:df43"
      ],
      "fruSerialNumber": "Y034BG17606E"
    }],
    "nodes": [{
      "accessState": "Partial",
      "manufacturerId": "20301",
      "arch": "x86",
      "addinCardSlots": 0,
      "location": {
        "lowestRackUnit": 0,
        "location": "",
        "rack": "",
        "room": ""
      },
      "serialNumber": "23YWAN5",
      "driveBays": 8,
      "macAddress": "6C:AE:8B:6F:0E:05,6C:AE:8B:6F:0E:04",
      "lanOverUsb": "disabled",
      "type": "ITE",
      "onboardPciDevices": [],
      "leds": [{
        "location": "Unknown",
        "color": "Unknown",
        "name": "",
        "state": "Off"
      }, {
        "location": "Planar",
        "color": "Yellow",
        "name": "DC Fault",
        "state": "Off"
      }, {
        "location": "Planar",
        "color": "Yellow",
        "name": "SAS BP 1 Error",
        "state": "Off"
      }, {
        "location": "Planar",
        "color": "Yellow",
        "name": "SAS BP 2 Error",
        "state": "Off"
      }, {
        "location": "Planar",
        "color": "Yellow",
        "name": "CMOS Batt Errror",
        "state": "Off"
      }],
      "description": "Flex System x880 X6 + 10G",
      "errorFields": [{
        "HostAndDomain": "NO_CONNECTOR"
      }, {
        "PhysicalAndLocation": "NO_CONNECTOR"
      }, {
        "Memory": "NO_CONNECTOR"
      }, {
        "ServerOnboardPciDevices": "NO_CONNECTOR"
      }, {
        "BootMode": "NO_CONNECTOR"
      }, {
        "Memory": "NO_CONNECTOR"
      }, {
        "BootOrder": "NO_CONNECTOR"
      }, {
        "FlashDimm": "NO_CONNECTOR"
      }, {
        "HostMacAddress": "NO_CONNECTOR"
      }, {
        "VnicMode": "NO_CONNECTOR"
      }, {
        "RemotePresenceEnabled": "NO_CONNECTOR"
      }, {
        "ActivationKey": "NO_CONNECTOR"
      }, {
        "LanOverUsbMode": "FETCH_FAILED"
      }, {
        "ServerMetrics": "NO_CONNECTOR"
      }, {
        "ScalableComplexPartitionUUIDData": "NO_CONNECTOR"
      }],
      "expansionCards": [],
      "mgmtProcIPaddress": "fd55:faaf:e1ab:2021:6eae:8bff:fe6f:e05",
      "ipInterfaces": [{
        "IPv4enabled": true,
        "IPv4DHCPmode": "DHCP_ONLY",
        "IPv6enabled": true,
        "IPv6assignments": [{
          "id": 16,
          "scope": "Global",
          "source": "Stateless",
          "gateway": "0:0:0:0:0:0:0:0",
          "address": "fd55:faaf:e1ab:2021:6eae:8bff:fe6f:e05",
          "prefix": 64,
          "type": "INUSE"
        }, {
          "id": 1,
          "scope": "LinkLocal",
          "source": "Other",
          "gateway": "fe80:0:0:0:202:ff:fe02:2",
          "address": "fe80:0:0:0:6eae:8bff:fe6f:e05",
          "prefix": 64,
          "type": "INUSE"
        }, {
          "id": 3,
          "scope": "Global",
          "source": "Static",
          "gateway": "0:0:0:0:0:0:0:0",
          "address": "0:0:0:0:0:0:0:0",
          "prefix": 64,
          "type": "CONFIGURED"
        }],
        "IPv4assignments": [{
          "id": 2,
          "subnet": "255.255.248.0",
          "gateway": "10.240.80.1",
          "address": "10.240.86.235",
          "type": "CONFIGURED"
        }, {
          "id": 64,
          "subnet": "255.255.240.0",
          "gateway": "10.243.0.1",
          "address": "10.243.15.207",
          "type": "INUSE"
        }],
        "IPv6DHCPenabled": true,
        "name": "eth1",
        "IPv6statelessEnabled": false,
        "label": "eth1",
        "IPv6staticEnabled": false
      }],
      "firmware": [{
        "status": "Active",
        "name": "MP",
        "role": "Primary",
        "build": "1AOO89M",
        "type": "MP",
        "date": "2014-09-08T04:00:00Z",
        "version": "9.00"
      }, {
        "status": "Not Active",
        "name": "MP",
        "role": "Backup",
        "build": "1AOO89M",
        "type": "MP",
        "date": "2014-09-08T04:00:00Z",
        "version": "9.00"
      }, {
        "status": "Active",
        "name": "UEFI",
        "role": "Primary",
        "build": "N2E111AUS",
        "type": "UEFI",
        "date": "2014-07-31T04:00:00Z",
        "version": "1.00"
      }, {
        "status": "Not Active",
        "name": "UEFI",
        "role": "Backup",
        "build": "N2E111AUS",
        "type": "UEFI",
        "date": "2014-07-31T04:00:00Z",
        "version": "1.00"
      }, {
        "status": "Active",
        "name": "DSA",
        "role": "Primary",
        "build": "DSYTD1H",
        "type": "DSA",
        "date": "2013-10-14T04:00:00Z",
        "version": "9.50"
      }],
      "bladeState": 1,
      "activationKeys": [],
      "status": {
        "message": "managed",
        "name": "MANAGED"
      },
      "bladeState_health": "GOOD",
      "hostname": "",
      "parent": {
        "uuid": "ED895B48D50D4E34B5DAF1F697B1FAC5",
        "uri": "cmms/ED895B48D50D4E34B5DAF1F697B1FAC5"
      }
    }]
  }]
  }
+ Response 400
+ Response 401
+ Response 404
+ Response 409
+ Response 500
