FORMAT: 1A

# Cmms

# GET /cmms/80C0B2F6B84011E0B504EC89B07DB965,256466549E0611E0A2F6872F34D5CCC9?excludeAttributes=accessState,backedBy

+ Response 200 (application/json)
{
   "cmmList":[
      {
         "model":"",
         "manufacturerId":"20301",
         "serialNumber":"",
         "type":"CMM",
         "dataHandle":1475517034173,
         "ipv4Addresses":[
            "10.240.72.61"
         ],
         "cmmDisplayName":"SN#Y034BG176046",
         "hostConfig":[
            {
               "DDNSenabled":false,
               "terIPv6userDNSserver":"0:0:0:0:0:0:0:0",
               "DNSenabled":false,
               "IPversionPriority":"IPv6ThenIPv4",
               "secIPv4userDNSserver":"10.240.0.11",
               "terIPv4userDNSserver":"0.0.0.0",
               "priIPv6userDNSserver":"0:0:0:0:0:0:0:0",
               "secIPv6userDNSserver":"0:0:0:0:0:0:0:0",
               "priIPv4userDNSserver":"10.240.0.10"
            }
         ],
         "leds":[
            {
               "color":"Amber",
               "location":"FrontPanel",
               "name":"FAULT",
               "state":"Off"
            }
         ],
         "description":"CMM",
         "name":"SN#Y034BG176046",
         "errorFields":[

         ],
         "mgmtProcIPaddress":"10.240.72.61",
         "role":"primary",
         "cmmHealthState":"Non-Critical",
         "userDescription":"",
         "partNumber":"68Y7029",
         "ipInterfaces":[
            {
               "IPv4enabled":true,
               "IPv4DHCPmode":"STATIC_ONLY",
               "IPv6enabled":true,
               "IPv6DHCPenabled":true,
               "IPv4assignments":[
                  {
                     "id":2,
                     "subnet":"255.255.252.0",
                     "gateway":"10.240.72.1",
                     "address":"10.240.72.61",
                     "type":"CONFIGURED"
                  },
                  {
                     "id":2,
                     "subnet":"255.255.252.0",
                     "gateway":"10.240.72.1",
                     "address":"10.240.72.61",
                     "type":"INUSE"
                  }
               ],
               "IPv6assignments":[
                  {
                     "id":1,
                     "scope":"LinkLocal",
                     "gateway":"0:0:0:0:0:0:0:0",
                     "source":"Other",
                     "address":"fe80:0:0:0:5ef3:fcff:fe25:deb3",
                     "prefix":64,
                     "type":"INUSE"
                  },
                  {
                     "id":2,
                     "scope":"Global",
                     "gateway":"0:0:0:0:0:0:0:0",
                     "source":"Static",
                     "address":"0:0:0:0:0:0:0:0",
                     "prefix":0,
                     "type":"CONFIGURED"
                  }
               ],
               "name":"eth0",
               "IPv6statelessEnabled":false,
               "label":"External",
               "IPv6staticEnabled":false
            }
         ],
         "excludedHealthState":"Warning",
         "firmware":[
            {
               "status":"",
               "name":"CMM firmware",
               "role":"",
               "date":"2016-07-29T04:00:00Z",
               "type":"CMM firmware",
               "build":"2PET33B",
               "version":"2.5.7"
            }
         ],
         "machineType":"",
         "parent":{
            "uuid":"7F3E7E375B5747E0938969896B1CFDF5",
            "uri":"chassis/7F3E7E375B5747E0938969896B1CFDF5"
         },
         "hostname":"MM5CF3FC25DEB3",
         "domainName":"labs.lenovo.com",
         "FRU":"68Y7032",
         "macAddresses":[
            "5C:F3:FC:25:DE:B3"
         ],
         "uri":"cmm/80C0B2F6B84011E0B504EC89B07DB965",
         "productId":"65",
         "powerAllocation":{
            "maximumAllocatedPower":20,
            "minimumAllocatedPower":20
         },
         "ipv6Addresses":[
            "fe80:0:0:0:5ef3:fcff:fe25:deb3"
         ],
         "overallHealthState":"Warning",
         "slots":[
            1
         ],
         "manufacturer":"IBM",
         "uuid":"80C0B2F6B84011E0B504EC89B07DB965",
         "dnsHostnames":[
            "Chassis119.labs.lenovo.com"
         ],
         "fruSerialNumber":"Y034BG176046"
      },
      {
         "model":"",
         "manufacturerId":"20301",
         "serialNumber":"",
         "type":"CMM",
         "dataHandle":1475517074784,
         "ipv4Addresses":[
            "10.243.1.141"
         ],
         "cmmDisplayName":"SN#Y034BG16E0C0",
         "hostConfig":[
            {
               "DDNSenabled":false,
               "terIPv6userDNSserver":"0:0:0:0:0:0:0:0",
               "DNSenabled":false,
               "IPversionPriority":"IPv6ThenIPv4",
               "secIPv4userDNSserver":"0.0.0.0",
               "terIPv4userDNSserver":"0.0.0.0",
               "priIPv6userDNSserver":"0:0:0:0:0:0:0:0",
               "secIPv6userDNSserver":"0:0:0:0:0:0:0:0",
               "priIPv4userDNSserver":"0.0.0.0"
            }
         ],
         "leds":[
            {
               "color":"Amber",
               "location":"FrontPanel",
               "name":"FAULT",
               "state":"Off"
            }
         ],
         "description":"CMM",
         "name":"SN#Y034BG16E0C0",
         "errorFields":[

         ],
         "mgmtProcIPaddress":"10.243.1.141",
         "role":"primary",
         "cmmHealthState":"Non-Critical",
         "userDescription":"",
         "partNumber":"68Y7029",
         "ipInterfaces":[
            {
               "IPv4enabled":true,
               "IPv4DHCPmode":"STATIC_ONLY",
               "IPv6enabled":true,
               "IPv6DHCPenabled":true,
               "IPv4assignments":[
                  {
                     "id":2,
                     "subnet":"255.255.240.0",
                     "gateway":"10.243.0.1",
                     "address":"10.243.1.141",
                     "type":"CONFIGURED"
                  },
                  {
                     "id":2,
                     "subnet":"255.255.240.0",
                     "gateway":"10.243.0.1",
                     "address":"10.243.1.141",
                     "type":"INUSE"
                  }
               ],
               "IPv6assignments":[
                  {
                     "id":1,
                     "scope":"LinkLocal",
                     "gateway":"0:0:0:0:0:0:0:0",
                     "source":"Other",
                     "address":"fe80:0:0:0:5ef3:fcff:fe25:db57",
                     "prefix":64,
                     "type":"INUSE"
                  },
                  {
                     "id":2,
                     "scope":"Global",
                     "gateway":"0:0:0:0:0:0:0:0",
                     "source":"Static",
                     "address":"0:0:0:0:0:0:0:0",
                     "prefix":0,
                     "type":"CONFIGURED"
                  },
                  {
                     "id":16,
                     "scope":"Global",
                     "gateway":"0:0:0:0:0:0:0:0",
                     "source":"Stateless",
                     "address":"fd55:faaf:e1ab:2021:5ef3:fcff:fe25:db57",
                     "prefix":64,
                     "type":"INUSE"
                  }
               ],
               "name":"eth0",
               "IPv6statelessEnabled":true,
               "label":"External",
               "IPv6staticEnabled":false
            }
         ],
         "excludedHealthState":"Warning",
         "firmware":[
            {
               "status":"",
               "name":"CMM firmware",
               "role":"",
               "date":"2016-07-29T04:00:00Z",
               "type":"CMM firmware",
               "build":"2PET33B",
               "version":"2.5.7"
            }
         ],
         "machineType":"",
         "parent":{
            "uuid":"3B058C775CE44FA6AC05608B196EDAB1",
            "uri":"chassis/3B058C775CE44FA6AC05608B196EDAB1"
         },
         "hostname":"MM5CF3FC25E03B",
         "domainName":"",
         "FRU":"68Y7032",
         "macAddresses":[
            "5C:F3:FC:25:DB:57"
         ],
         "uri":"cmm/256466549E0611E0A2F6872F34D5CCC9",
         "productId":"65",
         "powerAllocation":{
            "maximumAllocatedPower":20,
            "minimumAllocatedPower":20
         },
         "ipv6Addresses":[
            "fe80:0:0:0:5ef3:fcff:fe25:db57",
            "fd55:faaf:e1ab:2021:5ef3:fcff:fe25:db57"
         ],
         "overallHealthState":"Warning",
         "slots":[
            1
         ],
         "manufacturer":"IBM",
         "uuid":"256466549E0611E0A2F6872F34D5CCC9",
         "dnsHostnames":[
            "xhmcupdates5.labs.lenovo.com",
            "fd55:faaf:e1ab:2021:5ef3:fcff:fe25:db57"
         ],
         "fruSerialNumber":"Y034BG16E0C0"
      }
   ]
}
+ Response 400
+ Response 401
+ Response 404
+ Response 409
+ Response 500

# GET /cmms/80C0B2F6B84011E0B504EC89B07DB965,256466549E0611E0A2F6872F34D5CCC9?includeAttributes=accessState,backedBy

+ Response 200 (application/json)
{
   "cmmList":[
      {
         "accessState":"Online",
         "backedBy":"real",
         "parent":{
            "uuid":"7F3E7E375B5747E0938969896B1CFDF5",
            "uri":"chassis/7F3E7E375B5747E0938969896B1CFDF5"
         },
         "uuid":"80C0B2F6B84011E0B504EC89B07DB965",
         "uri":"cmm/80C0B2F6B84011E0B504EC89B07DB965",
         "dataHandle":1475517034173
      },
      {
         "accessState":"Online",
         "backedBy":"real",
         "parent":{
            "uuid":"3B058C775CE44FA6AC05608B196EDAB1",
            "uri":"chassis/3B058C775CE44FA6AC05608B196EDAB1"
         },
         "uuid":"256466549E0611E0A2F6872F34D5CCC9",
         "uri":"cmm/256466549E0611E0A2F6872F34D5CCC9",
         "dataHandle":1475517074784
      }
   ]
}
+ Response 400
+ Response 401
+ Response 404
+ Response 409
+ Response 500

# GET /cmms/80C0B2F6B84011E0B504EC89B07DB965?excludeAttributes=accessState,backedBy

+ Response 200 (application/json)
{
   "model":"",
   "manufacturerId":"20301",
   "serialNumber":"",
   "type":"CMM",
   "dataHandle":1475517034173,
   "ipv4Addresses":[
      "10.240.72.61"
   ],
   "cmmDisplayName":"SN#Y034BG176046",
   "hostConfig":[
      {
         "DDNSenabled":false,
         "terIPv6userDNSserver":"0:0:0:0:0:0:0:0",
         "DNSenabled":false,
         "IPversionPriority":"IPv6ThenIPv4",
         "secIPv4userDNSserver":"10.240.0.11",
         "terIPv4userDNSserver":"0.0.0.0",
         "priIPv6userDNSserver":"0:0:0:0:0:0:0:0",
         "secIPv6userDNSserver":"0:0:0:0:0:0:0:0",
         "priIPv4userDNSserver":"10.240.0.10"
      }
   ],
   "leds":[
      {
         "color":"Amber",
         "location":"FrontPanel",
         "name":"FAULT",
         "state":"Off"
      }
   ],
   "description":"CMM",
   "name":"SN#Y034BG176046",
   "errorFields":[

   ],
   "mgmtProcIPaddress":"10.240.72.61",
   "role":"primary",
   "cmmHealthState":"Non-Critical",
   "userDescription":"",
   "partNumber":"68Y7029",
   "ipInterfaces":[
      {
         "IPv4enabled":true,
         "IPv4DHCPmode":"STATIC_ONLY",
         "IPv6enabled":true,
         "IPv6DHCPenabled":true,
         "IPv4assignments":[
            {
               "id":2,
               "subnet":"255.255.252.0",
               "gateway":"10.240.72.1",
               "address":"10.240.72.61",
               "type":"CONFIGURED"
            },
            {
               "id":2,
               "subnet":"255.255.252.0",
               "gateway":"10.240.72.1",
               "address":"10.240.72.61",
               "type":"INUSE"
            }
         ],
         "IPv6assignments":[
            {
               "id":1,
               "scope":"LinkLocal",
               "gateway":"0:0:0:0:0:0:0:0",
               "source":"Other",
               "address":"fe80:0:0:0:5ef3:fcff:fe25:deb3",
               "prefix":64,
               "type":"INUSE"
            },
            {
               "id":2,
               "scope":"Global",
               "gateway":"0:0:0:0:0:0:0:0",
               "source":"Static",
               "address":"0:0:0:0:0:0:0:0",
               "prefix":0,
               "type":"CONFIGURED"
            }
         ],
         "name":"eth0",
         "IPv6statelessEnabled":false,
         "label":"External",
         "IPv6staticEnabled":false
      }
   ],
   "excludedHealthState":"Warning",
   "firmware":[
      {
         "status":"",
         "name":"CMM firmware",
         "role":"",
         "date":"2016-07-29T04:00:00Z",
         "type":"CMM firmware",
         "build":"2PET33B",
         "version":"2.5.7"
      }
   ],
   "machineType":"",
   "parent":{
      "uuid":"7F3E7E375B5747E0938969896B1CFDF5",
      "uri":"chassis/7F3E7E375B5747E0938969896B1CFDF5"
   },
   "hostname":"MM5CF3FC25DEB3",
   "domainName":"labs.lenovo.com",
   "FRU":"68Y7032",
   "macAddresses":[
      "5C:F3:FC:25:DE:B3"
   ],
   "uri":"cmm/80C0B2F6B84011E0B504EC89B07DB965",
   "productId":"65",
   "powerAllocation":{
      "maximumAllocatedPower":20,
      "minimumAllocatedPower":20
   },
   "ipv6Addresses":[
      "fe80:0:0:0:5ef3:fcff:fe25:deb3"
   ],
   "overallHealthState":"Warning",
   "slots":[
      1
   ],
   "manufacturer":"IBM",
   "uuid":"80C0B2F6B84011E0B504EC89B07DB965",
   "dnsHostnames":[
      "Chassis119.labs.lenovo.com"
   ],
   "fruSerialNumber":"Y034BG176046"
}
+ Response 400
+ Response 401
+ Response 404
+ Response 409
+ Response 500

# GET /cmms/80C0B2F6B84011E0B504EC89B07DB965?includeAttributes=accessState,backedBy

+ Response 200 (application/json)
{
   "accessState":"Online",
   "backedBy":"real",
   "parent":{
      "uuid":"7F3E7E375B5747E0938969896B1CFDF5",
      "uri":"chassis/7F3E7E375B5747E0938969896B1CFDF5"
   },
   "uuid":"80C0B2F6B84011E0B504EC89B07DB965",
   "uri":"cmm/80C0B2F6B84011E0B504EC89B07DB965",
   "dataHandle":1475517034173
}
+ Response 400
+ Response 401
+ Response 404
+ Response 409
+ Response 500

# GET /cmms?excludeAttributes=accessState,backedBy

+ Response 200 (application/json)
{
   "cmmList":[
      {
         "model":"",
         "manufacturerId":"20301",
         "serialNumber":"",
         "type":"CMM",
         "dataHandle":1475517034173,
         "ipv4Addresses":[
            "10.240.72.61"
         ],
         "cmmDisplayName":"SN#Y034BG176046",
         "hostConfig":[
            {
               "DDNSenabled":false,
               "terIPv6userDNSserver":"0:0:0:0:0:0:0:0",
               "DNSenabled":false,
               "IPversionPriority":"IPv6ThenIPv4",
               "secIPv4userDNSserver":"10.240.0.11",
               "terIPv4userDNSserver":"0.0.0.0",
               "priIPv6userDNSserver":"0:0:0:0:0:0:0:0",
               "secIPv6userDNSserver":"0:0:0:0:0:0:0:0",
               "priIPv4userDNSserver":"10.240.0.10"
            }
         ],
         "leds":[
            {
               "color":"Amber",
               "location":"FrontPanel",
               "name":"FAULT",
               "state":"Off"
            }
         ],
         "description":"CMM",
         "name":"SN#Y034BG176046",
         "errorFields":[

         ],
         "mgmtProcIPaddress":"10.240.72.61",
         "role":"primary",
         "cmmHealthState":"Non-Critical",
         "userDescription":"",
         "partNumber":"68Y7029",
         "ipInterfaces":[
            {
               "IPv4enabled":true,
               "IPv4DHCPmode":"STATIC_ONLY",
               "IPv6enabled":true,
               "IPv6DHCPenabled":true,
               "IPv4assignments":[
                  {
                     "id":2,
                     "subnet":"255.255.252.0",
                     "gateway":"10.240.72.1",
                     "address":"10.240.72.61",
                     "type":"CONFIGURED"
                  },
                  {
                     "id":2,
                     "subnet":"255.255.252.0",
                     "gateway":"10.240.72.1",
                     "address":"10.240.72.61",
                     "type":"INUSE"
                  }
               ],
               "IPv6assignments":[
                  {
                     "id":1,
                     "scope":"LinkLocal",
                     "gateway":"0:0:0:0:0:0:0:0",
                     "source":"Other",
                     "address":"fe80:0:0:0:5ef3:fcff:fe25:deb3",
                     "prefix":64,
                     "type":"INUSE"
                  },
                  {
                     "id":2,
                     "scope":"Global",
                     "gateway":"0:0:0:0:0:0:0:0",
                     "source":"Static",
                     "address":"0:0:0:0:0:0:0:0",
                     "prefix":0,
                     "type":"CONFIGURED"
                  }
               ],
               "name":"eth0",
               "IPv6statelessEnabled":false,
               "label":"External",
               "IPv6staticEnabled":false
            }
         ],
         "excludedHealthState":"Warning",
         "firmware":[
            {
               "status":"",
               "name":"CMM firmware",
               "role":"",
               "date":"2016-07-29T04:00:00Z",
               "type":"CMM firmware",
               "build":"2PET33B",
               "version":"2.5.7"
            }
         ],
         "machineType":"",
         "parent":{
            "uuid":"7F3E7E375B5747E0938969896B1CFDF5",
            "uri":"chassis/7F3E7E375B5747E0938969896B1CFDF5"
         },
         "hostname":"MM5CF3FC25DEB3",
         "domainName":"labs.lenovo.com",
         "FRU":"68Y7032",
         "macAddresses":[
            "5C:F3:FC:25:DE:B3"
         ],
         "uri":"cmm/80C0B2F6B84011E0B504EC89B07DB965",
         "productId":"65",
         "powerAllocation":{
            "maximumAllocatedPower":20,
            "minimumAllocatedPower":20
         },
         "ipv6Addresses":[
            "fe80:0:0:0:5ef3:fcff:fe25:deb3"
         ],
         "overallHealthState":"Warning",
         "slots":[
            1
         ],
         "manufacturer":"IBM",
         "uuid":"80C0B2F6B84011E0B504EC89B07DB965",
         "dnsHostnames":[
            "Chassis119.labs.lenovo.com"
         ],
         "fruSerialNumber":"Y034BG176046"
      },
      {
         "model":"",
         "manufacturerId":"20301",
         "serialNumber":"",
         "type":"CMM",
         "dataHandle":1475517074784,
         "ipv4Addresses":[
            "10.243.1.141"
         ],
         "cmmDisplayName":"SN#Y034BG16E0C0",
         "hostConfig":[
            {
               "DDNSenabled":false,
               "terIPv6userDNSserver":"0:0:0:0:0:0:0:0",
               "DNSenabled":false,
               "IPversionPriority":"IPv6ThenIPv4",
               "secIPv4userDNSserver":"0.0.0.0",
               "terIPv4userDNSserver":"0.0.0.0",
               "priIPv6userDNSserver":"0:0:0:0:0:0:0:0",
               "secIPv6userDNSserver":"0:0:0:0:0:0:0:0",
               "priIPv4userDNSserver":"0.0.0.0"
            }
         ],
         "leds":[
            {
               "color":"Amber",
               "location":"FrontPanel",
               "name":"FAULT",
               "state":"Off"
            }
         ],
         "description":"CMM",
         "name":"SN#Y034BG16E0C0",
         "errorFields":[

         ],
         "mgmtProcIPaddress":"10.243.1.141",
         "role":"primary",
         "cmmHealthState":"Non-Critical",
         "userDescription":"",
         "partNumber":"68Y7029",
         "ipInterfaces":[
            {
               "IPv4enabled":true,
               "IPv4DHCPmode":"STATIC_ONLY",
               "IPv6enabled":true,
               "IPv6DHCPenabled":true,
               "IPv4assignments":[
                  {
                     "id":2,
                     "subnet":"255.255.240.0",
                     "gateway":"10.243.0.1",
                     "address":"10.243.1.141",
                     "type":"CONFIGURED"
                  },
                  {
                     "id":2,
                     "subnet":"255.255.240.0",
                     "gateway":"10.243.0.1",
                     "address":"10.243.1.141",
                     "type":"INUSE"
                  }
               ],
               "IPv6assignments":[
                  {
                     "id":1,
                     "scope":"LinkLocal",
                     "gateway":"0:0:0:0:0:0:0:0",
                     "source":"Other",
                     "address":"fe80:0:0:0:5ef3:fcff:fe25:db57",
                     "prefix":64,
                     "type":"INUSE"
                  },
                  {
                     "id":2,
                     "scope":"Global",
                     "gateway":"0:0:0:0:0:0:0:0",
                     "source":"Static",
                     "address":"0:0:0:0:0:0:0:0",
                     "prefix":0,
                     "type":"CONFIGURED"
                  },
                  {
                     "id":16,
                     "scope":"Global",
                     "gateway":"0:0:0:0:0:0:0:0",
                     "source":"Stateless",
                     "address":"fd55:faaf:e1ab:2021:5ef3:fcff:fe25:db57",
                     "prefix":64,
                     "type":"INUSE"
                  }
               ],
               "name":"eth0",
               "IPv6statelessEnabled":true,
               "label":"External",
               "IPv6staticEnabled":false
            }
         ],
         "excludedHealthState":"Warning",
         "firmware":[
            {
               "status":"",
               "name":"CMM firmware",
               "role":"",
               "date":"2016-07-29T04:00:00Z",
               "type":"CMM firmware",
               "build":"2PET33B",
               "version":"2.5.7"
            }
         ],
         "machineType":"",
         "parent":{
            "uuid":"3B058C775CE44FA6AC05608B196EDAB1",
            "uri":"chassis/3B058C775CE44FA6AC05608B196EDAB1"
         },
         "hostname":"MM5CF3FC25E03B",
         "domainName":"",
         "FRU":"68Y7032",
         "macAddresses":[
            "5C:F3:FC:25:DB:57"
         ],
         "uri":"cmm/256466549E0611E0A2F6872F34D5CCC9",
         "productId":"65",
         "powerAllocation":{
            "maximumAllocatedPower":20,
            "minimumAllocatedPower":20
         },
         "ipv6Addresses":[
            "fe80:0:0:0:5ef3:fcff:fe25:db57",
            "fd55:faaf:e1ab:2021:5ef3:fcff:fe25:db57"
         ],
         "overallHealthState":"Warning",
         "slots":[
            1
         ],
         "manufacturer":"IBM",
         "uuid":"256466549E0611E0A2F6872F34D5CCC9",
         "dnsHostnames":[
            "xhmcupdates5.labs.lenovo.com",
            "fd55:faaf:e1ab:2021:5ef3:fcff:fe25:db57"
         ],
         "fruSerialNumber":"Y034BG16E0C0"
      }
   ]
}
+ Response 400
+ Response 401
+ Response 404
+ Response 409
+ Response 500

# GET /cmms?includeAttributes=accessState,backedBy

+ Response 200 (application/json)
{
   "cmmList":[
      {
         "accessState":"Online",
         "backedBy":"real",
         "parent":{
            "uuid":"7F3E7E375B5747E0938969896B1CFDF5",
            "uri":"chassis/7F3E7E375B5747E0938969896B1CFDF5"
         },
         "uuid":"80C0B2F6B84011E0B504EC89B07DB965",
         "uri":"cmm/80C0B2F6B84011E0B504EC89B07DB965",
         "dataHandle":1475517034173
      },
      {
         "accessState":"Online",
         "backedBy":"real",
         "parent":{
            "uuid":"3B058C775CE44FA6AC05608B196EDAB1",
            "uri":"chassis/3B058C775CE44FA6AC05608B196EDAB1"
         },
         "uuid":"256466549E0611E0A2F6872F34D5CCC9",
         "uri":"cmm/256466549E0611E0A2F6872F34D5CCC9",
         "dataHandle":1475517074784
      }
   ]
}
+ Response 400
+ Response 401
+ Response 404
+ Response 409
+ Response 500

# GET /cmms

+ Response 200 (application/json)
{
   "cmmList":[
      {
         "accessState":"Online",
         "model":"",
         "manufacturerId":"20301",
         "serialNumber":"",
         "type":"CMM",
         "dataHandle":1475517034173,
         "ipv4Addresses":[
            "10.240.72.61"
         ],
         "backedBy":"real",
         "cmmDisplayName":"SN#Y034BG176046",
         "hostConfig":[
            {
               "DDNSenabled":false,
               "terIPv6userDNSserver":"0:0:0:0:0:0:0:0",
               "DNSenabled":false,
               "IPversionPriority":"IPv6ThenIPv4",
               "secIPv4userDNSserver":"10.240.0.11",
               "terIPv4userDNSserver":"0.0.0.0",
               "priIPv6userDNSserver":"0:0:0:0:0:0:0:0",
               "secIPv6userDNSserver":"0:0:0:0:0:0:0:0",
               "priIPv4userDNSserver":"10.240.0.10"
            }
         ],
         "leds":[
            {
               "color":"Amber",
               "location":"FrontPanel",
               "name":"FAULT",
               "state":"Off"
            }
         ],
         "description":"CMM",
         "name":"SN#Y034BG176046",
         "mgmtProcIPaddress":"10.240.72.61",
         "errorFields":[

         ],
         "role":"primary",
         "cmmHealthState":"Non-Critical",
         "userDescription":"",
         "partNumber":"68Y7029",
         "ipInterfaces":[
            {
               "IPv4enabled":true,
               "IPv4DHCPmode":"STATIC_ONLY",
               "IPv6enabled":true,
               "IPv6DHCPenabled":true,
               "IPv4assignments":[
                  {
                     "id":2,
                     "subnet":"255.255.252.0",
                     "gateway":"10.240.72.1",
                     "address":"10.240.72.61",
                     "type":"CONFIGURED"
                  },
                  {
                     "id":2,
                     "subnet":"255.255.252.0",
                     "gateway":"10.240.72.1",
                     "address":"10.240.72.61",
                     "type":"INUSE"
                  }
               ],
               "IPv6assignments":[
                  {
                     "id":1,
                     "scope":"LinkLocal",
                     "gateway":"0:0:0:0:0:0:0:0",
                     "source":"Other",
                     "address":"fe80:0:0:0:5ef3:fcff:fe25:deb3",
                     "prefix":64,
                     "type":"INUSE"
                  },
                  {
                     "id":2,
                     "scope":"Global",
                     "gateway":"0:0:0:0:0:0:0:0",
                     "source":"Static",
                     "address":"0:0:0:0:0:0:0:0",
                     "prefix":0,
                     "type":"CONFIGURED"
                  }
               ],
               "name":"eth0",
               "IPv6statelessEnabled":false,
               "label":"External",
               "IPv6staticEnabled":false
            }
         ],
         "excludedHealthState":"Warning",
         "firmware":[
            {
               "status":"",
               "name":"CMM firmware",
               "role":"",
               "date":"2016-07-29T04:00:00Z",
               "type":"CMM firmware",
               "build":"2PET33B",
               "version":"2.5.7"
            }
         ],
         "machineType":"",
         "parent":{
            "uuid":"7F3E7E375B5747E0938969896B1CFDF5",
            "uri":"chassis/7F3E7E375B5747E0938969896B1CFDF5"
         },
         "hostname":"MM5CF3FC25DEB3",
         "domainName":"labs.lenovo.com",
         "FRU":"68Y7032",
         "macAddresses":[
            "5C:F3:FC:25:DE:B3"
         ],
         "uri":"cmm/80C0B2F6B84011E0B504EC89B07DB965",
         "productId":"65",
         "powerAllocation":{
            "maximumAllocatedPower":20,
            "minimumAllocatedPower":20
         },
         "ipv6Addresses":[
            "fe80:0:0:0:5ef3:fcff:fe25:deb3"
         ],
         "overallHealthState":"Warning",
         "slots":[
            1
         ],
         "manufacturer":"IBM",
         "uuid":"80C0B2F6B84011E0B504EC89B07DB965",
         "dnsHostnames":[
            "Chassis119.labs.lenovo.com"
         ],
         "fruSerialNumber":"Y034BG176046"
      },
      {
         "accessState":"Online",
         "model":"",
         "manufacturerId":"20301",
         "serialNumber":"",
         "type":"CMM",
         "dataHandle":1475517074784,
         "ipv4Addresses":[
            "10.243.1.141"
         ],
         "backedBy":"real",
         "cmmDisplayName":"SN#Y034BG16E0C0",
         "hostConfig":[
            {
               "DDNSenabled":false,
               "terIPv6userDNSserver":"0:0:0:0:0:0:0:0",
               "DNSenabled":false,
               "IPversionPriority":"IPv6ThenIPv4",
               "secIPv4userDNSserver":"0.0.0.0",
               "terIPv4userDNSserver":"0.0.0.0",
               "priIPv6userDNSserver":"0:0:0:0:0:0:0:0",
               "secIPv6userDNSserver":"0:0:0:0:0:0:0:0",
               "priIPv4userDNSserver":"0.0.0.0"
            }
         ],
         "leds":[
            {
               "color":"Amber",
               "location":"FrontPanel",
               "name":"FAULT",
               "state":"Off"
            }
         ],
         "description":"CMM",
         "name":"SN#Y034BG16E0C0",
         "mgmtProcIPaddress":"10.243.1.141",
         "errorFields":[

         ],
         "role":"primary",
         "cmmHealthState":"Non-Critical",
         "userDescription":"",
         "partNumber":"68Y7029",
         "ipInterfaces":[
            {
               "IPv4enabled":true,
               "IPv4DHCPmode":"STATIC_ONLY",
               "IPv6enabled":true,
               "IPv6DHCPenabled":true,
               "IPv4assignments":[
                  {
                     "id":2,
                     "subnet":"255.255.240.0",
                     "gateway":"10.243.0.1",
                     "address":"10.243.1.141",
                     "type":"CONFIGURED"
                  },
                  {
                     "id":2,
                     "subnet":"255.255.240.0",
                     "gateway":"10.243.0.1",
                     "address":"10.243.1.141",
                     "type":"INUSE"
                  }
               ],
               "IPv6assignments":[
                  {
                     "id":1,
                     "scope":"LinkLocal",
                     "gateway":"0:0:0:0:0:0:0:0",
                     "source":"Other",
                     "address":"fe80:0:0:0:5ef3:fcff:fe25:db57",
                     "prefix":64,
                     "type":"INUSE"
                  },
                  {
                     "id":2,
                     "scope":"Global",
                     "gateway":"0:0:0:0:0:0:0:0",
                     "source":"Static",
                     "address":"0:0:0:0:0:0:0:0",
                     "prefix":0,
                     "type":"CONFIGURED"
                  },
                  {
                     "id":16,
                     "scope":"Global",
                     "gateway":"0:0:0:0:0:0:0:0",
                     "source":"Stateless",
                     "address":"fd55:faaf:e1ab:2021:5ef3:fcff:fe25:db57",
                     "prefix":64,
                     "type":"INUSE"
                  }
               ],
               "name":"eth0",
               "IPv6statelessEnabled":true,
               "label":"External",
               "IPv6staticEnabled":false
            }
         ],
         "excludedHealthState":"Warning",
         "firmware":[
            {
               "status":"",
               "name":"CMM firmware",
               "role":"",
               "date":"2016-07-29T04:00:00Z",
               "type":"CMM firmware",
               "build":"2PET33B",
               "version":"2.5.7"
            }
         ],
         "machineType":"",
         "parent":{
            "uuid":"3B058C775CE44FA6AC05608B196EDAB1",
            "uri":"chassis/3B058C775CE44FA6AC05608B196EDAB1"
         },
         "hostname":"MM5CF3FC25E03B",
         "domainName":"",
         "FRU":"68Y7032",
         "macAddresses":[
            "5C:F3:FC:25:DB:57"
         ],
         "uri":"cmm/256466549E0611E0A2F6872F34D5CCC9",
         "productId":"65",
         "powerAllocation":{
            "maximumAllocatedPower":20,
            "minimumAllocatedPower":20
         },
         "ipv6Addresses":[
            "fe80:0:0:0:5ef3:fcff:fe25:db57",
            "fd55:faaf:e1ab:2021:5ef3:fcff:fe25:db57"
         ],
         "overallHealthState":"Warning",
         "slots":[
            1
         ],
         "manufacturer":"IBM",
         "uuid":"256466549E0611E0A2F6872F34D5CCC9",
         "dnsHostnames":[
            "xhmcupdates5.labs.lenovo.com",
            "fd55:faaf:e1ab:2021:5ef3:fcff:fe25:db57"
         ],
         "fruSerialNumber":"Y034BG16E0C0"
      }
   ]
}
+ Response 400
+ Response 401
+ Response 404
+ Response 409
+ Response 500
