FORMAT: 1A

# Ffdc

# GET /config/target/65

+ Response 200 (application/json)
{
    "identifier": "id",
    "items": [
        {
            "access": "unknown",
            "children": [
                {
                    "ites": [
                        {
                            "access": "unknown",
                            "architecture": "x86",
                            "bays": [
                                "1"
                            ],
                            "deployCompatibility": {
                                "message": "The pattern can be deployed to this server or bay.",
                                "status": "READY"
                            },
                            "firmwareLevel": "compatible",
                            "formFactor": "f",
                            "id": "FA59C0BBC43C3C15B9D72B94AFF52B91",
                            "location": "F44E92339683385A8D97CD6348A6F45F_bay1",
                            "mgmtIp": "169.254.2.155",
                            "name": "Demo - 00410X7162",
                            "powerStatus": "on",
                            "productName": "Lenovo Flex System x240 Compute Node",
                            "profile": "",
                            "rackId": "",
                            "schedule": "unassigned",
                            "subBays": [],
                            "type": "imm",
                            "unit": 0
                        }
                    ]
                },
                {
                    "ites": [
                        {
                            "access": "unknown",
                            "architecture": "x86",
                            "bays": [
                                "2"
                            ],
                            "deployCompatibility": {
                                "message": "The pattern can be deployed to this server or bay.",
                                "status": "READY"
                            },
                            "firmwareLevel": "compatible",
                            "formFactor": "f",
                            "id": "29C5281206083D21AF8721A0823E2F29",
                            "location": "F44E92339683385A8D97CD6348A6F45F_bay2",
                            "mgmtIp": "169.254.2.182",
                            "name": "Demo - 00437X7162",
                            "powerStatus": "on",
                            "productName": "Lenovo Flex System x240 Compute Node",
                            "profile": "",
                            "rackId": "",
                            "schedule": "unassigned",
                            "subBays": [],
                            "type": "imm",
                            "unit": 0
                        }
                    ]
                },
                {
                    "ites": [
                        {
                            "access": "unknown",
                            "architecture": "x86",
                            "bays": [
                                "3"
                            ],
                            "deployCompatibility": {
                                "message": "The pattern can be deployed to this server or bay.",
                                "status": "READY"
                            },
                            "firmwareLevel": "compatible",
                            "formFactor": "f",
                            "id": "DC5C4F4F16F23C63A7B7125EB50AC2E6",
                            "location": "F44E92339683385A8D97CD6348A6F45F_bay3",
                            "mgmtIp": "169.254.2.209",
                            "name": "Demo - 00464X7162",
                            "powerStatus": "on",
                            "productName": "Lenovo Flex System x240 Compute Node",
                            "profile": "",
                            "rackId": "",
                            "schedule": "unassigned",
                            "subBays": [],
                            "type": "imm",
                            "unit": 0
                        }
                    ]
                },
                {
                    "ites": [
                        {
                            "access": "unknown",
                            "architecture": "x86",
                            "bays": [
                                "4"
                            ],
                            "deployCompatibility": {
                                "message": "The pattern can be deployed to this server or bay.",
                                "status": "READY"
                            },
                            "firmwareLevel": "compatible",
                            "formFactor": "f",
                            "id": "4CB4B50C8C033C0D8429ED7742EBDBA1",
                            "location": "F44E92339683385A8D97CD6348A6F45F_bay4",
                            "mgmtIp": "169.254.2.236",
                            "name": "Demo - 00491X7162",
                            "powerStatus": "on",
                            "productName": "Lenovo Flex System x240 Compute Node",
                            "profile": "",
                            "rackId": "",
                            "schedule": "unassigned",
                            "subBays": [],
                            "type": "imm",
                            "unit": 0
                        }
                    ]
                },
                {
                    "ites": [
                        {
                            "access": "unknown",
                            "architecture": "x86",
                            "bays": [
                                "5"
                            ],
                            "deployCompatibility": {
                                "message": "The pattern can be deployed to this server or bay.",
                                "status": "READY"
                            },
                            "firmwareLevel": "compatible",
                            "formFactor": "f",
                            "id": "C65430DCB6C3318BBEC070B9B13AE833",
                            "location": "F44E92339683385A8D97CD6348A6F45F_bay5",
                            "mgmtIp": "169.254.3.7",
                            "name": "Demo - 00518X7162",
                            "powerStatus": "on",
                            "productName": "Lenovo Flex System x240 Compute Node",
                            "profile": "",
                            "rackId": "",
                            "schedule": "unassigned",
                            "subBays": [],
                            "type": "imm",
                            "unit": 0
                        }
                    ]
                },
                {
                    "ites": [
                        {
                            "access": "unknown",
                            "architecture": "x86",
                            "bays": [
                                "6"
                            ],
                            "deployCompatibility": {
                                "message": "The pattern can be deployed to this server or bay.",
                                "status": "READY"
                            },
                            "firmwareLevel": "compatible",
                            "formFactor": "f",
                            "id": "A292C6D8349C3EA988BE0BFFD9D8FF86",
                            "location": "F44E92339683385A8D97CD6348A6F45F_bay6",
                            "mgmtIp": "169.254.3.34",
                            "name": "Demo - 00545X7162",
                            "powerStatus": "on",
                            "productName": "Lenovo Flex System x240 Compute Node",
                            "profile": "",
                            "rackId": "",
                            "schedule": "unassigned",
                            "subBays": [],
                            "type": "imm",
                            "unit": 0
                        }
                    ]
                },
                {
                    "ites": [
                        {
                            "access": "unknown",
                            "architecture": "x86",
                            "bays": [
                                "7"
                            ],
                            "deployCompatibility": {
                                "message": "The pattern can be deployed to this server or bay.",
                                "status": "READY"
                            },
                            "firmwareLevel": "compatible",
                            "formFactor": "f",
                            "id": "6935BDDCDD5F3620B1C770209844EEFB",
                            "location": "F44E92339683385A8D97CD6348A6F45F_bay7",
                            "mgmtIp": "169.254.3.61",
                            "name": "Demo - 00572X7162",
                            "powerStatus": "on",
                            "productName": "Lenovo Flex System x240 Compute Node",
                            "profile": "",
                            "rackId": "",
                            "schedule": "unassigned",
                            "subBays": [],
                            "type": "imm",
                            "unit": 0
                        }
                    ]
                },
                {
                    "ites": [
                        {
                            "access": "unknown",
                            "architecture": "x86",
                            "bays": [
                                "8"
                            ],
                            "deployCompatibility": {
                                "message": "The pattern can be deployed to this server or bay.",
                                "status": "READY"
                            },
                            "firmwareLevel": "compatible",
                            "formFactor": "f",
                            "id": "6D4A07DABB0336DC8520B2EC5BB537A6",
                            "location": "F44E92339683385A8D97CD6348A6F45F_bay8",
                            "mgmtIp": "169.254.3.88",
                            "name": "Demo - 00599X7162",
                            "powerStatus": "on",
                            "productName": "Lenovo Flex System x240 Compute Node",
                            "profile": "",
                            "rackId": "",
                            "schedule": "unassigned",
                            "subBays": [],
                            "type": "imm",
                            "unit": 0
                        }
                    ]
                },
                {
                    "ites": [
                        {
                            "access": "unknown",
                            "architecture": "x86",
                            "bays": [
                                "9"
                            ],
                            "deployCompatibility": {
                                "message": "The pattern can be deployed to this server or bay.",
                                "status": "READY"
                            },
                            "firmwareLevel": "compatible",
                            "formFactor": "f",
                            "id": "A78707FDDC3D32AE81F78911B4E99AAD",
                            "location": "F44E92339683385A8D97CD6348A6F45F_bay9",
                            "mgmtIp": "169.254.3.115",
                            "name": "Demo - 00626X7162",
                            "powerStatus": "on",
                            "productName": "Lenovo Flex System x240 Compute Node",
                            "profile": "",
                            "rackId": "",
                            "schedule": "unassigned",
                            "subBays": [],
                            "type": "imm",
                            "unit": 0
                        }
                    ]
                },
                {
                    "ites": [
                        {
                            "access": "unknown",
                            "architecture": "x86",
                            "bays": [
                                "10"
                            ],
                            "deployCompatibility": {
                                "message": "The pattern can be deployed to this server or bay.",
                                "status": "READY"
                            },
                            "firmwareLevel": "compatible",
                            "formFactor": "f",
                            "id": "07FCC2D043C330DC9BBB4AA0E15A7C61",
                            "location": "F44E92339683385A8D97CD6348A6F45F_bay10",
                            "mgmtIp": "169.254.3.142",
                            "name": "Demo - 00653X7162",
                            "powerStatus": "on",
                            "productName": "Lenovo Flex System x240 Compute Node",
                            "profile": "",
                            "rackId": "",
                            "schedule": "unassigned",
                            "subBays": [],
                            "type": "imm",
                            "unit": 0
                        }
                    ]
                },
                {
                    "ites": [
                        {
                            "access": "unknown",
                            "architecture": "x86",
                            "bays": [
                                "11"
                            ],
                            "deployCompatibility": {
                                "message": "The pattern can be deployed to this server or bay.",
                                "status": "READY"
                            },
                            "firmwareLevel": "compatible",
                            "formFactor": "f",
                            "id": "7BA09F498C7C3164B91AE940B0ADF4B2",
                            "location": "F44E92339683385A8D97CD6348A6F45F_bay11",
                            "mgmtIp": "169.254.3.169",
                            "name": "Demo - 00680X7162",
                            "powerStatus": "on",
                            "productName": "Lenovo Flex System x240 Compute Node",
                            "profile": "",
                            "rackId": "",
                            "schedule": "unassigned",
                            "subBays": [],
                            "type": "imm",
                            "unit": 0
                        }
                    ]
                },
                {
                    "ites": [
                        {
                            "access": "unknown",
                            "architecture": "x86",
                            "bays": [
                                "12"
                            ],
                            "deployCompatibility": {
                                "message": "The pattern can be deployed to this server or bay.",
                                "status": "READY"
                            },
                            "firmwareLevel": "compatible",
                            "formFactor": "f",
                            "id": "EC96C3433ABC36FEA2FF48ADA9C7241F",
                            "location": "F44E92339683385A8D97CD6348A6F45F_bay12",
                            "mgmtIp": "169.254.3.196",
                            "name": "Demo - 00707X7162",
                            "powerStatus": "on",
                            "productName": "Lenovo Flex System x240 Compute Node",
                            "profile": "",
                            "rackId": "",
                            "schedule": "unassigned",
                            "subBays": [],
                            "type": "imm",
                            "unit": 0
                        }
                    ]
                },
                {
                    "ites": [
                        {
                            "access": "unknown",
                            "architecture": "x86",
                            "bays": [
                                "13"
                            ],
                            "deployCompatibility": {
                                "message": "The pattern can be deployed to this server or bay.",
                                "status": "READY"
                            },
                            "firmwareLevel": "compatible",
                            "formFactor": "f",
                            "id": "57E19EE96D4B352991326D0FDB1C9A4E",
                            "location": "F44E92339683385A8D97CD6348A6F45F_bay13",
                            "mgmtIp": "169.254.3.223",
                            "name": "Demo - 00734X7162",
                            "powerStatus": "on",
                            "productName": "Lenovo Flex System x240 Compute Node",
                            "profile": "",
                            "rackId": "",
                            "schedule": "unassigned",
                            "subBays": [],
                            "type": "imm",
                            "unit": 0
                        }
                    ]
                },
                {
                    "ites": [
                        {
                            "access": "unknown",
                            "architecture": "x86",
                            "bays": [
                                "14"
                            ],
                            "deployCompatibility": {
                                "message": "The pattern can be deployed to this server or bay.",
                                "status": "READY"
                            },
                            "firmwareLevel": "compatible",
                            "formFactor": "f",
                            "id": "2EFBDD83153132B5B75EE2668F6EA250",
                            "location": "F44E92339683385A8D97CD6348A6F45F_bay14",
                            "mgmtIp": "169.254.3.250",
                            "name": "Demo - 00761X7162",
                            "powerStatus": "on",
                            "productName": "Lenovo Flex System x240 Compute Node",
                            "profile": "",
                            "rackId": "",
                            "schedule": "unassigned",
                            "subBays": [],
                            "type": "imm",
                            "unit": 0
                        }
                    ]
                }
            ],
            "description": "",
            "firmwareLevel": "compatible",
            "id": "F44E92339683385A8D97CD6348A6F45F",
            "ipaddresses": "",
            "name": "Demo - Lenovo demo chassis 00001",
            "type": "chassis",
            "uuid": "F44E92339683385A8D97CD6348A6F45F"
        }
    ],
    "label": "name"
}

+ Response 400
+ Response 401
+ Response 404
+ Response 409
+ Response 500

