FORMAT: 1A

# Ffdc

# GET /ffdc/endpoint/1B33D6D13F267A614567A897DC784F00

+ Response 201 (application/json)

{"jobURL":"/jobs/289"}

+ Response 400
+ Response 401
+ Response 404
+ Response 409
+ Response 500

