FORMAT: 1A

# XClarity Nodes

# GET /nodes

+ Response 200 (application/json)
  {
  "nodeList": [{
    "accessState": "Online",
    "activationKeys": [{
      "description": "IBM Integrated Management Module Advanced Upgrade",
      "keyExpirationDate": "",
      "keyFeatureType": 1,
      "keyIdentiferList": [{
        "keyIdentifier": "5463KVD0153",
        "keyIdentifierType": "MT"
      }],
      "keyStatus": "VALID",
      "keyUseCount": 0,
      "keyUseLimit": 0,
      "uuid": "8f0f1789295e78f9"
    }],
    "addinCardSlots": 0,
    "addinCards": [{
      "FRU": "N/A",
      "firmware": [{
        "build": "0",
        "classifications": [13],
        "date": "2015-04-06T00:00:00Z",
        "name": "LSI MegaRAID Controller Firmware",
        "revision": "0",
        "role": "Primary",
        "softwareID": "10140454",
        "status": "Active",
        "type": "Software Bundle",
        "version": "24.7.0-0052"
      }],
      "fodUniqueID": "N/A",
      "fruSerialNumber": "SV42100396",
      "isAddOnCard": true,
      "isAgentless": true,
      "manufacturer": "IBM",
      "name": "ServeRAID M5210",
      "partNumber": "N/A",
      "pciBusNumber": "1",
      "pciDeviceNumber": "0",
      "pciFunctionNumber": "0",
      "pciRevision": "2",
      "pciSubID": "454",
      "pciSubVendorID": "1014",
      "portInfo": {

      },
      "posID": "5d",
      "productName": "ServeRAID M5210",
      "slotName": "SlotDesig4_Slot 4",
      "slotNumber": "4",
      "slotSupportsHotPlug": "false",
      "vpdID": "1000"
    }],
    "arch": "x86",
    "backedBy": "real",
    "bladeState": 0,
    "bootMode": {
      "currentValue": "UEFI Mode",
      "possibleValues": ["UEFI Mode",
        "Legacy Mode"
      ]
    },
    "bootOrder": {
      "bootOrderList": [{
        "bootType": "SingleUse",
        "currentBootOrderDevices": ["None"],
        "possibleBootOrderDevices": ["None",
          "PXE Network",
          "Hard Disk 0",
          "Diagnostics",
          "CD/DVD Rom",
          "Boot To F1",
          "Hypervisor",
          "Floppy Disk"
        ]
      }, {
        "bootType": "WakeOnLAN",
        "currentBootOrderDevices": ["PXE Network",
          "CD/DVD Rom",
          "Hard Disk 0"
        ],
        "possibleBootOrderDevices": ["PXE Network",
          "CD/DVD Rom",
          "Hard Disk 0",
          "Floppy Disk",
          "sSATA Port 2",
          "sSATA Port 3",
          "DSA"
        ]
      }],
      "uri": "node/425AF828DF7D11D4B0F8E76767BBBBBB/bootOrder"
    },
    "cmmDisplayName": "Management Controller UUID-425AF828DF7D11D4B0F8E76767BBBBBB",
    "cmmHealthState": "Normal",
    "complexID": -1,
    "contact": "",
    "dataHandle": 1440525606363,
    "description": "Cmms",
    "dnsHostnames": ["10.243.6.69",
      "fd55:faaf:e1ab:2021:42f2:e9ff:feb8:1585"
    ],
    "domainName": "",
    "driveBays": 0,
    "drives": [],
    "embeddedHypervisorPresence": false,
    "encapsulation": {
      "encapsulationMode": "normal"
    },
    "errorFields": [{
      "CmmsMounted": "NO_CONNECTOR"
    }],
    "excludedHealthState": "Normal",
    "expansionCardSlots": 0,
    "expansionCards": [],
    "expansionProductType": "",
    "expansionProducts": [],
    "firmware": [{
      "build": "TBE105KUS",
      "date": "2015-04-17T00:00:00Z",
      "name": "UEFI Firmware/BIOS",
      "role": "Primary",
      "status": "Active",
      "type": "UEFI",
      "version": "1.10"
    }, {
      "build": "TBE105KUS",
      "date": "2015-04-17T00:00:00Z",
      "name": "UEFI Backup Firmware/BIOS",
      "role": "Backup",
      "status": "Inactive",
      "type": "UEFI-Backup",
      "version": "1.10"
    }, {
      "build": "TCOO09D",
      "date": "2015-04-17T00:00:00Z",
      "name": "IMM2 Backup Firmware",
      "role": "Backup",
      "status": "Inactive",
      "type": "IMM2-Backup",
      "version": "1.71"
    }],
    "flashStorage": [],
    "FRU": "None",
    "fruSerialNumber": "None",
    "hasOS": false,
    "height": 1,
    "hostMacAddresses": "40:F2:E9:B8:15:80,40:F2:E9:B8:15:81,40:F2:E9:B8:15:82,40:F2:E9:B8:15:83",
    "hostname": "IMM2-40f2e9b81585",
    "ipInterfaces": [{
      "IPv4DHCPmode": "STATIC_ONLY",
      "IPv4assignments": [{
        "address": "10.243.6.69",
        "gateway": "0.0.0.0",
        "id": 0,
        "subnet": "255.255.240.0",
        "type": "INUSE"
      }],
      "IPv4enabled": true,
      "IPv6DHCPenabled": true,
      "IPv6assignments": [{
        "address": "fd55:faaf:e1ab:2021:42f2:e9ff:feb8:1585",
        "gateway": "0:0:0:0:0:0:0:0",
        "id": 0,
        "prefix": 64,
        "scope": "Global",
        "source": "Stateless",
        "type": "INUSE"
      }, {
        "address": "fe80:0:0:0:42f2:e9ff:feb8:1585",
        "gateway": "0:0:0:0:0:0:0:0",
        "id": 0,
        "prefix": 64,
        "scope": "LinkLocal",
        "source": "Other",
        "type": "INUSE"
      }],
      "IPv6enabled": true,
      "IPv6statelessEnabled": true,
      "IPv6staticEnabled": false,
      "label": "unknown",
      "name": "eth0"
    }],
    "ipv4Addresses": ["10.243.6.69",
      "169.254.95.118"
    ],
    "ipv6Addresses": ["fd55:faaf:e1ab:2021:42f2:e9ff:feb8:1585",
      "fe80::42f2:e9ff:feb8:1585"
    ],
    "isConnectionTrusted": "true",
    "isITME": false,
    "isRemotePresenceEnabled": true,
    "isScalable": false,
    "lanOverUsb": "enabled",
    "leds": [{
      "color": "Yellow",
      "location": "Unknown",
      "name": "Fault",
      "state": "Off"
    }, {
      "color": "Blue",
      "location": "Unknown",
      "name": "Identify",
      "state": "Off"
    }, {
      "color": "Yellow",
      "location": "Planar",
      "name": "SDRAID Error",
      "state": "Off"
    }],
    "location": {
      "location": "",
      "lowestRackUnit": 0,
      "rack": "",
      "room": ""
    },
    "macAddress": "40:F2:E9:B8:15:85,40:F2:E9:B8:15:86",
    "machineType": "5463",
    "manufacturer": " IBM(WIST)",
    "manufacturerId": " IBM(WIST)",
    "memoryModules": [{
      "capacity": 4,
      "displayName": "DIMM 1",
      "manufacturer": "Unknown",
      "model": "DDR4",
      "partNumber": "HMA451R7MFR8N-TFTD ",
      "serialNumber": "103D4F44",
      "slot": 1,
      "speed": 2133,
      "type": "DDR4"
    }],
    "memorySlots": 0,
    "mgmtProcIPaddress": "10.243.6.69",
    "model": "45Z",
    "name": "DaAn5",
    "nist": {
      "currentValue": "Compatibility",
      "possibleValues": ["Compatibility",
        "Nist_800_131A_Strict"
      ]
    },
    "onboardPciDevices": [{
      "firmware": [{
        "build": "0",
        "classifications": [0],
        "date": "",
        "name": "PCIFirmware",
        "revision": "0",
        "role": "Primary",
        "softwareID": "1014:405",
        "status": "Active",
        "type": "",
        "version": ""
      }],
      "fodUniqueID": "",
      "isAddOnCard": false,
      "isAgentless": false,
      "name": "",
      "pciBusNumber": "25",
      "pciDeviceNumber": "0",
      "pciFunctionNumber": "0",
      "pciRevision": "1",
      "pciSubID": "405",
      "pciSubVendorID": "1014",
      "portInfo": {

      },
      "posID": "534",
      "vpdID": "102b"
    }, {
      "firmware": [{
        "build": "0",
        "classifications": [33024],
        "date": "",
        "name": "17.0.4.4a",
        "revision": "0",
        "role": "Primary",
        "softwareID": "101404D1",
        "status": "Active",
        "type": "VPD-V0",
        "version": "17.0.4.4a"
      }],
      "fodUniqueID": "11SBCM957190123456789",
      "isAddOnCard": false,
      "isAgentless": true,
      "name": "Broadcom NetXtreme Gigabit Ethernet Controller",
      "pciBusNumber": "27",
      "pciDeviceNumber": "0",
      "pciFunctionNumber": "3",
      "pciRevision": "1",
      "pciSubID": "4d1",
      "pciSubVendorID": "1014",
      "portInfo": {
        "logicalPorts": [{
          "addresses": "40F2E9B81583",
          "portNumber": 1,
          "portType": "ETHERNET",
          "vnicMode": false
        }],
        "peerBay": 0,
        "portNumber": 4,
        "portType": "ETHERNET"
      },
      "posID": "1657",
      "vpdID": "14e4"
    }],
    "overallHealthState": "Normal",
    "partNumber": "00KC903",
    "partitionID": -1,
    "pciCapabilities": ["Raid Link",
      "OOB PCIe",
      "Raid Link Config",
      "Raid Link Alert",
      "OOB PCIe Config"
    ],
    "pciDevices": [{
      "FRU": "N/A",
      "firmware": [{
        "build": "0",
        "classifications": [13],
        "date": "2015-04-06T00:00:00Z",
        "name": "LSI MegaRAID Controller Firmware",
        "revision": "0",
        "role": "Primary",
        "softwareID": "10140454",
        "status": "Active",
        "type": "Software Bundle",
        "version": "24.7.0-0052"
      }],
      "fodUniqueID": "N/A",
      "fruSerialNumber": "SV42100396",
      "isAddOnCard": true,
      "isAgentless": true,
      "manufacturer": "IBM",
      "name": "ServeRAID M5210",
      "partNumber": "N/A",
      "pciBusNumber": "1",
      "pciDeviceNumber": "0",
      "pciFunctionNumber": "0",
      "pciRevision": "2",
      "pciSubID": "454",
      "pciSubVendorID": "1014",
      "portInfo": {

      },
      "posID": "5d",
      "productName": "ServeRAID M5210",
      "slotName": "SlotDesig4_Slot 4",
      "slotNumber": "4",
      "slotSupportsHotPlug": "false",
      "vpdID": "1000"
    }, {
      "firmware": [{
        "build": "0",
        "classifications": [33024],
        "date": "",
        "name": "17.0.4.4a",
        "revision": "0",
        "role": "Primary",
        "softwareID": "101404D1",
        "status": "Active",
        "type": "VPD-V0",
        "version": "17.0.4.4a"
      }],
      "fodUniqueID": "11SBCM957190123456789",
      "isAddOnCard": false,
      "isAgentless": true,
      "name": "Broadcom NetXtreme Gigabit Ethernet Controller",
      "pciBusNumber": "27",
      "pciDeviceNumber": "0",
      "pciFunctionNumber": "3",
      "pciRevision": "1",
      "pciSubID": "4d1",
      "pciSubVendorID": "1014",
      "portInfo": {
        "logicalPorts": [{
          "addresses": "40F2E9B81583",
          "portNumber": 1,
          "portType": "ETHERNET",
          "vnicMode": false
        }],
        "peerBay": 0,
        "portNumber": 4,
        "portType": "ETHERNET"
      },
      "posID": "1657",
      "vpdID": "14e4"
    }],
    "ports": [{
      "ioModuleBay": 0,
      "portNumber": 1
    }, {
      "ioModuleBay": 0,
      "portNumber": 2
    }, {
      "ioModuleBay": 0,
      "portNumber": 3
    }, {
      "ioModuleBay": 0,
      "portNumber": 4
    }],
    "posID": "",
    "powerAllocation": {
      "maximumAllocatedPower": 660,
      "minimumAllocatedPower": 26
    },
    "powerCappingPolicy": {
      "cappingACorDCMode": "DC",
      "cappingPolicy": "OFF",
      "currentPowerCap": 0,
      "maxPowerCap": 319000,
      "maximumPowerCappingHotPlugLevel": 367000,
      "minPowerCap": 85300,
      "minimumHardCapLevel": 246200,
      "minimumPowerCappingHotPlugLevel": 268000,
      "powerCappingAllocUnit": "watts*10^-3"
    },
    "powerStatus": 5,
    "powerSupplies": [{
      "FRU": "",
      "cmmDisplayName": "Power Supply 1",
      "dataHandle": 0,
      "description": "",
      "firmware": [],
      "fruSerialNumber": "",
      "hardwareRevision": "",
      "healthState": "CRITICAL",
      "inputVoltageIsAC": true,
      "inputVoltageMax": -1,
      "inputVoltageMin": -1,
      "leds": [],
      "machineType": "",
      "manufactureDate": "",
      "manufacturer": "EMER",
      "manufacturerId": "",
      "model": "",
      "name": "Power Supply 1",
      "partNumber": "94Y8136",
      "posID": "",
      "powerAllocation": {
        "totalInputPower": 0,
        "totalOutputPower": 550000
      },
      "powerState": "Unknown",
      "productId": "",
      "productName": "",
      "serialNumber": "K118146600A",
      "slots": [1],
      "type": "PowerSupply",
      "uri": "powerSupply/",
      "userDescription": "",
      "uuid": "",
      "vpdID": ""
    }, {
      "FRU": "",
      "cmmDisplayName": "Power Supply 2",
      "dataHandle": 0,
      "description": "",
      "firmware": [],
      "fruSerialNumber": "",
      "hardwareRevision": "",
      "healthState": "CRITICAL",
      "inputVoltageIsAC": true,
      "inputVoltageMax": -1,
      "inputVoltageMin": -1,
      "leds": [],
      "machineType": "",
      "manufactureDate": "",
      "manufacturer": "EMER",
      "manufacturerId": "",
      "model": "",
      "name": "Power Supply 2",
      "partNumber": "94Y8136",
      "posID": "",
      "powerAllocation": {
        "totalInputPower": 0,
        "totalOutputPower": 550000
      },
      "powerState": "Unknown",
      "productId": "",
      "productName": "",
      "serialNumber": "K1181466087",
      "slots": [2],
      "type": "PowerSupply",
      "uri": "powerSupply/",
      "userDescription": "",
      "uuid": "",
      "vpdID": ""
    }],
    "processorSlots": 0,
    "processors": [{
      "cores": 10,
      "displayName": "Intel(R) Xeon(R) CPU E5-2650 v3 @ 2.30GHz",
      "family": "INTEL_R_XEON_TM",
      "manufacturer": "Intel(R) Corporation",
      "productVersion": "Intel(R) Xeon(R) CPU E5-2650 v3 @ 2.30GHz",
      "slot": 1,
      "speed": 2.2999999999999998
    }],
    "productId": "4D4F00",
    "productName": "Lenovo System x3550 M5",
    "raidSettings": [{
      "description": "ServeRAID M5210",
      "diskDrives": [{
        "FRU": "42D0631",
        "bay": 0,
        "blockSize": 512,
        "description": "AL13SEB300",
        "diskState": "System",
        "healthState": "Normal",
        "interfaceType": "SAS",
        "manufacturer": "IBM-ESXS",
        "mediaType": "Rotational",
        "model": "AL13SEB300",
        "name": "Disk 0_0",
        "numberOfBlocks": 585937500,
        "partNumber": "42D0628",
        "serialNumber": "44P012H5",
        "uuid": ""
      }, {
        "FRU": "81Y3810",
        "bay": 1,
        "blockSize": 512,
        "description": "ST9300653SS",
        "diskState": "System",
        "healthState": "Normal",
        "interfaceType": "SAS",
        "manufacturer": "IBM-ESXS",
        "mediaType": "Rotational",
        "model": "ST9300653SS",
        "name": "Disk 2_2",
        "numberOfBlocks": 585937500,
        "partNumber": "81Y9667",
        "serialNumber": "6XN3J9M9",
        "uuid": ""
      }],
      "firmware": [{
        "build": "0",
        "classifications": [],
        "date": "2015-04-06T00:00:00Z",
        "name": "LSI MegaRAID Controller Firmware",
        "revision": "0",
        "role": "Primary",
        "softwareID": "10140454",
        "status": "Active",
        "type": "",
        "version": "24.7.0-0052"
      }],
      "name": "ServeRAID M5210",
      "uuid": "0000000000000000500605B008E48280"
    }],
    "secureBootMode": {
      "currentValue": "Disabled",
      "possibleValues": ["Disabled",
        "Enabled"
      ]
    },
    "serialNumber": "KVD0153",
    "slots": [1],
    "status": {
      "message": "managed",
      "name": "MANAGED"
    },
    "subSlots": [],
    "subType": "",
    "tlsVersion": {
      "currentValue": "TLS_10",
      "possibleValues": ["TLS_10",
        "TLS_11",
        "TLS_12"
      ]
    },
    "type": "Rack-Tower Server",
    "uri": "node/425AF828DF7D11D4B0F8E76767BBBBBB",
    "userDescription": "",
    "uuid": "425AF828DF7D11D4B0F8E76767BBBBBB",
    "vnicMode": "disabled",
    "vpdID": ""
  }, {
    "accessState": "Online",
    "activationKeys": [],
    "addinCards": [],
    "addinCardSlots": 0,
    "arch": "x86_64",
    "backedBy": "real",
    "bladeState": 0,
    "bootMode": {
      "possibleValues": ["Legacy Only",
        "UEFI and Legacy",
        "UEFI Only"
      ],
      "currentValue": "UEFI and Legacy"
    },
    "bootOrder": {
      "bootOrderList": [{
        "bootType": "SingleUse",
        "currentBootOrderDevices": ["None"],
        "possibleBootOrderDevices": ["Boot To F1",
          "CD/DVD Rom",
          "Diagnostics",
          "Floppy Disk",
          "Hard Disk 0",
          "Hypervisor",
          "None",
          "PXE Network"
        ]
      }],
      "uri": "node/00DD973D1C2CE511B19E3C18A000F4F0/bootOrder"
    },
    "cmmDisplayName": "",
    "cmmHealthState": "Warning",
    "complexID": -1,
    "contact": "",
    "dataHandle": 0,
    "description": "cmms RD650",
    "domainName": "lenovo.com",
    "driveBays": 2,
    "drives": [{
      "bay": 0,
      "capacity": 953,
      "interfaceType": "SATA",
      "mediaType": "HDD",
      "speed": "6.0 Gb/s",
      "state": "stopped",
      "raidPresence": "Regular"
    }, {
      "bay": 1,
      "capacity": 953,
      "interfaceType": "SATA",
      "mediaType": "HDD",
      "raidPresence": "Regular",
      "speed": "6.0 Gb/s",
      "state": "stopped"
    }],
    "embeddedHypervisorPresence": false,
    "errorFields": [],
    "excludedHealthState": "Warning",
    "expansionCards": [],
    "expansionCardSlots": 0,
    "expansionProducts": [],
    "expansionProductType": "",
    "fans": [],
    "firmware": [{
      "build": "",
      "date": "",
      "name": "BIOS",
      "role": "PRIMARY",
      "status": "ACTIVE",
      "type": "BIOS",
      "version": "PB2TS154"
    }, {
      "build": "",
      "date": "",
      "name": "Windows Driver Bundle",
      "role": "",
      "status": "ACTIVE",
      "type": "Windows Driver Bundle",
      "version": "1.02.0004"
    }],
    "flashStorage": [],
    "FRU": "",
    "fruSerialNumber": "8SSB20A05917R2SH54D005X",
    "hasOS": false,
    "height": 2,
    "hostMacAddresses": "",
    "hostname": "blah",
    "ipInterfaces": [],
    "ipv4Addresses": ["10.35.106.142"],
    "ipv6Addresses": [""],
    "isConnectionTrusted": "true",
    "isITME": false,
    "isRemotePresenceEnabled": true,
    "isScalable": false,
    "lanOverUsb": "disabled",
    "leds": [{
      "conditions": "Fault",
      "color": "Red",
      "location": "FrontPanel",
      "name": "Fault",
      "state": "Off"
    }, {
      "conditions": "Fault",
      "color": "Red",
      "location": "PSU",
      "name": "PSU1 FAULT",
      "state": "Off"
    }],
    "location": {
      "location": "",
      "lowestRackUnit": 0,
      "rack": "",
      "room": ""
    },
    "macAddress": "00:8C:FA:E7:E8:D0,00:8C:FA:E7:E8:D1",
    "machineType": "RD650",
    "manufacturer": "LENOVO",
    "manufacturerId": "",
    "memoryModules": [{
      "capacity": 8,
      "displayName": "DIMM 1",
      "manufacturer": "Micron Technology",
      "model": "",
      "partNumber": "18ASF1G72PZ-2G1A2",
      "serialNumber": "da90356",
      "slot": 1,
      "speed": 1866,
      "type": "RDIMM",
      "voltage": "1.2V"
    }],
    "memorySlots": 0,
    "mgmtProcIPaddress": "",
    "model": "70DR000SUX",
    "name": "blah",
    "nist": {
      "currentValue": "Nist_800_131A_Strict",
      "possibleValues": ["Compatibility",
        "Nist_800_131A_Custom",
        "Nist_800_131A_Strict"
      ]
    },
    "onboardPciDevices": [{
      "fodUniqueID": "",
      "isAddOnCard": false,
      "isAgentless": false,
      "name": "",
      "pciBusNumber": "4",
      "pciDeviceNumber": "0",
      "pciRevision": "0",
      "pciSubID": "1051",
      "pciSubVendorID": "17aa",
      "pciFunctionNumber": "0",
      "portInfo": {

      },
      "posID": "73",
      "vpdID": "1000"
    }],
    "overallHealthState": "Warning",
    "partitionID": -1,
    "partNumber": "",
    "pciCapabilities": [],
    "pciDevices": [{
      "fodUniqueID": "",
      "isAddOnCard": false,
      "isAgentless": false,
      "name": "",
      "pciBusNumber": "4",
      "pciFunctionNumber": "0",
      "pciRevision": "0",
      "pciSubID": "1051",
      "pciSubVendorID": "17aa",
      "pciDeviceNumber": "0",
      "portInfo": {

      },
      "posID": "73",
      "vpdID": "1000"
    }],
    "ports": [],
    "posID": "",
    "powerAllocation": {
      "maximumAllocatedPower": 0,
      "minimumAllocatedPower": 0
    },
    "powerCappingPolicy": {
      "cappingACorDCMode": "UNKNOWN",
      "cappingPolicy": "UNKNOWN",
      "currentPowerCap": 0,
      "maxPowerCap": -1,
      "maximumPowerCappingHotPlugLevel": -1,
      "minimumHardCapLevel": -1,
      "minPowerCap": -1,
      "minimumPowerCappingHotPlugLevel": -1,
      "powerCappingAllocUnit": "watts"

    },
    "powerStatus": 8,
    "powerSupplies": [{
      "cmmDisplayName": null,
      "dataHandle": 0,
      "description": "Power Supply 1",
      "firmware": [],
      "FRU": null,
      "fruSerialNumber": null,
      "hardwareRevision": "01F",
      "healthState": "GOOD",
      "inputVoltageIsAC": false,
      "inputVoltageMax": 0,
      "inputVoltageMin": 0,
      "leds": [{
        "color": "Green",
        "location": "FRU",
        "name": "IN",
        "state": "On"
      }, {
        "color": "Amber",
        "location": "FRU",
        "name": "FAULT",
        "state": "Off"
      }],
      "machineType": null,
      "manufactureDate": "Feb 5, 2015",
      "manufacturer": null,
      "manufacturerId": "DELTA",
      "model": "DPS-1100EB A",
      "name": "0F33323D1DG525001X",
      "partNumber": null,
      "posID": null,
      "powerAllocation": {
        "totalInputPower": 0,
        "totalOutputPower": 0
      },
      "powerState": null,
      "productId": null,
      "productName": null,
      "serialNumber": "0F33323D1DG525001X",
      "slots": [0],
      "type": "PowerSupply",
      "uri": "powerSupply/null",
      "userDescription": null,
      "uuid": null,
      "vpdID": null
    }],
    "processors": [{
      "cores": 8,
      "displayName": "",
      "family": "Intel Nehalem Family",
      "manufacturer": "GenuineIntel",
      "productVersion": "Haswell Server Model",
      "slot": 1,
      "speed": 3.4
    }],
    "processorSlots": 0,
    "productId": "",
    "productName": "RD650",
    "raidSettings": [],
    "secureBootMode": {
      "currentValue": "",
      "possibleValues": []
    },
    "serialNumber": "MJ02SC2F",
    "slots": [1],
    "status": {
      "message": "managed",
      "name": "MANAGED"
    },
    "subType": "",
    "subSlots": [],
    "thinkServerFru": [{
      "deviceName": "12GBP 8xS",
      "description": "BackPlane1 FRU",
      "manufatucturer": "LENOVO",
      "manufatucturerDate": "Dec 24, 2014",
      "partNumber": "SSF0A47711",
      "serial": "8SSSF0A47711V1SH4CR0079"
    }, {
      "deviceName": "Riser2U 3x8",
      "description": "Riser1 FRU",
      "manufatucturer": "LENOVO",
      "manufatucturerDate": "Dec 15, 2014",
      "partNumber": "SC50A06667",
      "serial": "8SSC50A06667V1SH4CE00JW"
    }],
    "tlsVersion": {
      "currentValue": "Unknown",
      "possibleValues": ["TLS_10",
        "TLS_11",
        "TLS_12"
      ]
    },
    "type": "Lenovo ThinkServer",
    "uri": "node/00DD973D1C2CE511B19E3C18A000F4F0",
    "userDescription": "",
    "uuid": "00DD973D1C2CE511B19E3C18A000F4F0",
    "vnicMode": "disabled",
    "vpdID": ""
  }]
  }
+ Response 400
+ Response 401
+ Response 404
+ Response 409
+ Response 500
