FORMAT: 1A

# XClarity Nodes

# GET /scalable_complexes

+ Response 200 (application/json)
{
   "complexID": "C29379AA380E11E39DF3000AF7256714",
   "location": {
      "location": "here",
      "lowestRackUnit": 35,
      "rack": "ZD123",
      "room": "here"
   },
   "nodeCount": 1,
   "orphanNodes": [],
  "partition": [],
   "partitionCount": 1,
   "uuid": "C29379AA380E11E39DF3000AF7256714"
}

+ Response 400
+ Response 401
+ Response 404
+ Response 409
+ Response 500
