FORMAT: 1A

# Lenovo XClarity Management Console API

# POST /sessions

+ Response 200 (application/json)

  {
    "response": {
      "pwChangeRequired": false
    },
    "result":"success",
    "messages" : [ 
      {
        "id": "FQHMSE",
        "text": "The request completed successfully.",
        "explanation": "",
        "recovery": {
          "text": "Information only. No action is required.",
          "URL":""
        }
      }
    ]
  }  
