FORMAT: 1A

#XClarity Update Repositories

# GET /updateRepositories/firmware?key=supportedMts

+ Response 200 (application/json)
{
        "supportedMts": [{
                "comp": "[]",
                "category": "rackswitch",
                "displayType": "7159",
                "name": "Lenovo RackSwitch G8124E",
                "inventoryMT": "false",
                "type": "7159BF7,7159BR6,7159HC9,7159PAG,7159PAH,7159HC7",
                "supportDownload": "false"
        }, {
                "comp": "[]",
                "category": "server",
                "displayType": "7X21",
                "name": "Lenovo Thinksystem SD530 Server",
                "inventoryMT": "false",
                "type": "7X21",
                "supportDownload": "true"
        }, {
                "comp": "[]",
                "category": "server",
                "displayType": "8738",
                "name": "IBM Flex System x240 Compute Node",
                "inventoryMT": "false",
                "type": "8738",
                "supportDownload": "true"
        }, {
                "comp": "[]",
                "category": "server",
                "displayType": "7167",
                "name": "Lenovo Flex System x440 Compute Node",
                "inventoryMT": "false",
                "type": "7167",
                "supportDownload": "true"
        }, {
                "comp": "[]",
                "category": "chassis",
                "displayType": "7893",
                "name": "Lenovo Flex Chassis Management Module II",
                "inventoryMT": "false",
                "type": "7893_1AON",
                "supportDownload": "true"
        }, {
                "comp": "[]",
                "category": "chassis",
                "displayType": "7893",
                "name": "IBM Flex Chassis Management Module",
                "inventoryMT": "false",
                "type": "7893_2PET",
                "supportDownload": "true"
        }, {
                "comp": "[]",
                "category": "server",
                "displayType": "8737",
                "name": "IBM Flex System x240 Compute Node",
                "inventoryMT": "false",
                "type": "8737",
                "supportDownload": "true"
        }, {
                "comp": "[]",
                "category": "server",
                "displayType": "7162",
                "name": "Lenovo Flex System x240 Compute Node",
                "inventoryMT": "true",
                "type": "7162",
                "supportDownload": "true"
        }, {
                "comp": "[]",
                "category": "rackswitch",
                "displayType": "7159",
                "name": "Lenovo RackSwitch G8264",
                "inventoryMT": "false",
                "type": "715964F,7159G64,7159HC3,7159HC4,7159PAJ,7159PAK",
                "supportDownload": "false"
        }, {
                "comp": "[]",
                "category": "server",
                "displayType": "8871",
                "name": "Lenovo System x3650 M5",
                "inventoryMT": "false",
                "type": "8871",
                "supportDownload": "true"
        }, {
                "comp": "[]",
                "category": "switch",
                "displayType": "0x0130-0x0017",
                "name": "IBM Flex System Fabric EN4093 10Gb Scalable Switch",
                "inventoryMT": "true",
                "type": "0x0130-0x0017",
                "supportDownload": "true"
        }, {
                "comp": "[]",
                "category": "switch",
                "displayType": "0x0130-0x001A",
                "name": "IBM Flex System EN4091 10Gb Ethernet Passthru",
                "inventoryMT": "false",
                "type": "0x0130-0x001A",
                "supportDownload": "true"
        }, {
                "comp": "[]",
                "category": "rackswitch",
                "displayType": "7159",
                "name": "Lenovo RackSwitch G7052",
                "inventoryMT": "false",
                "type": "7159CAX,7159HCT",
                "supportDownload": "false"
        }, {
                "comp": "[]",
                "category": "storage",
                "displayType": "6411",
                "name": "Lenovo Storage S2200\/S3200",
                "inventoryMT": "false",
                "type": "6411",
                "supportDownload": "false"
        }, {
                "comp": "[]",
                "category": "chassis",
                "displayType": "8724",
                "name": "IBM Flex Chassis Management Module",
                "inventoryMT": "false",
                "type": "8724_2PET",
                "supportDownload": "true"
        }, {
                "comp": "[]",
                "category": "chassis",
                "displayType": "8724",
                "name": "Lenovo Flex Chassis Management Module II",
                "inventoryMT": "false",
                "type": "8724_1AON",
                "supportDownload": "true"
        }, {
                "comp": "[]",
                "category": "server",
                "displayType": "8869",
                "name": "Lenovo System x3550 M5",
                "inventoryMT": "false",
                "type": "8869",
                "supportDownload": "true"
        }, {
                "comp": "[]",
                "category": "switch",
                "displayType": "0x0130-0x0119",
                "name": "IBM Flex EN2092 1Gb Ethernet Scalable Switch",
                "inventoryMT": "false",
                "type": "0x0130-0x0119",
                "supportDownload": "true"
        }, {
                "comp": "[]",
                "category": "switch",
                "displayType": "0x0130-0x0029",
                "name": "Lenovo Flex System Fabric SI4093 System Interconnect Module",
                "inventoryMT": "false",
                "type": "0x0130-0x0029",
                "supportDownload": "true"
        }, {
                "comp": "[]",
                "category": "switch",
                "displayType": "0x0130-0x0028",
                "name": "Lenovo Flex System Fabric EN4093R 10Gb Scalable Switch",
                "inventoryMT": "false",
                "type": "0x0130-0x0028",
                "supportDownload": "true"
        }, {
                "comp": "[]",
                "category": "switch",
                "displayType": "0x0130-0x0027",
                "name": "Lenovo Flex System Fabric CN4093 10Gb Converged Scalable Switch",
                "inventoryMT": "false",
                "type": "0x0130-0x0027",
                "supportDownload": "true"
        }, {
                "comp": "[]",
                "category": "switch",
                "displayType": "0x0130-0x0026",
                "name": "Lenovo Flex System SI4091 10Gb System Interconnect Module",
                "inventoryMT": "false",
                "type": "0x0130-0x0026",
                "supportDownload": "true"
        }, {
                "comp": "[]",
                "category": "switch",
                "displayType": "0x0130-0x0024",
                "name": "IBM Flex System Fabric SI4093 System Interconnect Module",
                "inventoryMT": "false",
                "type": "0x0130-0x0024",
                "supportDownload": "true"
        }, {
                "comp": "[]",
                "category": "switch",
                "displayType": "0x0130-0x0023",
                "name": "IBM Flex System EN4023 10Gb Scalable Switch",
                "inventoryMT": "false",
                "type": "0x0130-0x0023",
                "supportDownload": "true"
        }, {
                "comp": "[]",
                "category": "switch",
                "displayType": "0x0135-0x0011",
                "name": "IBM Flex System FC5022 16Gb SAN Scalable Switch",
                "inventoryMT": "false",
                "type": "0x0135-0x0011",
                "supportDownload": "true"
        }, {
                "comp": "[]",
                "category": "switch",
                "displayType": "0x0135-0x0010",
                "name": "IBM Flex System FC3171 8Gb SAN Switch and SAN Pass-thru",
                "inventoryMT": "false",
                "type": "0x0135-0x0010",
                "supportDownload": "true"
        }, {
                "comp": "[]",
                "category": "rackswitch",
                "displayType": "7159",
                "name": "Lenovo RackSwitch G8052",
                "inventoryMT": "false",
                "type": "7159G52_standalone,715952F_standalone,7159HC1_standalone,7159HC2_standalone,7159PAC_standalone,7159PAD_standalone",
                "supportDownload": "false"
        }, {
                "comp": "[]",
                "category": "rackswitch",
                "displayType": "7159",
                "name": "Lenovo RackSwitch G8052RS",
                "inventoryMT": "false",
                "type": "7159G52_stacked,715952F_stacked,7159HC1_stacked,7159HC2_stacked,7159PAC_stacked,7159PAD_stacked",
                "supportDownload": "false"
        }, {
                "comp": "[]",
                "category": "switch",
                "displayType": "0x0130-0x001B",
                "name": "IBM Flex System Fabric CN4093 10Gb Converged Scalable Switch",
                "inventoryMT": "false",
                "type": "0x0130-0x001B",
                "supportDownload": "true"
        }, {
                "comp": "[]",
                "category": "switch",
                "displayType": "0x0130-0x001C",
                "name": "IBM Flex System EN6131 40Gb Ethernet Switch",
                "inventoryMT": "false",
                "type": "0x0130-0x001C",
                "supportDownload": "true"
        }, {
                "comp": "[]",
                "category": "switch",
                "displayType": "0x0130-0x0021",
                "name": "IBM Flex System Fabric EN4093R 10Gb Scalable Switch",
                "inventoryMT": "false",
                "type": "0x0130-0x0021",
                "supportDownload": "true"
        }, {
                "comp": "[]",
                "category": "server",
                "displayType": "3943",
                "name": "Lenovo System x3250 M6",
                "inventoryMT": "false",
                "type": "3943",
                "supportDownload": "true"
        }, {
                "comp": "[]",
                "category": "rackswitch",
                "displayType": "7309",
                "name": "IBM RackSwitch G8264",
                "inventoryMT": "false",
                "type": "7309G64,7309HC3,7309HC4,730964F,7309PAK,7309PAJ",
                "supportDownload": "false"
        }, {
                "comp": "[]",
                "category": "server",
                "displayType": "8956",
                "name": "IBM Flex System x240 Compute Node",
                "inventoryMT": "false",
                "type": "8956",
                "supportDownload": "true"
        }, {
                "comp": "[]",
                "category": "server",
                "displayType": "2590",
                "name": "Lenovo Flex System x440 Compute Node",
                "inventoryMT": "false",
                "type": "2590",
                "supportDownload": "true"
        }, {
                "comp": "[]",
                "category": "server",
                "displayType": "2591",
                "name": "Lenovo Flex System x240 M5 Compute Node",
                "inventoryMT": "false",
                "type": "2591",
                "supportDownload": "true"
        }, {
                "comp": "[]",
                "category": "server",
                "displayType": "7916",
                "name": "IBM Flex System x222 Compute Node",
                "inventoryMT": "false",
                "type": "7916",
                "supportDownload": "true"
        }, {
                "comp": "[]",
                "category": "server",
                "displayType": "2585",
                "name": "IBM Flex System x220 Compute Node",
                "inventoryMT": "false",
                "type": "2585",
                "supportDownload": "true"
        }, {
                "comp": "[]",
                "category": "rackswitch",
                "displayType": "1455",
                "name": "IBM RackSwitch G8052",
                "inventoryMT": "false",
                "type": "145548E",
                "supportDownload": "false"
        }, {
                "comp": "[]",
                "category": "server",
                "displayType": "2588",
                "name": "Lenovo Flex System x240 Compute Node",
                "inventoryMT": "false",
                "type": "2588",
                "supportDownload": "true"
        }, {
                "comp": "[]",
                "category": "rackswitch",
                "displayType": "7120",
                "name": "IBM RackSwitch G8264",
                "inventoryMT": "false",
                "type": "712064C",
                "supportDownload": "false"
        }, {
                "comp": "[]",
                "category": "server",
                "displayType": "7196",
                "name": "Lenovo Flex System x280\/x480\/x880 X6 Compute Node",
                "inventoryMT": "false",
                "type": "7196",
                "supportDownload": "true"
        }, {
                "comp": "[]",
                "category": "server",
                "displayType": "7917",
                "name": "IBM Flex System x440 Compute Node",
                "inventoryMT": "false",
                "type": "7917",
                "supportDownload": "true"
        }, {
                "comp": "[]",
                "category": "server",
                "displayType": "5128",
                "name": "Lenovo Storage DX8200N",
                "inventoryMT": "false",
                "type": "5128",
                "supportDownload": "true"
        }, {
                "comp": "[]",
                "category": "server",
                "displayType": "7906",
                "name": "IBM Flex System x220 Compute Node",
                "inventoryMT": "false",
                "type": "7906",
                "supportDownload": "true"
        }, {
                "comp": "[]",
                "category": "rackswitch",
                "displayType": "7120",
                "name": "IBM RackSwitch G8052",
                "inventoryMT": "false",
                "type": "712048E",
                "supportDownload": "false"
        }, {
                "comp": "[]",
                "category": "server",
                "displayType": "3633",
                "name": "Lenovo System x3250 M6",
                "inventoryMT": "false",
                "type": "3633",
                "supportDownload": "true"
        }, {
                "comp": "[]",
                "category": "server",
                "displayType": "5135",
                "name": "Lenovo Storage DX8200D",
                "inventoryMT": "false",
                "type": "5135",
                "supportDownload": "true"
        }, {
                "comp": "[]",
                "category": "server",
                "displayType": "7903",
                "name": "IBM Flex System x280\/x480\/x880 X6 Compute Node",
                "inventoryMT": "false",
                "type": "7903",
                "supportDownload": "true"
        }, {
                "comp": "[]",
                "category": "rackswitch",
                "displayType": "7309",
                "name": "IBM RackSwitch G8052",
                "inventoryMT": "false",
                "type": "7309G52,7309HC1,7309HC2,730952F,7309PAC,7309PAD",
                "supportDownload": "false"
        }, {
                "comp": "[]",
                "category": "rackswitch",
                "displayType": "7159",
                "name": "Lenovo Flex System Interconnect Fabric",
                "inventoryMT": "false",
                "type": "7159DRX_stacked,7159DFX_stacked,7159HCK_stacked,7159HCM_stacked",
                "supportDownload": "false"
        }, {
                "comp": "[]",
                "category": "rackswitch",
                "displayType": "7159",
                "name": "Lenovo RackSwitch G8264CS",
                "inventoryMT": "false",
                "type": "7159DRX_standalone,7159DFX_standalone,7159HCK_standalone,7159HCM_standalone",
                "supportDownload": "false"
        }, {
                "comp": "[]",
                "category": "server",
                "displayType": "4258",
                "name": "Lenovo Flex System x280\/x480\/x880 X6 Compute Node",
                "inventoryMT": "false",
                "type": "4258",
                "supportDownload": "true"
        }, {
                "comp": "[]",
                "category": "server",
                "displayType": "4259",
                "name": "IBM Flex System x280\/x480\/x880 X6 Compute Node",
                "inventoryMT": "false",
                "type": "4259",
                "supportDownload": "true"
        }, {
                "comp": "[]",
                "category": "switch",
                "displayType": "0x0138-0x0006",
                "name": "IBM Flex System IB6131 40Gb Infiniband Switch",
                "inventoryMT": "false",
                "type": "0x0138-0x0006",
                "supportDownload": "true"
        }, {
                "comp": "[]",
                "category": "server",
                "displayType": "5120",
                "name": "Lenovo Storage DX8200C",
                "inventoryMT": "false",
                "type": "5120",
                "supportDownload": "true"
        }, {
                "comp": "[]",
                "category": "chassis",
                "displayType": "7385",
                "name": "Lenovo Flex Telco Chassis Management Module II",
                "inventoryMT": "false",
                "type": "7385",
                "supportDownload": "true"
        }, {
                "comp": "[]",
                "category": "server",
                "displayType": "8693",
                "name": "Lenovo Converged HX Series",
                "inventoryMT": "false",
                "type": "8693",
                "supportDownload": "true"
        }, {
                "comp": "[]",
                "category": "server",
                "displayType": "8695",
                "name": "Lenovo Converged HX Series",
                "inventoryMT": "false",
                "type": "8695",
                "supportDownload": "true"
        }, {
                "comp": "[]",
                "category": "server",
                "displayType": "9532",
                "name": "Lenovo Flex System x240 M5 Compute Node",
                "inventoryMT": "false",
                "type": "9532",
                "supportDownload": "true"
        }, {
                "comp": "[]",
                "category": "chassis",
                "displayType": "8721",
                "name": "Lenovo Flex Chassis Management Module II",
                "inventoryMT": "true",
                "type": "8721_1AON",
                "supportDownload": "true"
        }, {
                "comp": "[]",
                "category": "chassis",
                "displayType": "8721",
                "name": "IBM Flex Chassis Management Module",
                "inventoryMT": "false",
                "type": "8721_2PET",
                "supportDownload": "true"
        }, {
                "comp": "[]",
                "category": "server",
                "displayType": "6241",
                "name": "Lenovo System x3850 \/ x3950 X6",
                "inventoryMT": "false",
                "type": "6241",
                "supportDownload": "true"
        }, {
                "comp": "[]",
                "category": "rackswitch",
                "displayType": "7159",
                "name": "Lenovo RackSwitch G8332",
                "inventoryMT": "false",
                "type": "7159HDE,7159CFX,7159BFX,7159HCE,7159HC8,7159BRX",
                "supportDownload": "false"
        }, {
                "comp": "[]",
                "category": "server",
                "displayType": "5465",
                "name": "Lenovo NeXtScale nx360 M5",
                "inventoryMT": "false",
                "type": "5465",
                "supportDownload": "true"
        }, {
                "comp": "[]",
                "category": "server",
                "displayType": "7X01",
                "name": "Lenovo Thinksystem SR630 Server",
                "inventoryMT": "false",
                "type": "7X01",
                "supportDownload": "true"
        }, {
                "comp": "[]",
                "category": "server",
                "displayType": "5463",
                "name": "Lenovo System x3550 M5",
                "inventoryMT": "false",
                "type": "5463",
                "supportDownload": "true"
        }, {
                "comp": "[]",
                "category": "server",
                "displayType": "5464",
                "name": "Lenovo System x3500 M5",
                "inventoryMT": "false",
                "type": "5464",
                "supportDownload": "true"
        }, {
                "comp": "[]",
                "category": "server",
                "displayType": "7X02",
                "name": "Lenovo Thinksystem SR630 Server",
                "inventoryMT": "false",
                "type": "7X02",
                "supportDownload": "true"
        }, {
                "comp": "[]",
                "category": "server",
                "displayType": "7X03",
                "name": "Lenovo Thinksystem SR550 Server",
                "inventoryMT": "false",
                "type": "7X03",
                "supportDownload": "true"
        }, {
                "comp": "[]",
                "category": "server",
                "displayType": "7X04",
                "name": "Lenovo Thinksystem SR550 Server",
                "inventoryMT": "false",
                "type": "7X04",
                "supportDownload": "true"
        }, {
                "comp": "[]",
                "category": "server",
                "displayType": "5462",
                "name": "Lenovo System x3650 M5",
                "inventoryMT": "false",
                "type": "5462",
                "supportDownload": "true"
        }, {
                "comp": "[]",
                "category": "server",
                "displayType": "7X05",
                "name": "Lenovo Thinksystem SR650 Server",
                "inventoryMT": "false",
                "type": "7X05",
                "supportDownload": "true"
        }, {
                "comp": "[]",
                "category": "server",
                "displayType": "7X06",
                "name": "Lenovo Thinksystem SR650 Server",
                "inventoryMT": "false",
                "type": "7X06",
                "supportDownload": "true"
        }, {
                "comp": "[]",
                "category": "server",
                "displayType": "7X07",
                "name": "Lenovo Thinksystem SR530 Server",
                "inventoryMT": "false",
                "type": "7X07",
                "supportDownload": "true"
        }, {
                "comp": "[]",
                "category": "server",
                "displayType": "7X08",
                "name": "Lenovo Thinksystem SR530 Server",
                "inventoryMT": "false",
                "type": "7X08",
                "supportDownload": "true"
        }, {
                "comp": "[]",
                "category": "server",
                "displayType": "7X09",
                "name": "Lenovo Thinksystem ST550 Server",
                "inventoryMT": "false",
                "type": "7X09",
                "supportDownload": "true"
        }, {
                "comp": "[]",
                "category": "rackswitch",
                "displayType": "7159",
                "name": "Lenovo RackSwitch G7028",
                "inventoryMT": "false",
                "type": "7159BAX,7159HCP",
                "supportDownload": "false"
        }, {
                "comp": "[]",
                "category": "server",
                "displayType": "5467",
                "name": "Lenovo NeXtScale nx360 M5 DWC",
                "inventoryMT": "false",
                "type": "5467",
                "supportDownload": "true"
        }, {
                "comp": "[]",
                "category": "server",
                "displayType": "7X12",
                "name": "Lenovo Thinksystem SR950 Server",
                "inventoryMT": "false",
                "type": "7X12",
                "supportDownload": "true"
        }, {
                "comp": "[]",
                "category": "rackswitch",
                "displayType": "7159",
                "name": "Lenovo RackSwitch G8296",
                "inventoryMT": "false",
                "type": "7159GF5,7159GR6,7159HC5,7159HC6",
                "supportDownload": "false"
        }, {
                "comp": "[]",
                "category": "server",
                "displayType": "7X10",
                "name": "Lenovo Thinksystem ST550 Server",
                "inventoryMT": "false",
                "type": "7X10",
                "supportDownload": "true"
        }, {
                "comp": "[]",
                "category": "server",
                "displayType": "7X16",
                "name": "Lenovo Thinksystem SN550 Server",
                "inventoryMT": "false",
                "type": "7X16",
                "supportDownload": "true"
        }, {
                "comp": "[]",
                "category": "server",
                "displayType": "7X15",
                "name": "Lenovo Thinksystem SN850 Server",
                "inventoryMT": "false",
                "type": "7X15",
                "supportDownload": "true"
        }, {
                "comp": "[]",
                "category": "rackswitch",
                "displayType": "7159",
                "name": "Lenovo RackSwitch G8272",
                "inventoryMT": "false",
                "type": "7159CFV,7159HCV,7159HCW,7159CRW",
                "supportDownload": "false"
        }, {
                "comp": "[]",
                "category": "server",
                "displayType": "7X18",
                "name": "Lenovo Thinksystem SR850 Server",
                "inventoryMT": "false",
                "type": "7X18",
                "supportDownload": "true"
        }, {
                "comp": "[]",
                "category": "server",
                "displayType": "7X19",
                "name": "Lenovo Thinksystem SR850 Server",
                "inventoryMT": "false",
                "type": "7X19",
                "supportDownload": "true"
        }, {
                "comp": "[]",
                "category": "server",
                "displayType": "7863",
                "name": "IBM Flex System x240 Compute Node",
                "inventoryMT": "false",
                "type": "7863",
                "supportDownload": "true"
        }],
        "status": {
                "result": "informational",
                "messages": [{
                        "id": "FQXHMUP2500I",
                        "text": "Repository operation completed successfully."
                }]
        }
}

+ Response 400
+ Response 401
+ Response 404
+ Response 409
+ Response 500

# GET /updateRepositories/firmware?key=lastRefreshed

+ Response 200 (application/json)
{
        "status": {
                "result": "informational",
                "messages": [{
                        "id": "FQXHMUP2500I",
                        "text": "Repository operation completed successfully."
                }]
        },
        "lastRefreshed": "05-11-2017-08:35"
}

+ Response 400
+ Response 401
+ Response 404
+ Response 409
+ Response 500

# GET /updateRepositories/firmware?key=size

+ Response 200 (application/json)
{
        "status": {
                "result": "informational",
                "messages": [{
                        "id": "FQXHMUP2500I",
                        "text": "Repository operation completed successfully."
                }]
        },
        "size": {
                "freeSpace": 16106127360,
                "usedSpace": 0,
                "allotment": 16106127360,
                "highusage": "low"
        }
}

+ Response 400
+ Response 401
+ Response 404
+ Response 409
+ Response 500

# GET /updateRepositories/firmware?key=importDir

+ Response 200 (application/json)
{
        "status": {
                "result": "informational",
                "messages": [{
                        "id": "FQXHMUP2500I",
                        "text": "Repository operation completed successfully."
                }]
        },
        "importDir": "\/opt\/lenovo\/lxca\/data\/updates\/repository"
}

+ Response 400
+ Response 401
+ Response 404
+ Response 409
+ Response 500

# GET /updateRepositories/firmware?key=publicKeys

+ Response 200 (application/json)
{
        "status": {
                "result": "informational",
                "messages": [{
                        "id": "FQXHMUP2500I",
                        "text": "Repository operation completed successfully."
                }]
        },
        "publicKeys": []
}

+ Response 400
+ Response 401
+ Response 404
+ Response 409
+ Response 500

# GET /updateRepositories/firmware?key=updates

+ Response 200 (application/json)
{
        "updates": [],
        "status": {
                "result": "informational",
                "messages": [{
                        "id": "FQXHMUP2500I",
                        "text": "Repository operation completed successfully."
                }]
        }
}

+ Response 400
+ Response 401
+ Response 404
+ Response 409
+ Response 500

# GET /updateRepositories/firmware?key=updatesByMt

+ Response 200 (application/json)
{
        "updatesByMt": {
                "total": 0,
                "progress": 100,
                "updates": [],
                "downloadedsize": 1,
                "current": "",
                "state": "complete",
                "totalsize": 1,
                "downloadednum": 0,
                "jobid": -1
        },
        "status": {
                "result": "informational",
                "messages": [{
                        "id": "FQXHMUP2500I",
                        "text": "Repository operation completed successfully."
                }]
        }
}

+ Response 400
+ Response 401
+ Response 404
+ Response 409
+ Response 500

# GET /updateRepositories/firmware?key=updatesByMtByComp

+ Response 200 (application/json)
{
        "status": {
                "result": "informational",
                "messages": [{
                        "id": "FQXHMUP2500I",
                        "text": "Repository operation completed successfully."
                }]
        },
        "updatesByMtByComp": {
                "parameter": "MTS",
                "value": [{
                        "comp": "[]",
                        "category": "rackswitch",
                        "displayType": "7159",
                        "name": "Lenovo RackSwitch G8124E",
                        "inventoryMT": "false",
                        "type": "7159BF7,7159BR6,7159HC9,7159PAG,7159PAH,7159HC7",
                        "supportDownload": "false"
                }, {
                        "comp": "[]",
                        "category": "server",
                        "displayType": "7X21",
                        "name": "Lenovo Thinksystem SD530 Server",
                        "inventoryMT": "false",
                        "type": "7X21",
                        "supportDownload": "true"
                }, {
                        "comp": "[]",
                        "category": "server",
                        "displayType": "8738",
                        "name": "IBM Flex System x240 Compute Node",
                        "inventoryMT": "false",
                        "type": "8738",
                        "supportDownload": "true"
                }, {
                        "comp": "[]",
                        "category": "server",
                        "displayType": "7167",
                        "name": "Lenovo Flex System x440 Compute Node",
                        "inventoryMT": "false",
                        "type": "7167",
                        "supportDownload": "true"
                }, {
                        "comp": "[]",
                        "category": "chassis",
                        "displayType": "7893",
                        "name": "Flex Chassis Management Module",
                        "inventoryMT": "false",
                        "type": "7893",
                        "supportDownload": "true"
                }, {
                        "comp": "[]",
                        "category": "server",
                        "displayType": "8737",
                        "name": "IBM Flex System x240 Compute Node",
                        "inventoryMT": "false",
                        "type": "8737",
                        "supportDownload": "true"
                }, {
                        "comp": "[]",
                        "category": "server",
                        "displayType": "7162",
                        "name": "Lenovo Flex System x240 Compute Node",
                        "inventoryMT": "true",
                        "type": "7162",
                        "supportDownload": "true"
                }, {
                        "comp": "[]",
                        "category": "rackswitch",
                        "displayType": "7159",
                        "name": "Lenovo RackSwitch G8264",
                        "inventoryMT": "false",
                        "type": "715964F,7159G64,7159HC3,7159HC4,7159PAJ,7159PAK",
                        "supportDownload": "false"
                }, {
                        "comp": "[]",
                        "category": "server",
                        "displayType": "8871",
                        "name": "Lenovo System x3650 M5",
                        "inventoryMT": "false",
                        "type": "8871",
                        "supportDownload": "true"
                }, {
                        "comp": "[]",
                        "category": "switch",
                        "displayType": "0x0130-0x0017",
                        "name": "IBM Flex System Fabric EN4093 10Gb Scalable Switch",
                        "inventoryMT": "true",
                        "type": "0x0130-0x0017",
                        "supportDownload": "true"
                }, {
                        "comp": "[]",
                        "category": "switch",
                        "displayType": "0x0130-0x001A",
                        "name": "IBM Flex System EN4091 10Gb Ethernet Passthru",
                        "inventoryMT": "false",
                        "type": "0x0130-0x001A",
                        "supportDownload": "true"
                }, {
                        "comp": "[]",
                        "category": "rackswitch",
                        "displayType": "7159",
                        "name": "Lenovo RackSwitch G7052",
                        "inventoryMT": "false",
                        "type": "7159CAX,7159HCT",
                        "supportDownload": "false"
                }, {
                        "comp": "[]",
                        "category": "storage",
                        "displayType": "6411",
                        "name": "Lenovo Storage S2200\/S3200",
                        "inventoryMT": "false",
                        "type": "6411",
                        "supportDownload": "false"
                }, {
                        "comp": "[]",
                        "category": "chassis",
                        "displayType": "8724",
                        "name": "Flex Chassis Management Module",
                        "inventoryMT": "false",
                        "type": "8724",
                        "supportDownload": "true"
                }, {
                        "comp": "[]",
                        "category": "server",
                        "displayType": "8869",
                        "name": "Lenovo System x3550 M5",
                        "inventoryMT": "false",
                        "type": "8869",
                        "supportDownload": "true"
                }, {
                        "comp": "[]",
                        "category": "switch",
                        "displayType": "0x0130-0x0119",
                        "name": "IBM Flex EN2092 1Gb Ethernet Scalable Switch",
                        "inventoryMT": "false",
                        "type": "0x0130-0x0119",
                        "supportDownload": "true"
                }, {
                        "comp": "[]",
                        "category": "switch",
                        "displayType": "0x0130-0x0029",
                        "name": "Lenovo Flex System Fabric SI4093 System Interconnect Module",
                        "inventoryMT": "false",
                        "type": "0x0130-0x0029",
                        "supportDownload": "true"
                }, {
                        "comp": "[]",
                        "category": "switch",
                        "displayType": "0x0130-0x0028",
                        "name": "Lenovo Flex System Fabric EN4093R 10Gb Scalable Switch",
                        "inventoryMT": "false",
                        "type": "0x0130-0x0028",
                        "supportDownload": "true"
                }, {
                        "comp": "[]",
                        "category": "switch",
                        "displayType": "0x0130-0x0027",
                        "name": "Lenovo Flex System Fabric CN4093 10Gb Converged Scalable Switch",
                        "inventoryMT": "false",
                        "type": "0x0130-0x0027",
                        "supportDownload": "true"
                }, {
                        "comp": "[]",
                        "category": "switch",
                        "displayType": "0x0130-0x0026",
                        "name": "Lenovo Flex System SI4091 10Gb System Interconnect Module",
                        "inventoryMT": "false",
                        "type": "0x0130-0x0026",
                        "supportDownload": "true"
                }, {
                        "comp": "[]",
                        "category": "switch",
                        "displayType": "0x0130-0x0024",
                        "name": "IBM Flex System Fabric SI4093 System Interconnect Module",
                        "inventoryMT": "false",
                        "type": "0x0130-0x0024",
                        "supportDownload": "true"
                }, {
                        "comp": "[]",
                        "category": "switch",
                        "displayType": "0x0130-0x0023",
                        "name": "IBM Flex System EN4023 10Gb Scalable Switch",
                        "inventoryMT": "false",
                        "type": "0x0130-0x0023",
                        "supportDownload": "true"
                }, {
                        "comp": "[]",
                        "category": "switch",
                        "displayType": "0x0135-0x0011",
                        "name": "IBM Flex System FC5022 16Gb SAN Scalable Switch",
                        "inventoryMT": "false",
                        "type": "0x0135-0x0011",
                        "supportDownload": "true"
                }, {
                        "comp": "[]",
                        "category": "switch",
                        "displayType": "0x0135-0x0010",
                        "name": "IBM Flex System FC3171 8Gb SAN Switch and SAN Pass-thru",
                        "inventoryMT": "false",
                        "type": "0x0135-0x0010",
                        "supportDownload": "true"
                }, {
                        "comp": "[]",
                        "category": "rackswitch",
                        "displayType": "7159",
                        "name": "Lenovo RackSwitch G8052",
                        "inventoryMT": "false",
                        "type": "7159G52,715952F,7159HC1,7159HC2,7159PAC,7159PAD",
                        "supportDownload": "false"
                }, {
                        "comp": "[]",
                        "category": "switch",
                        "displayType": "0x0130-0x001B",
                        "name": "IBM Flex System Fabric CN4093 10Gb Converged Scalable Switch",
                        "inventoryMT": "false",
                        "type": "0x0130-0x001B",
                        "supportDownload": "true"
                }, {
                        "comp": "[]",
                        "category": "switch",
                        "displayType": "0x0130-0x001C",
                        "name": "IBM Flex System EN6131 40Gb Ethernet Switch",
                        "inventoryMT": "false",
                        "type": "0x0130-0x001C",
                        "supportDownload": "true"
                }, {
                        "comp": "[]",
                        "category": "switch",
                        "displayType": "0x0130-0x0021",
                        "name": "IBM Flex System Fabric EN4093R 10Gb Scalable Switch",
                        "inventoryMT": "false",
                        "type": "0x0130-0x0021",
                        "supportDownload": "true"
                }, {
                        "comp": "[]",
                        "category": "server",
                        "displayType": "3943",
                        "name": "Lenovo System x3250 M6",
                        "inventoryMT": "false",
                        "type": "3943",
                        "supportDownload": "true"
                }, {
                        "comp": "[]",
                        "category": "rackswitch",
                        "displayType": "7309",
                        "name": "IBM RackSwitch G8264",
                        "inventoryMT": "false",
                        "type": "7309G64,7309HC3,7309HC4,730964F,7309PAK,7309PAJ",
                        "supportDownload": "false"
                }, {
                        "comp": "[]",
                        "category": "server",
                        "displayType": "8956",
                        "name": "IBM Flex System x240 Compute Node",
                        "inventoryMT": "false",
                        "type": "8956",
                        "supportDownload": "true"
                }, {
                        "comp": "[]",
                        "category": "server",
                        "displayType": "2590",
                        "name": "Lenovo Flex System x440 Compute Node",
                        "inventoryMT": "false",
                        "type": "2590",
                        "supportDownload": "true"
                }, {
                        "comp": "[]",
                        "category": "server",
                        "displayType": "2591",
                        "name": "Lenovo Flex System x240 M5 Compute Node",
                        "inventoryMT": "false",
                        "type": "2591",
                        "supportDownload": "true"
                }, {
                        "comp": "[]",
                        "category": "server",
                        "displayType": "7916",
                        "name": "IBM Flex System x222 Compute Node",
                        "inventoryMT": "false",
                        "type": "7916",
                        "supportDownload": "true"
                }, {
                        "comp": "[]",
                        "category": "server",
                        "displayType": "2585",
                        "name": "IBM Flex System x220 Compute Node",
                        "inventoryMT": "false",
                        "type": "2585",
                        "supportDownload": "true"
                }, {
                        "comp": "[]",
                        "category": "rackswitch",
                        "displayType": "1455",
                        "name": "IBM RackSwitch G8052",
                        "inventoryMT": "false",
                        "type": "145548E",
                        "supportDownload": "false"
                }, {
                        "comp": "[]",
                        "category": "server",
                        "displayType": "2588",
                        "name": "Lenovo Flex System x240 Compute Node",
                        "inventoryMT": "false",
                        "type": "2588",
                        "supportDownload": "true"
                }, {
                        "comp": "[]",
                        "category": "rackswitch",
                        "displayType": "7120",
                        "name": "IBM RackSwitch G8264",
                        "inventoryMT": "false",
                        "type": "712064C",
                        "supportDownload": "false"
                }, {
                        "comp": "[]",
                        "category": "server",
                        "displayType": "7196",
                        "name": "Lenovo Flex System x280\/x480\/x880 X6 Compute Node",
                        "inventoryMT": "false",
                        "type": "7196",
                        "supportDownload": "true"
                }, {
                        "comp": "[]",
                        "category": "server",
                        "displayType": "7917",
                        "name": "IBM Flex System x440 Compute Node",
                        "inventoryMT": "false",
                        "type": "7917",
                        "supportDownload": "true"
                }, {
                        "comp": "[]",
                        "category": "server",
                        "displayType": "5128",
                        "name": "Lenovo Storage DX8200N",
                        "inventoryMT": "false",
                        "type": "5128",
                        "supportDownload": "true"
                }, {
                        "comp": "[]",
                        "category": "server",
                        "displayType": "7906",
                        "name": "IBM Flex System x220 Compute Node",
                        "inventoryMT": "false",
                        "type": "7906",
                        "supportDownload": "true"
                }, {
                        "comp": "[]",
                        "category": "rackswitch",
                        "displayType": "7120",
                        "name": "IBM RackSwitch G8052",
                        "inventoryMT": "false",
                        "type": "712048E",
                        "supportDownload": "false"
                }, {
                        "comp": "[]",
                        "category": "server",
                        "displayType": "3633",
                        "name": "Lenovo System x3250 M6",
                        "inventoryMT": "false",
                        "type": "3633",
                        "supportDownload": "true"
                }, {
                        "comp": "[]",
                        "category": "server",
                        "displayType": "5135",
                        "name": "Lenovo Storage DX8200D",
                        "inventoryMT": "false",
                        "type": "5135",
                        "supportDownload": "true"
                }, {
                        "comp": "[]",
                        "category": "server",
                        "displayType": "7903",
                        "name": "IBM Flex System x280\/x480\/x880 X6 Compute Node",
                        "inventoryMT": "false",
                        "type": "7903",
                        "supportDownload": "true"
                }, {
                        "comp": "[]",
                        "category": "rackswitch",
                        "displayType": "7309",
                        "name": "IBM RackSwitch G8052",
                        "inventoryMT": "false",
                        "type": "7309G52,7309HC1,7309HC2,730952F,7309PAC,7309PAD",
                        "supportDownload": "false"
                }, {
                        "comp": "[]",
                        "category": "rackswitch",
                        "displayType": "7159",
                        "name": "Lenovo RackSwitch G8264CS",
                        "inventoryMT": "false",
                        "type": "7159DRX,7159DFX,7159HCK,7159HCM",
                        "supportDownload": "false"
                }, {
                        "comp": "[]",
                        "category": "server",
                        "displayType": "4258",
                        "name": "Lenovo Flex System x280\/x480\/x880 X6 Compute Node",
                        "inventoryMT": "false",
                        "type": "4258",
                        "supportDownload": "true"
                }, {
                        "comp": "[]",
                        "category": "server",
                        "displayType": "4259",
                        "name": "IBM Flex System x280\/x480\/x880 X6 Compute Node",
                        "inventoryMT": "false",
                        "type": "4259",
                        "supportDownload": "true"
                }, {
                        "comp": "[]",
                        "category": "switch",
                        "displayType": "0x0138-0x0006",
                        "name": "IBM Flex System IB6131 40Gb Infiniband Switch",
                        "inventoryMT": "false",
                        "type": "0x0138-0x0006",
                        "supportDownload": "true"
                }, {
                        "comp": "[]",
                        "category": "server",
                        "displayType": "5120",
                        "name": "Lenovo Storage DX8200C",
                        "inventoryMT": "false",
                        "type": "5120",
                        "supportDownload": "true"
                }, {
                        "comp": "[]",
                        "category": "chassis",
                        "displayType": "7385",
                        "name": "Lenovo Flex Telco Chassis Management Module II",
                        "inventoryMT": "false",
                        "type": "7385",
                        "supportDownload": "true"
                }, {
                        "comp": "[]",
                        "category": "server",
                        "displayType": "8693",
                        "name": "Lenovo Converged HX Series",
                        "inventoryMT": "false",
                        "type": "8693",
                        "supportDownload": "true"
                }, {
                        "comp": "[]",
                        "category": "server",
                        "displayType": "8695",
                        "name": "Lenovo Converged HX Series",
                        "inventoryMT": "false",
                        "type": "8695",
                        "supportDownload": "true"
                }, {
                        "comp": "[]",
                        "category": "server",
                        "displayType": "9532",
                        "name": "Lenovo Flex System x240 M5 Compute Node",
                        "inventoryMT": "false",
                        "type": "9532",
                        "supportDownload": "true"
                }, {
                        "comp": "[]",
                        "category": "chassis",
                        "displayType": "8721",
                        "name": "Flex Chassis Management Module",
                        "inventoryMT": "true",
                        "type": "8721",
                        "supportDownload": "true"
                }, {
                        "comp": "[]",
                        "category": "server",
                        "displayType": "6241",
                        "name": "Lenovo System x3850 \/ x3950 X6",
                        "inventoryMT": "false",
                        "type": "6241",
                        "supportDownload": "true"
                }, {
                        "comp": "[]",
                        "category": "rackswitch",
                        "displayType": "7159",
                        "name": "Lenovo RackSwitch G8332",
                        "inventoryMT": "false",
                        "type": "7159HDE,7159CFX,7159BFX,7159HCE,7159HC8,7159BRX",
                        "supportDownload": "false"
                }, {
                        "comp": "[]",
                        "category": "server",
                        "displayType": "5465",
                        "name": "Lenovo NeXtScale nx360 M5",
                        "inventoryMT": "false",
                        "type": "5465",
                        "supportDownload": "true"
                }, {
                        "comp": "[]",
                        "category": "server",
                        "displayType": "7X01",
                        "name": "Lenovo Thinksystem SR630 Server",
                        "inventoryMT": "false",
                        "type": "7X01",
                        "supportDownload": "true"
                }, {
                        "comp": "[]",
                        "category": "server",
                        "displayType": "5463",
                        "name": "Lenovo System x3550 M5",
                        "inventoryMT": "false",
                        "type": "5463",
                        "supportDownload": "true"
                }, {
                        "comp": "[]",
                        "category": "server",
                        "displayType": "5464",
                        "name": "Lenovo System x3500 M5",
                        "inventoryMT": "false",
                        "type": "5464",
                        "supportDownload": "true"
                }, {
                        "comp": "[]",
                        "category": "server",
                        "displayType": "7X02",
                        "name": "Lenovo Thinksystem SR630 Server",
                        "inventoryMT": "false",
                        "type": "7X02",
                        "supportDownload": "true"
                }, {
                        "comp": "[]",
                        "category": "server",
                        "displayType": "7X03",
                        "name": "Lenovo Thinksystem SR550 Server",
                        "inventoryMT": "false",
                        "type": "7X03",
                        "supportDownload": "true"
                }, {
                        "comp": "[]",
                        "category": "server",
                        "displayType": "7X04",
                        "name": "Lenovo Thinksystem SR550 Server",
                        "inventoryMT": "false",
                        "type": "7X04",
                        "supportDownload": "true"
                }, {
                        "comp": "[]",
                        "category": "server",
                        "displayType": "5462",
                        "name": "Lenovo System x3650 M5",
                        "inventoryMT": "false",
                        "type": "5462",
                        "supportDownload": "true"
                }, {
                        "comp": "[]",
                        "category": "server",
                        "displayType": "7X05",
                        "name": "Lenovo Thinksystem SR650 Server",
                        "inventoryMT": "false",
                        "type": "7X05",
                        "supportDownload": "true"
                }, {
                        "comp": "[]",
                        "category": "server",
                        "displayType": "7X06",
                        "name": "Lenovo Thinksystem SR650 Server",
                        "inventoryMT": "false",
                        "type": "7X06",
                        "supportDownload": "true"
                }, {
                        "comp": "[]",
                        "category": "server",
                        "displayType": "7X07",
                        "name": "Lenovo Thinksystem SR530 Server",
                        "inventoryMT": "false",
                        "type": "7X07",
                        "supportDownload": "true"
                }, {
                        "comp": "[]",
                        "category": "server",
                        "displayType": "7X08",
                        "name": "Lenovo Thinksystem SR530 Server",
                        "inventoryMT": "false",
                        "type": "7X08",
                        "supportDownload": "true"
                }, {
                        "comp": "[]",
                        "category": "server",
                        "displayType": "7X09",
                        "name": "Lenovo Thinksystem ST550 Server",
                        "inventoryMT": "false",
                        "type": "7X09",
                        "supportDownload": "true"
                }, {
                        "comp": "[]",
                        "category": "rackswitch",
                        "displayType": "7159",
                        "name": "Lenovo RackSwitch G7028",
                        "inventoryMT": "false",
                        "type": "7159BAX,7159HCP",
                        "supportDownload": "false"
                }, {
                        "comp": "[]",
                        "category": "server",
                        "displayType": "5467",
                        "name": "Lenovo NeXtScale nx360 M5 DWC",
                        "inventoryMT": "false",
                        "type": "5467",
                        "supportDownload": "true"
                }, {
                        "comp": "[]",
                        "category": "server",
                        "displayType": "7X12",
                        "name": "Lenovo Thinksystem SR950 Server",
                        "inventoryMT": "false",
                        "type": "7X12",
                        "supportDownload": "true"
                }, {
                        "comp": "[]",
                        "category": "rackswitch",
                        "displayType": "7159",
                        "name": "Lenovo RackSwitch G8296",
                        "inventoryMT": "false",
                        "type": "7159GF5,7159GR6,7159HC5,7159HC6",
                        "supportDownload": "false"
                }, {
                        "comp": "[]",
                        "category": "server",
                        "displayType": "7X10",
                        "name": "Lenovo Thinksystem ST550 Server",
                        "inventoryMT": "false",
                        "type": "7X10",
                        "supportDownload": "true"
                }, {
                        "comp": "[]",
                        "category": "server",
                        "displayType": "7X16",
                        "name": "Lenovo Thinksystem SN550 Server",
                        "inventoryMT": "false",
                        "type": "7X16",
                        "supportDownload": "true"
                }, {
                        "comp": "[]",
                        "category": "server",
                        "displayType": "7X15",
                        "name": "Lenovo Thinksystem SN850 Server",
                        "inventoryMT": "false",
                        "type": "7X15",
                        "supportDownload": "true"
                }, {
                        "comp": "[]",
                        "category": "rackswitch",
                        "displayType": "7159",
                        "name": "Lenovo RackSwitch G8272",
                        "inventoryMT": "false",
                        "type": "7159CFV,7159HCV,7159HCW,7159CRW",
                        "supportDownload": "false"
                }, {
                        "comp": "[]",
                        "category": "server",
                        "displayType": "7X18",
                        "name": "Lenovo Thinksystem SR850 Server",
                        "inventoryMT": "false",
                        "type": "7X18",
                        "supportDownload": "true"
                }, {
                        "comp": "[]",
                        "category": "server",
                        "displayType": "7X19",
                        "name": "Lenovo Thinksystem SR850 Server",
                        "inventoryMT": "false",
                        "type": "7X19",
                        "supportDownload": "true"
                }, {
                        "comp": "[]",
                        "category": "server",
                        "displayType": "7863",
                        "name": "IBM Flex System x240 Compute Node",
                        "inventoryMT": "false",
                        "type": "7863",
                        "supportDownload": "true"
                }]
        }
}

+ Response 400
+ Response 401
+ Response 404
+ Response 409
+ Response 500

