require 'xclarity_client/version'
require 'utils/logger'

module XClarityClient
  $lxca_log = XClarityClient::XClarityLogger.new
end

require 'xclarity_client/errors/errors'

require 'xclarity_client/configuration'
require 'xclarity_client/xclarity_base'
require 'xclarity_client/xclarity_power_management_mixin'
require 'xclarity_client/xclarity_credentials_validator'
require 'xclarity_client/discover'
require 'xclarity_client/client'
require 'xclarity_client/endpoints/endpoints'
require 'xclarity_client/services/services'
require 'xclarity_client/config_target'
require 'xclarity_client/config_target_management'
require 'xclarity_client/config_profile'
require 'xclarity_client/config_profile_management'
require 'xclarity_client/config_pattern'
require 'xclarity_client/config_pattern_management'
require 'xclarity_client/error/authentication_error'
require 'xclarity_client/error/connection_failed'
require 'xclarity_client/error/connection_failed_unknown'
require 'xclarity_client/error/connection_refused'
require 'xclarity_client/error/hostname_unknown'
require 'xclarity_client/discover_request'
require 'xclarity_client/discover_request_management'
require 'xclarity_client/discovery'
require 'xclarity_client/discovery_management'
require 'xclarity_client/unmanage_request'
require 'xclarity_client/unmanage_request_management'
require 'xclarity_client/remotefileserver'
require 'xclarity_client/remotefileserver_management'
require 'xclarity_client/osimage'
require 'xclarity_client/osimage_management'
require 'xclarity_client/hostplatform'
require 'xclarity_client/hostplatform_management'
require 'xclarity_client/globalsettings'
require 'xclarity_client/globalsettings_management'
