module XClarityClient
  module Services
  end
end

require 'xclarity_client/services/xclarity_management_mixin'
require 'xclarity_client/services/xclarity_service'

require 'xclarity_client/services/aicc_management'
require 'xclarity_client/services/cabinet_management'
require 'xclarity_client/services/canister_management'
require 'xclarity_client/services/chassi_management'
require 'xclarity_client/services/cmm_management'
require 'xclarity_client/services/compliance_policy_management'
require 'xclarity_client/services/config_pattern_management'
require 'xclarity_client/services/config_profile_management'
require 'xclarity_client/services/config_target_management'
require 'xclarity_client/services/discover_request_management'
require 'xclarity_client/services/discovery_management'
require 'xclarity_client/services/event_management'
require 'xclarity_client/services/fan_management'
require 'xclarity_client/services/fan_mux_management'
require 'xclarity_client/services/ffdc_management'
require 'xclarity_client/services/globalsettings_management'
require 'xclarity_client/services/hostplatform_management'
require 'xclarity_client/services/job_management'
require 'xclarity_client/services/node_management'
require 'xclarity_client/services/osimage_management'
require 'xclarity_client/services/persisted_result_management'
require 'xclarity_client/services/power_supply_management'
require 'xclarity_client/services/remote_access_management'
require 'xclarity_client/services/remotefileserver_management'
require 'xclarity_client/services/scalable_complex_management'
require 'xclarity_client/services/switch_management'
require 'xclarity_client/services/storage_management'
require 'xclarity_client/services/unmanage_request_management'
require 'xclarity_client/services/manage_request_management'
require 'xclarity_client/services/update_repo_management'
require 'xclarity_client/services/update_comp_management'
require 'xclarity_client/services/user_management'
require 'xclarity_client/services/virtual_appliance_management'
require 'xclarity_client/services/management_server_management'
