module XClarityClient
  module Endpoints
  end
end

require 'xclarity_client/endpoints/xclarity_endpoint'
require 'xclarity_client/endpoints/aicc'
require 'xclarity_client/endpoints/cabinet'
require 'xclarity_client/endpoints/canister'
require 'xclarity_client/endpoints/chassi'
require 'xclarity_client/endpoints/cmm'
require 'xclarity_client/endpoints/config_pattern'
require 'xclarity_client/endpoints/config_profile'
require 'xclarity_client/endpoints/config_target'
require 'xclarity_client/endpoints/discover_request'
require 'xclarity_client/endpoints/discovery'
require 'xclarity_client/endpoints/event'
require 'xclarity_client/endpoints/fan_mux'
require 'xclarity_client/endpoints/fan'
require 'xclarity_client/endpoints/ffdc'
require 'xclarity_client/endpoints/job'
require 'xclarity_client/endpoints/node'
require 'xclarity_client/endpoints/persisted_result'
require 'xclarity_client/endpoints/power_supply'
require 'xclarity_client/endpoints/scalable_complex'
require 'xclarity_client/endpoints/switch'
require 'xclarity_client/endpoints/unmanage_request'
require 'xclarity_client/endpoints/update_repo'
require 'xclarity_client/endpoints/user'
require 'xclarity_client/endpoints/remote_access'
require 'xclarity_client/endpoints/globalsettings'
require 'xclarity_client/endpoints/hostplatform'
require 'xclarity_client/endpoints/osimage'
require 'xclarity_client/endpoints/remotefileserver'
require 'xclarity_client/endpoints/compliance_policy'
